#ifndef FX_ALIGNMENT_H
#define FX_ALIGNMENT_H

enum
{
	ALIGNMENT_MODE = 1000,
		ALIGNMENT_MODE_X = 0,
		ALIGNMENT_MODE_Y,
		ALIGNMENT_MODE_Z,
		ALIGNMENT_MODE_SPHERICAL,
		ALIGNMENT_MODE_BOX,
		ALIGNMENT_MODE_CYLINDRICAL,
		ALIGNMENT_MODE_NORMAL,
		ALIGNMENT_MODE_CUSTOM,
		ALIGNMENT_MODE_RANDOM,
		ALIGNMENT_MODE_VOLUMETRANSLATIONS,
	ALIGNMENT_INVERT = 1001,
	ALIGNMENT_CUSTOMDIRECTION,
	ALIGNMENT_SPACE,
	ALIGNMENT_SPACE_SELECTOR,
	
	ALIGNMENT_DUMMY_

};

#endif