CONTAINER fx_alignment
{
	NAME fx_alignment;
	INCLUDE fx_force_base;
	
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			DEFAULT 1; COLUMNS 2; 
			LINK ALIGNMENT_SPACE { ACCEPT{Obase;}}
			BUTTON ALIGNMENT_SPACE_SELECTOR {SCALE_V; FIT_H;}
		}
		
		BOOL ALIGNMENT_INVERT {}
		LONG ALIGNMENT_MODE
		{
			CYCLE
			{
				ALIGNMENT_MODE_X;
				ALIGNMENT_MODE_Y;
				ALIGNMENT_MODE_Z;
				ALIGNMENT_MODE_SPHERICAL;
				ALIGNMENT_MODE_BOX;
				ALIGNMENT_MODE_CYLINDRICAL;
				ALIGNMENT_MODE_NORMAL;
				ALIGNMENT_MODE_RANDOM;
				ALIGNMENT_MODE_CUSTOM;
				ALIGNMENT_MODE_VOLUMETRANSLATIONS;
			}
		}
		VECTOR ALIGNMENT_CUSTOMDIRECTION {MIN -1 -1 -1; MAX 1 1 1; STEP 0.001;}		
	}
}