#ifndef FX_BASE_VOLUME_H
#define FX_BASE_VOLUME_H

enum
{	
	BASE_VOLUME_DISPLAY_TAB = 6500,

	BASE_VOLUME_DRAW = 6600,
	BASE_VOLUME_DRAW_PLANE = 6601,
		BASE_VOLUME_DRAW_PLANE_OFF = 0,
		BASE_VOLUME_DRAW_PLANE_X,
		BASE_VOLUME_DRAW_PLANE_Y,
		BASE_VOLUME_DRAW_PLANE_Z,
	BASE_VOLUME_DRAW_MIX = 6602,
	BASE_VOLUME_DRAW_CUTOFF,
	BASE_VOLUME_DRAW_MAX,
	BASE_VOLUME_DRAW_COLOR,
	BASE_VOLUME_DRAW_AUTOTRANSPARENCY,
	BASE_VOLUME_DRAWMODE = 6607,
		BASE_VOLUME_DRAWMODE_VERTICES = 0,
		BASE_VOLUME_DRAWMODE_VOXELS,
		BASE_VOLUME_DRAWMODE_SLICE,
	BASE_VOLUME_DRAW_BANDWIDTH = 6608,

	BASE_VOLUME_END

};

#endif