CONTAINER fx_base_display_inspector
{
	NAME fx_base_display_inspector;
	INCLUDE fx_base_display;
	
	GROUP FX_BASE_DISPLAYTAB
	{
		COLOR INSPECTOR_DISPLAY_COLOR { OPEN; }

		SEPARATOR {LINE; }	
		
		BOOL INSPECTOR_DISPLAY_USE {}
		BOOL INSPECTOR_DISPLAY_USEFULLFORCE {HIDDEN;}
		BOOL INSPECTOR_DISPLAY_DUALPARTICLES {HIDDEN;}
		BOOL INSPECTOR_DISPLAY_EVALCONSTRAINTS {HIDDEN;}
		VECTOR INSPECTOR_DISPLAY_DIMENSION { MIN 0 0 0; UNIT METER; }
		REAL INSPECTOR_DISPLAY_STEP { MIN 0.1; MINSLIDER 0.5; MAX 5; MAXSLIDER 2.0; STEP 0.01; CUSTOMGUI REALSLIDER; }

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;
			LINK INSPECTOR_DISPLAY_PARTICLES { HIDDEN; SCALE_H; ACCEPT{fx_particlegroup; fx_group;} }
			BUTTON INSPECTOR_DISPLAY_PARTICLES_SELECTOR {HIDDEN;}
			LONG INSPECTOR_DISPLAY_FACTORY
			{
				HIDDEN;
				CYCLE
				{
					INSPECTOR_DISPLAY_FACTORY_PASSIVE;
					INSPECTOR_DISPLAY_FACTORY_VORTICITY;
					INSPECTOR_DISPLAY_FACTORY_LIQUID;
					INSPECTOR_DISPLAY_FACTORY_DIFFUSE;
				}
			}
		}
	}
}