#ifndef FX_BASE_CONSTRAINTS_H
#define FX_BASE_CONSTRAINTS_H

enum
{	
	ID_FORCE_BASE_CONSTRAINTS = 2500,
	FORCE_BASE_CONSTRAINTS = 2502,
	FORCE_BASE_MOEFFECTORS,
	FORCE_BASE_CONSTRAINTS_SELECTOR,
	ID_FORCE_BASE_CONSTRAINTS_SUB,
	
	FORCE_BASE_CONSTRAINTS_BLENDVALUES = 2550

};

#endif