CONTAINER fx_base
{
	NAME fx_base;

	GROUP
	{
		SEPARATOR FX_BASE_QUICKTAB_HEADER {}
		GROUP FX_BASE_QUICKTAB
		{
			
		}
	}

	INCLUDE Obase;
	
	GROUP FX_BASE
	{
		DEFAULT 0;

		LONG FX_BASE_PIPELINESTAGE
		{
			CYCLE
			{
			FX_BASE_PIPELINESTAGE_DEFAULT;
			FX_BASE_PIPELINESTAGE_VOLUMES;
			FX_BASE_PIPELINESTAGE_BOUNDS;
			FX_BASE_PIPELINESTAGE_EMITTERS;
			FX_BASE_PIPELINESTAGE_ADVECTION;
			FX_BASE_PIPELINESTAGE_OPERATORS;
			FX_BASE_PIPELINESTAGE_FLUID;
			FX_BASE_PIPELINESTAGE_FLUID_FORCES;
			FX_BASE_PIPELINESTAGE_FLUID_DIVERGENCE;
			FX_BASE_PIPELINESTAGE_FLUID_FLIP;
			FX_BASE_PIPELINESTAGE_POSTFLUID;
			FX_BASE_PIPELINESTAGE_DENSITY;
			FX_BASE_PIPELINESTAGE_DENSITY_ADVECTION;
			FX_BASE_PIPELINESTAGE_DENSITY_OPERATORS;
			FX_BASE_PIPELINESTAGE_FINISH;
			FX_BASE_PIPELINESTAGE_SAVE_CACHE;
			FX_BASE_PIPELINESTAGE_END;

			FX_BASE_PIPELINESTAGE_MESH_START;
			FX_BASE_PIPELINESTAGE_MESH_RECONSTRUCTION;
			FX_BASE_PIPELINESTAGE_MESH_MESHING;
			FX_BASE_PIPELINESTAGE_MESH_POST;
			FX_BASE_PIPELINESTAGE_MESH_END;
			}
		}
		LONG FX_BASE_PRIORITY {}
		BOOL FX_BASE_SPLIT {}
		BOOL FX_BASE_USEGPU { HIDDEN; }
	}
}