CONTAINER fx_base_volume
{
	NAME fx_base_volume;
	INCLUDE fx_force_base;
	INCLUDE fx_base_display;

	GROUP FX_BASE_DISPLAYTAB
	{
		LONG BASE_VOLUME_DRAWMODE
		{
			CYCLE
			{
				BASE_VOLUME_DRAWMODE_VERTICES;
				BASE_VOLUME_DRAWMODE_VOXELS;
				BASE_VOLUME_DRAWMODE_SLICE;
			}
		}
		//VERTICES/VOXELS MODE
		REAL BASE_VOLUME_DRAW_BANDWIDTH { MIN 0.0; MAX 3; STEP 0.1; }

		//DOT SLICE MODE
		LONG BASE_VOLUME_DRAW_PLANE 
		{
			CYCLE 
			{
				BASE_VOLUME_DRAW_PLANE_OFF;
				BASE_VOLUME_DRAW_PLANE_X;
				BASE_VOLUME_DRAW_PLANE_Y;
				BASE_VOLUME_DRAW_PLANE_Z;
			}
		}
		REAL BASE_VOLUME_DRAW_MIX { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		COLOR BASE_VOLUME_DRAW_COLOR {}
		REAL BASE_VOLUME_DRAW_CUTOFF { MAX 0; STEP 0.1; }
		REAL BASE_VOLUME_DRAW_MAX { MIN 0; STEP 0.1; }
		BOOL BASE_VOLUME_DRAW_AUTOTRANSPARENCY {}
	}
}