#ifndef FX_BASE_DISPLAY_INSPECTOR_H
#define FX_BASE_DISPLAY_INSPECTOR_H

enum
{		
	INSPECTOR_DISPLAY_COLOR = 8100,
	INSPECTOR_DISPLAY_DIMENSION,
	INSPECTOR_DISPLAY_USE,
	INSPECTOR_DISPLAY_STEP,
	INSPECTOR_DISPLAY_PARTICLES,
	INSPECTOR_DISPLAY_PARTICLES_SELECTOR,
	INSPECTOR_DISPLAY_FACTORY = 8106,
		INSPECTOR_DISPLAY_FACTORY_PASSIVE = 0,
		INSPECTOR_DISPLAY_FACTORY_VORTICITY,
		INSPECTOR_DISPLAY_FACTORY_LIQUID,
		INSPECTOR_DISPLAY_FACTORY_DIFFUSE,
	INSPECTOR_DISPLAY_DUALPARTICLES = 8107,
	INSPECTOR_DISPLAY_EVALCONSTRAINTS,
	INSPECTOR_DISPLAY_USEFULLFORCE
};

#endif