#ifndef FX_CSG_H
#define FX_CSG_H

enum
{
	CSG_MODE = 1000,
		CSG_MODE_UNION = 0,
		CSG_MODE_INTERSECTION,
		CSG_MODE_DIFFERENCE,
		CSG_MODE_UNIONBLEND,
	CSG_ISOSURFACE = 1001,
	CSG_VOLUME_A,
	CSG_VOLUME_B,
	CSG_VOLUME_A_SELECTOR,
	CSG_VOLUME_B_SELECTOR,
	CSG_VOLUME_SWITCH,
	CSG_BLEND_RADIUS,
	CSG_BLEND_T,
	CSG_BLENDMODE = 1009,
		CSG_BLENDMODE_RFUNC_GLOBAL = 0,
		CSG_BLENDMODE_RFUNC_LOCAL,
		CSG_BLENDMODE_MIX,
	
	CSG_DUMMY_
		
};

#endif