#ifndef FX_CONSTRAINT_PARTICLE_PROPERTY_H
#define FX_CONSTRAINT_PARTICLE_PROPERTY_H

enum
{	
	CONSTRAINT_PARTICLE_PROPERTY = 1000,
	CONSTRAINT_PARTICLE_PROPERTY_SELECTOR,
	CONSTRAINT_PARTICLE_PROPERTY_SCALARMIN,
	CONSTRAINT_PARTICLE_PROPERTY_SCALARMAX,
	CONSTRAINT_PARTICLE_PROPERTY_VECTOR,
	CONSTRAINT_PARTICLE_PROPERTY_STATE,

	CONSTRAINT_PARTICLE_PROPERTY_DUMMY_
};

#endif