CONTAINER fx_channelop_math
{
	NAME fx_channelop_math;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK CHANNELOP_MATH_CHANNEL { ACCEPT {Obase;} }
			BUTTON CHANNELOP_MATH_CHANNEL_SELECTOR { }
		}

		LONG CHANNELOP_MATH_OPERATION
		{
			CYCLE
			{
			CHANNELOP_MATH_OPERATION_ADD;
			CHANNELOP_MATH_OPERATION_SUBSTRACT;
			CHANNELOP_MATH_OPERATION_MULTIPLY;
			CHANNELOP_MATH_OPERATION_DOT;
			CHANNELOP_MATH_OPERATION_MIN;
			CHANNELOP_MATH_OPERATION_MAX;
			CHANNELOP_MATH_OPERATION_BLEND;
			}
		}
		BOOL CHANNELOP_MATH_ISVECTOR {}
		REAL CHANNELOP_MATH_VALUE_SCALAR { STEP 0.1; }
		VECTOR CHANNELOP_MATH_VALUE_VECTOR { STEP 0.1; }
		LONG CHANNELOP_MATH_COLORMODE
		{
			CYCLE
			{
				CHANNELOP_MATH_COLORMODE_OFF;
				CHANNELOP_MATH_COLORMODE_COLOR;
				CHANNELOP_MATH_COLORMODE_CONSTRAINTS;
				CHANNELOP_MATH_COLORMODE_CONSTRAINTS_PARENT;
			}
		}
		COLOR CHANNELOP_MATH_COLOR {HIDDEN;}
		LONG CHANNELOP_MATH_BLENDMODE
		{
			CYCLE
			{
				CHANNELOP_MATH_BLENDMODE_NORMAL;
				CHANNELOP_MATH_BLENDMODE_MULTIPLY;
				CHANNELOP_MATH_BLENDMODE_DARKEN;
				CHANNELOP_MATH_BLENDMODE_LIGHTEN;
				CHANNELOP_MATH_BLENDMODE_SCREEN;
				CHANNELOP_MATH_BLENDMODE_OVERLAY;
				CHANNELOP_MATH_BLENDMODE_HARDLIGHT;
				CHANNELOP_MATH_BLENDMODE_SOFTLIGHT;
				CHANNELOP_MATH_BLENDMODE_COLORDODGE;
				CHANNELOP_MATH_BLENDMODE_COLORDODGEINV;
				CHANNELOP_MATH_BLENDMODE_COLORBURN;
				CHANNELOP_MATH_BLENDMODE_SOFTBURN;
				CHANNELOP_MATH_BLENDMODE_DIFFERENCE;
				CHANNELOP_MATH_BLENDMODE_NDIFFERENCE;
				CHANNELOP_MATH_BLENDMODE_EXCLUDE;
				CHANNELOP_MATH_BLENDMODE_REFLECT;
				CHANNELOP_MATH_BLENDMODE_ADD;
				CHANNELOP_MATH_BLENDMODE_SUB;
			}
		}
		REAL CHANNELOP_MATH_BLENDVALUE {MIN 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
	}
}
			