#ifndef FX_CONSTRAINT_PARTICLEDISTANCE_H
#define FX_CONSTRAINT_PARTICLEDISTANCE_H

enum
{
	CONSTRAINT_PARTICLEDISTANCE_PARTICLES = 1000,
	CONSTRAINT_PARTICLEDISTANCE_RATIO,
	CONSTRAINT_PARTICLEDISTANCE_PARTICLES_SELECTOR,
	CONSTRAINT_PARTICLEDISTANCE_FACTORY = 1003,
		CONSTRAINT_PARTICLEDISTANCE_FACTORY_PASSIVE = 0,
		CONSTRAINT_PARTICLEDISTANCE_FACTORY_VORTICITY,
		CONSTRAINT_PARTICLEDISTANCE_FACTORY_LIQUID,
		CONSTRAINT_PARTICLEDISTANCE_FACTORY_DIFFUSE,

	CONSTRAINT_PARTICLEDISTANCE_DUMMY_
};

#endif