#ifndef fx_c4d_effector_sampler_H__
#define fx_c4d_effector_sampler_H__

enum
{
	FX_EFFS_SCALE	=	1500,
	FX_EFFS_CHANNEL,
	FX_EFFS_CHANNEL_SELECTOR,
	FX_EFFS_WEIGHT_TARGET = 1503,
		FX_EFFS_WEIGHT_TARGET_ALL = 0,
		FX_EFFS_WEIGHT_TARGET_POS,
		FX_EFFS_WEIGHT_TARGET_ROT,
		FX_EFFS_WEIGHT_TARGET_SCALE,
		FX_EFFS_WEIGHT_TARGET_COLOROPACITY,
		FX_EFFS_WEIGHT_TARGET_VISIBILITY,
		FX_EFFS_WEIGHT_TARGET_WEIGHT,			
		FX_EFFS_WEIGHT_TARGET_INDEX,
		FX_EFFS_WEIGHT_TARGET_TIME,
	FX_EFFS_VMAXLEN = 1504,
	FX_EFFS_VECMODE = 1505,
		FX_EFFS_VECMODE_LENGTH = 0,
		FX_EFFS_VECMODE_SUM,
		FX_EFFS_VECMODE_AVERAGE,
		FX_EFFS_VECMODE_X,
		FX_EFFS_VECMODE_Y,
		FX_EFFS_VECMODE_Z,
		
	FX_EFFS_END
};
#endif 
