CONTAINER fx_channel_vector
{
	NAME fx_channel_vector;
	INCLUDE fx_channel_base;
	
	GROUP GRIDCHANNEL_SPECIFICS
	{
		COLUMNS 1;
		VECTOR GRIDCHANNEL_MIN_VECTOR	{}			
		VECTOR GRIDCHANNEL_MAX_VECTOR	{}			
		VECTOR GRIDCHANNEL_RESET_VECTOR	{}
	}
	GROUP FX_BASE_DISPLAYTAB
	{
		HIDE GRIDCHANNEL_DISPLAY_MEDIUM_HIGHSUB;
		HIDE GRIDCHANNEL_DISPLAY_MEDIUM_LOWSUB;
		HIDE GRIDCHANNEL_DISPLAY_MEDIUM_ALBEDO;
		HIDE GRIDCHANNEL_DISPLAY_MEDIUM_ABSORPTION;

		BOOL GRIDCHANNEL_VECTOR_ISCOLOR {}	
	}
}