CONTAINER fx_constraint_particle_collision
{
	NAME fx_constraint_particle_collision;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{			
		GROUP CONSTRAINT_PARAMS_SID
		{			
			LONG CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE
			{
				CYCLE
				{
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_BORN;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_ALIVE;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_VISIBLE;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_COLLIDE;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_SPRAY;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_BUBBLE;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_SHEET;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_TEMP;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_SPAWN;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_PASSIVE;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_LIQUID;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_VORTICITY;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_DIFFUSE;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_STEER;
					CONSTRAINT_PARTICLE_COLLISION_ATTRIBUTE_FOLLOW;
				}
			}
		}
	}
}