#ifndef FX_CACHE_H
#define FX_CACHE_H

enum
{
	GRID_CACHE_LOAD = 2000,
	GRID_CACHE_SAVE,

	GRID_CACHE_RENDERONLY = 1000,
	GRID_CACHE_MODE = 1001,
		GRID_CACHE_MODE_LOAD = 0,
		GRID_CACHE_MODE_SAVE,
		GRID_CACHE_MODE_LOADSAVE,
	GRID_CACHE_FILESELECT = 1002,
	GRID_CACHE_FILEPATH,
	GRID_CACHE_FILENAME,
	
	GRID_CACHE_LOAD_FRAME_INITIALISE,
	GRID_CACHE_LOAD_FRAME,
	GRID_CACHE_LOAD_OFFSET,
	GRID_CACHEFILE_INFO,

	GRID_CACHE_SAVE_COMPRESS,
	GRID_CACHE_SAVE_GRIDS = 1010,
		GRID_CACHE_SAVE_GRIDS_EFFEX = 0,
		GRID_CACHE_SAVE_GRIDS_FIELD3D,
		GRID_CACHE_SAVE_GRIDS_OPENVDB,
		GRID_CACHE_SAVE_GRIDS_OPENVDBFX,
	GRID_CACHE_SAVE_FRAME = 1011,
		GRID_CACHE_SAVE_FRAME_SIM = 0,
		GRID_CACHE_SAVE_FRAME_C4D,
	GRID_CACHE_CHANNELS = 1012,
	GRID_CACHE_PATHMODE = 1013,
		GRID_CACHE_PATHMODE_SCENEPATH = 0,
		GRID_CACHE_PATHMODE_CUSTOM,
	GRID_CACHE_LOAD_FRAME_REVERSE = 1014,
	GRID_CACHE_SEQUENCEINFO,
	GRID_CACHE_DELETE,
	GRID_CACHE_CHANNELS_SELECTOR,
	GRID_CACHE_DURATION,
	GRID_CACHE_DURATION_SELECTOR,
	GRID_CACHE_LOAD_RESAMPLE_IPOL = 1020,
		GRID_CACHE_LOAD_RESAMPLE_IPOL_LINEAR = 0,
		GRID_CACHE_LOAD_RESAMPLE_IPOL_CUBIC,
		GRID_CACHE_LOAD_RESAMPLE_IPOL_HERMITE,
	GRID_CACHE_PADDING = 1021,
		GRID_CACHE_PADDING_OFF = -1,
		GRID_CACHE_PADDING_3 = 3,
		GRID_CACHE_PADDING_4,
		GRID_CACHE_PADDING_5,
		GRID_CACHE_PADDING_6,
	GRID_CACHE_SAVE_THRESHOLD = 1022,
	GRID_CACHE_LOAD_RESAMPLE_IPOLVDB = 1023,
		GRID_CACHE_LOAD_RESAMPLE_IPOLVDB_NEAREST = 0,
		GRID_CACHE_LOAD_RESAMPLE_IPOLVDB_LINEAR,
		GRID_CACHE_LOAD_RESAMPLE_IPOLVDB_QUADRATIC,
	GRID_CACHE_LOAD_KEEPCACHED = 1024,
	GRID_CACHE_LOAD_SCALE,

	GRID_CACHE_DUMMY_
};

#endif