#ifndef FX_CONSTRAINT_NOISE_H
#define FX_CONSTRAINT_NOISE_H

enum
{
	CONSTRAINT_NOISE_PREVIEW = 1000,
	CONSTRAINT_NOISE_SCALE,
	CONSTRAINT_NOISE_SCALE3D,
	CONSTRAINT_NOISE_OCTAVES,
	CONSTRAINT_NOISE_TYPE,
	CONSTRAINT_NOISE_CONTRAST,
	CONSTRAINT_NOISE_ANIMATION,
	CONSTRAINT_NOISE_BRIGHTNESS,
	CONSTRAINT_NOISE_SEED,
	CONSTRAINT_NOISE_LOOP,
	CONSTRAINT_NOISE_LOWCLIP,
	CONSTRAINT_NOISE_HIGHCLIP,
	CONSTRAINT_NOISE_ABSOLUTE,
	CONSTRAINT_NOISE_DETAILATT,
	CONSTRAINT_NOISE_SAMPLINGDELTA,

	CONSTRAINT_NOISE_DUMMY_
};

#endif