#ifndef FX_CONSTRAINT_STRAIN_H
#define FX_CONSTRAINT_STRAIN_H

enum
{
	CONSTRAINT_STRAIN_CHANNEL = 1000,
	CONSTRAINT_STRAIN_CHANNEL_SELECTOR,
	CONSTRAINT_STRAIN_LENGTH,
	CONSTRAINT_STRAIN_MODE = 1003,
		CONSTRAINT_STRAIN_MODE_MEAN = 0,
		CONSTRAINT_STRAIN_MODE_SHEAR,
		CONSTRAINT_STRAIN_MODE_NORMALX,
		CONSTRAINT_STRAIN_MODE_NORMALY,
		CONSTRAINT_STRAIN_MODE_NORMALZ,
		CONSTRAINT_STRAIN_MODE_SHEARXY,
		CONSTRAINT_STRAIN_MODE_SHEARXZ,
		CONSTRAINT_STRAIN_MODE_SHEARYZ,
	CONSTRAINT_STRAIN_ABSOLUTE = 1004,

	CONSTRAINT_STRAIN_DUMMY_
};

#endif