CONTAINER fx_constraint
{
	NAME fx_constraint;
	INCLUDE fx_force_base;
	INCLUDE fx_base_display_inspector;
	HIDE FX_BASE;
	
	GROUP ID_FORCE_BASE
	{
		BOOL CONSTRAINT_INVERT {}
		REAL CONSTRAINT_INTENSITY {MINSLIDER 0.0; MAXSLIDER 200; UNIT PERCENT; CUSTOMGUI REALSLIDER;}		

		SEPARATOR { LINE; }

		GROUP CONSTRAINT_PARAMS_SID
		{			
		}
		GROUP CONSTRAINT_MAPPING_SID
		{			
			DEFAULT 1;
			BOOL CONSTRAINT_MAPPING_CLAMP_MIN {}
			BOOL CONSTRAINT_MAPPING_CLAMP_MAX {}
			REAL CONSTRAINT_MAPPING_INPUT_MIN {STEP 0.1;CUSTOMGUI DOUBLE; DSIZE 70; DDIGITS 8; }
			REAL CONSTRAINT_MAPPING_INPUT_MAX {STEP 0.1;CUSTOMGUI DOUBLE; DSIZE 70; DDIGITS 8; }
			REAL CONSTRAINT_MAPPING_OUTPUT_MIN {STEP 0.1;CUSTOMGUI DOUBLE; DSIZE 70; DDIGITS 8; }
			REAL CONSTRAINT_MAPPING_OUTPUT_MAX {STEP 0.1;CUSTOMGUI DOUBLE; DSIZE 70; DDIGITS 8; }
			
			BOOL CONSTRAINT_MAPPING_SPLINE_USE {}
			SPLINE CONSTRAINT_MAPPING_SPLINE { SHOWGRID_H; X_MIN 0; X_MAX 1; Y_MIN 0; Y_MAX 1; X_STEPS 0.01; Y_STEPS 0.01;	}
			
			BOOL CONSTRAINT_MAPPING_COLOR_USE {}
			GRADIENT CONSTRAINT_MAPPING_COLOR {COLOR;ICC_BASEDOCUMENT;}
		}
	}
}