#ifndef FX_CONSTRAINT_GRADIENT_H
#define FX_CONSTRAINT_GRADIENT_H

enum
{
	CONSTRAINT_GRADIENT = 1000,
	CONSTRAINT_GRADIENT_AXIS = 1001,
		CONSTRAINT_GRADIENT_AXIS_X = 0,
		CONSTRAINT_GRADIENT_AXIS_Y,
		CONSTRAINT_GRADIENT_AXIS_Z,
		CONSTRAINT_GRADIENT_AXIS_SPHERE,
	CONSTRAINT_GRADIENT_ORIGIN = 1002,
	CONSTRAINT_GRADIENT_DISTANCE,
	CONSTRAINT_GRADIENT_CLAMPAXIS,
	CONSTRAINT_GRADIENT_ALIGNMENT,
	CONSTRAINT_GRADIENT_ALIGNMENT_SELECTOR,
	CONSTRAINT_GRADIENT_SQUARED,

	CONSTRAINT_GRADIENT_DUMMY_
};

#endif