#ifndef fx_c4d_obstacle_H_
#define fx_c4d_obstacle_H_

enum
{
	SUB_FXOBSTACLE_MATERIAL = 2200,
	SUB_FXOBSTACLE_DYNAMICS,
	SUB_FXOBSTACLE_COLLISION,
	SUB_FXOBSTACLE_COUPLING,
	SUB_FXOBSTACLE_DYNAMICS_CONSTRAINTS,
	SUB_FXOBSTACLE_COLLISION_CONSTRAINTS,
	SUB_FXOBSTACLE_CACHE,
	
	SEP_FXOBSTACLE_COUPLING_SOLID,
	SEP_FXOBSTACLE_COUPLING_FLUID,
	SEP_FXOBSTACLE_CACHE_LOAD,

	FXOBSTACLE_DYNAMIC_STATE = 2000,
		FXOBSTACLE_DYNAMIC_STATE_STATIC = 0,
		FXOBSTACLE_DYNAMIC_STATE_KINEMATIC,
		FXOBSTACLE_DYNAMIC_STATE_DYNAMIC,
	FXOBSTACLE_COLLISION_SHAPE = 2001,
		FXOBSTACLE_COLLISION_SHAPE_BOX = 0,
		FXOBSTACLE_COLLISION_SHAPE_MESH,
	FXOBSTACLE_MASS = 2002,
	FXOBSTACLE_DENSITY,
	FXOBSTACLE_STRENGTH_TRANSLATION,
	FXOBSTACLE_STRENGTH_ROTATION,
	FXOBSTACLE_GHOST,
	FXOBSTACLE_DEACTIVATION,

	FXOBSTACLE_MATERIAL_SPEC = 2008,
		FXOBSTACLE_MATERIAL_SPEC_MASS = 0,
		FXOBSTACLE_MATERIAL_SPEC_DENSITY,
	
	FXOBSTACLE_COLLISION_DAMPING = 2009,
	FXOBSTACLE_COLLISION_DAMPING_ANGULAR,
	
	FXOBSTACLE_COLLISION_MARGIN = 2011,
	FXOBSTACLE_COLLISION_BOUNCE,
	FXOBSTACLE_COLLISION_FRICTION,
	FXOBSTACLE_COLLISION_FRICTION_ANGULAR,
	FXOBSTACLE_COLLISION_ANISOTROPIC_FRICTION_MODE = 2015,
		FXOBSTACLE_COLLISION_ANISOTROPIC_FRICTION_MODE_OFF = 0,
		FXOBSTACLE_COLLISION_ANISOTROPIC_FRICTION_MODE_LINEAR,
		FXOBSTACLE_COLLISION_ANISOTROPIC_FRICTION_MODE_ANGULAR,
	FXOBSTACLE_COLLISION_ANISOTROPIC_FRICTION = 2016,
	FXOBSTACLE_COLLISION_ANISOTROPIC_FRICTION_AUTO,
	FXOBSTACLE_COLLISION_SAMPLE_MODE = 2018,
		FXOBSTACLE_COLLISION_SAMPLE_MODE_FIRST = 0,
		FXOBSTACLE_COLLISION_SAMPLE_MODE_ALL,
	FXOBSTACLE_CENTEROFMASS = 2019,
	FXOBSTACLE_DEACTIVATION_ANGULAR,
	FXOBSTACLE_DYNAMICS_FACTOR_LINEAR,
	FXOBSTACLE_DYNAMICS_FACTOR_ANGULAR,
	FXOBSTACLE_DYNAMICS_INITIAL_DIR,
	FXOBSTACLE_DYNAMICS_INITIAL_FORCE,
		
	FXOBSTACLE_DYNAMICS_CONSTRAINTS_DAMPING,
	FXOBSTACLE_DYNAMICS_CONSTRAINTS_DAMPING_ANGULAR,
	FXOBSTACLE_COLLISION_CONSTRAINTS_BOUNCE,
	FXOBSTACLE_COLLISION_CONSTRAINTS_FRICTION,
	FXOBSTACLE_COLLISION_CONSTRAINTS_FRICTION_ANGULAR,
	
	FXOBSTACLE_STRENGTH_TRANSLATION_FLUID,
	FXOBSTACLE_STRENGTH_ROTATION_FLUID,
	FXOBSTACLE_DYNAMICS_ACTIVE_ON_COLL,
	FXOBSTACLE_DYNAMICS_TRANSFER_TO_ORIG,
	FXOBSTACLE_DYNAMICS_ACTIVE_ON_VELO,
	FXOBSTACLE_DYNAMICS_ACTIVE_ON_VELO_THRESHOLD,
	FXOBSTACLE_CACHE_USE,
	FXOBSTACLE_CACHE_DURATION,
	FXOBSTACLE_CACHE_SUBFRAMES,
	FXOBSTACLE_CACHE_CLEAR,
	FXOBSTACLE_CACHE_LOAD,
	FXOBSTACLE_CACHE_OFFSET,
	FXOBSTACLE_DYNAMICS_INITIAL_DIR_SELECTOR,

	OBSTACLE_DUMMY_

};

#endif