#ifndef FX_CONSTRAINT_H
#define FX_CONSTRAINT_H

enum
{
	CONSTRAINT_INVERT = 1100,
	ID_CONSTRAINT_BASE,
	CONSTRAINT_GLOBAL,
	CONSTRAINT_INTENSITY,
	
	CONSTRAINT_PARAMS_SID,
	CONSTRAINT_MAPPING_SID,
	CONSTRAINT_MAPPING_CLAMP_MIN,
	CONSTRAINT_MAPPING_CLAMP_MAX,
	CONSTRAINT_MAPPING_INPUT_MIN,
	CONSTRAINT_MAPPING_INPUT_MAX,
	CONSTRAINT_MAPPING_OUTPUT_MIN,
	CONSTRAINT_MAPPING_OUTPUT_MAX,		
	CONSTRAINT_MAPPING_SPLINE_USE,
	CONSTRAINT_MAPPING_SPLINE,
	CONSTRAINT_MAPPING_COLOR_USE,
	CONSTRAINT_MAPPING_COLOR,

	CONSTRAINT_DUMMY_
};

#endif