CONTAINER fx_cache_mesh
{
	NAME fx_cache_mesh;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			IN_EXCLUDE MESH_CACHE_MESHERS
			{
				SEND_SELCHNGMSG 1;
				NUM_FLAGS 0; 
				ACCEPT { fx_mesher; };
			}
			BUTTON MESH_CACHE_MESHERS_SELECTOR {}
			LINK MESH_CACHE_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON MESH_CACHE_DURATION_SELECTOR {}
		}
		
		SEPARATOR{LINE;}
		
		BOOL MESH_CACHE_RENDERONLY {}
		LONG MESH_CACHE_MODE
		{
			ANIM OFF;
			CYCLE
			{
				MESH_CACHE_MODE_LOAD;
				MESH_CACHE_MODE_SAVE;
				MESH_CACHE_MODE_LOADSAVE;
			}
		}
		LONG MESH_CACHE_PATHMODE
		{
			ANIM OFF;
			CYCLE
			{
				MESH_CACHE_PATHMODE_SCENEPATH;
				MESH_CACHE_PATHMODE_CUSTOM;
			}
		}

		SEPARATOR{LINE;}

		GROUP
		{
			COLUMNS 2;
			STRING MESH_CACHE_FILEPATH {ANIM OFF;SCALE_H;}
			BUTTON MESH_CACHE_FILESELECT {FIT_H;}

			STRING MESH_CACHE_FILENAME {ANIM OFF;SCALE_H;}
			LONG MESH_CACHE_SAVE_FORMAT
			{
				ANIM OFF;
				CYCLE
				{
					MESH_CACHE_SAVE_FORMAT_EFFEX;
					//MESH_CACHE_SAVE_FORMAT_C4D;
				}
			}			
			BUTTON MESH_CACHE_DELETE {FIT_H;}
			LONG MESH_CACHE_PADDING 
			{
				CYCLE
				{
					MESH_CACHE_PADDING_OFF;
					MESH_CACHE_PADDING_3;
					MESH_CACHE_PADDING_4;
					MESH_CACHE_PADDING_5;
					MESH_CACHE_PADDING_6;
				}
			}
			STRING MESH_CACHE_SEQUENCEINFO { CUSTOMGUI MULTISTRING; READONLY; }
			
		}
		
		SEPARATOR {}
				
		GROUP MESH_CACHE_LOAD
		{
			DEFAULT 1;
			BOOL MESH_CACHE_LOAD_FRAME_REVERSE {}
			LONG MESH_CACHE_LOAD_FRAME {MIN -1; }
			LONG MESH_CACHE_LOAD_OFFSET { }
						
			SEPARATOR{LINE;}
			
			STRING MESH_CACHEFILE_INFO { CUSTOMGUI MULTISTRING; }
		}
		GROUP MESH_CACHE_SAVE
		{
			DEFAULT 1;
			BOOL MESH_CACHE_SAVE_COMPRESS {ANIM OFF; }
			LONG MESH_CACHE_SAVE_FRAME 
			{
				ANIM OFF;
				CYCLE
				{
					MESH_CACHE_SAVE_FRAME_SIM;
					MESH_CACHE_SAVE_FRAME_C4D;
				}
			}
		}
	}
}