#ifndef FX_CONSTRAINT_GRIDVALUE_H
#define FX_CONSTRAINT_GRIDVALUE_H

enum
{
	CONSTRAINT_GRIDVALUE_CHANNEL = 1000,
	CONSTRAINT_GRIDVALUE_MODE = 1001,
		CONSTRAINT_GRIDVALUE_MODE_ISEQUAL = 0,
		CONSTRAINT_GRIDVALUE_MODE_ISNOT,
		CONSTRAINT_GRIDVALUE_MODE_RANGE_SEGE,
		CONSTRAINT_GRIDVALUE_MODE_RANGE_GESE,
	CONSTRAINT_GRIDVALUE_A = 1002,
	CONSTRAINT_GRIDVALUE_B,
	CONSTRAINT_GRIDVALUE_MAPRESULTS,
	CONSTRAINT_GRIDVALUE_SPLINE,
	CONSTRAINT_GRIDVALUE_CHANNEL_SELECTOR,
	CONSTRAINT_GRIDVALUE_VECLENGTH,
	CONSTRAINT_GRIDVALUE_DYNAMICS = 1008,
		CONSTRAINT_GRIDVALUE_DYNAMICS_DIVERGENCE = 0,
		CONSTRAINT_GRIDVALUE_DYNAMICS_PRESSURE,
		CONSTRAINT_GRIDVALUE_DYNAMICS_VELOCITY,

	CONSTRAINT_GRIDVALUE_DUMMY_
};

#endif