CONTAINER fx_c4d_attach
{
	NAME fx_c4d_attach;
	INCLUDE Obase;

	//Basic Tab
	GROUP ID_OBJECTPROPERTIES
	{			
		DEFAULT 1;
		BOOL FXC4D_ATTACH_RENDERONLY {}
		LINK FXC4D_ATTACH_LINK {ACCEPT{fx_particlegroup;}; }

		LONG FXC4D_ATTACH_FACTORY
		{
			CYCLE
			{
				FXC4D_ATTACH_FACTORY_PASSIVE;
				FXC4D_ATTACH_FACTORY_VORTICITY;
				FXC4D_ATTACH_FACTORY_IMPLICIT;
				FXC4D_ATTACH_FACTORY_DIFFUSE;
			}
		}
		
		LONG FXC4D_ATTACH_INSTANCE
		{
			CYCLE
			{
				FXC4D_ATTACH_INSTANCE_ORIG;
				FXC4D_ATTACH_INSTANCE_INSTANCE;
				FXC4D_ATTACH_INSTANCE_RENDERINSTANCE;
			}
		}
	}		
	GROUP FXC4D_ATTACH_GENERATION
	{
		LONG FXC4D_ATTACH_SPLIT { MIN 10000; }
		LONG FXC4D_ATTACH_SPLITPART { MIN 1; MAX 1000; }

		GROUP FXC4D_ATTACH_CLOUD_SID
		{
			COLUMNS 2;
			LONG FXC4D_ATTACH_CLOUDCNT {	MIN 0; }
			REAL FXC4D_ATTACH_CLOUDCNT_VAR { MIN 0; MAX 100; UNIT PERCENT;}
			REAL FXC4D_ATTACH_CLOUDOFFSET { UNIT METER; }			
			REAL FXC4D_ATTACH_CLOUDOFFSET_VAR { MIN 0; MAX 100; UNIT PERCENT;}

			REAL FXC4D_ATTACH_CLOUD_ADVECTION {MIN -1.0; MAX 1.0;}
		}

		GROUP FXC4D_ATTACH_DIMENSIONS
		{
			VECTOR	 FXC4D_ATTACH_SCALE	{MIN 0 0 0;}
			VECTOR	 FXC4D_ATTACH_VELSCALE {MIN 0 0 0; UNIT PERCENT;}
			LONG	FXC4D_ATTACH_SCALE_FPBASE	
			{
				CYCLE
				{
					FXC4D_ATTACH_SCALE_FPBASE_OFF;
					FXC4D_ATTACH_SCALE_FPBASE_PRAD;
					FXC4D_ATTACH_SCALE_FPBASE_SMOKE;
					FXC4D_ATTACH_SCALE_FPBASE_VELOCITY;
					FXC4D_ATTACH_SCALE_FPBASE_TEMP;
					FXC4D_ATTACH_SCALE_FPBASE_FUEL;
					//FXC4D_ATTACH_SCALE_FPBASE_SIMSMOKE;
					//FXC4D_ATTACH_SCALE_FPBASE_SIMTEMP;
					//FXC4D_ATTACH_SCALE_FPBASE_SIMFUEL;
					//FXC4D_ATTACH_SCALE_FPBASE_SIMFIRE;
				}
			}
			LONG	FXC4D_ATTACH_SCALE_VPBASE	
			{
				CYCLE
				{
					FXC4D_ATTACH_SCALE_VPBASE_OFF;
					FXC4D_ATTACH_SCALE_VPBASE_PRAD;
					FXC4D_ATTACH_SCALE_VPBASE_VORTICITY;
					FXC4D_ATTACH_SCALE_VPBASE_VELOCITY;
				}
			}
			LONG	FXC4D_ATTACH_SCALE_SPBASE	
			{
				CYCLE
				{
					FXC4D_ATTACH_SCALE_SPBASE_OFF;
					FXC4D_ATTACH_SCALE_SPBASE_PRAD;
					FXC4D_ATTACH_SCALE_SPBASE_VELOCITY;
				}
			}
			REAL	FXC4D_ATTACH_SCALE_PRAD	{MIN 0; UNIT METER;}
			REAL	FXC4D_ATTACH_SCALE_VAR	{MIN 0; MAX 100; UNIT PERCENT;}

			GRADIENT FXC4D_ATTACH_SCALE_AGEX {ALPHA;ANIM ON;}
			GRADIENT FXC4D_ATTACH_SCALE_AGEY {ALPHA;ANIM ON;}
			GRADIENT FXC4D_ATTACH_SCALE_AGEZ {ALPHA;ANIM ON;}
		}
		GROUP FXC4D_ATTACH_ROTATION
		{			
			LONG FXC4D_ATTACH_ALIGNMENT 
			{
				CYCLE
				{
					FXC4D_ATTACH_ALIGNMENT_X;
					FXC4D_ATTACH_ALIGNMENT_Y;
					FXC4D_ATTACH_ALIGNMENT_Z;
					FXC4D_ATTACH_ALIGNMENT_TANGENT;
					FXC4D_ATTACH_ALIGNMENT_BILLBOARD;
					FXC4D_ATTACH_ALIGNMENT_NORMAL;
				}
			}
			VECTOR FXC4D_ATTACH_BILLOW	{MIN -360 -360 -360; MAX 360 360 360; UNIT DEGREE;}
			LONG	FXC4D_ATTACH_BILLOW_FPBASE	
			{
				CYCLE
				{
					FXC4D_ATTACH_BILLOW_FPBASE_OFF;
					FXC4D_ATTACH_BILLOW_FPBASE_PRAD;
					FXC4D_ATTACH_BILLOW_FPBASE_SMOKE;
					FXC4D_ATTACH_BILLOW_FPBASE_VELOCITY;
					FXC4D_ATTACH_BILLOW_FPBASE_TEMP;
					FXC4D_ATTACH_BILLOW_FPBASE_FUEL;
				}
			}
			LONG	FXC4D_ATTACH_BILLOW_VPBASE	
			{
				CYCLE
				{
					FXC4D_ATTACH_BILLOW_VPBASE_OFF;
					FXC4D_ATTACH_BILLOW_VPBASE_PRAD;
					FXC4D_ATTACH_BILLOW_VPBASE_VORTICITY;
					FXC4D_ATTACH_BILLOW_VPBASE_VELOCITY;
				}
			}
			LONG	FXC4D_ATTACH_BILLOW_SPBASE	
			{
				CYCLE
				{
					FXC4D_ATTACH_BILLOW_SPBASE_OFF;
					FXC4D_ATTACH_BILLOW_SPBASE_PRAD;
					FXC4D_ATTACH_BILLOW_SPBASE_VELOCITY;
				}
			}
			REAL	FXC4D_ATTACH_BILLOW_PRAD	{MIN 0; UNIT METER;}
			REAL	FXC4D_ATTACH_BILLOW_VAR	{MIN 0; MAX 100; UNIT PERCENT;}
			SPLINE	FXC4D_ATTACH_BILLOW_VARSEED	
			{
				SHOWGRID_H; 
													  
				X_MIN 0; 
				X_MAX 1; 
									  
				Y_MIN 0; 
				Y_MAX 1; 
									  
				X_STEPS 0.01; 
				Y_STEPS 0.01; 
			}

			GRADIENT FXC4D_ATTACH_BILLOW_AGEX {ALPHA;ANIM ON;}
			GRADIENT FXC4D_ATTACH_BILLOW_AGEY {ALPHA;ANIM ON;}
			GRADIENT FXC4D_ATTACH_BILLOW_AGEZ {ALPHA;ANIM ON;}
		}
		GROUP FXC4D_ATTACH_PROPERTIES
		{			
			//FLUID PARTICLES
			LONG FXC4D_ATTACH_FLUIDGROUP
			{
				CYCLE
				{
					FXC4D_ATTACH_FLUIDGROUP_ALL;
				}
			}
			BOOL FXC4D_ATTACH_SETCOLOR {}

			//VORTICITY PARTICLES
			LONG FXC4D_ATTACH_SUBGRIDLAYER 
			{
				CYCLE
				{	
					FXC4D_ATTACH_SUBGRIDLAYER_PARENT;
				}
			}
		}
	}
	
}