CONTAINER fx_constraint_quadratic
{
	NAME fx_constraint_quadratic;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{
		GROUP CONSTRAINT_PARAMS_SID
		{		
			LONG CONSTRAINT_QUADRATIC 
			{ 
				CYCLE
				{
					CONSTRAINT_QUADRATIC_SPHERE;
					CONSTRAINT_QUADRATIC_ELLIPSOID;
					CONSTRAINT_QUADRATIC_BOX;
					CONSTRAINT_QUADRATIC_TORUS;
					CONSTRAINT_QUADRATIC_CYLINDER;
				}
			}
			VECTOR CONSTRAINT_QUADRATIC_RADIUS {MIN 0.01; UNIT METER; }
			REAL CONSTRAINT_QUADRATIC_RADIUS_SPHERE {MIN 0.01; UNIT METER; }
		}
	}
}