CONTAINER fx_channel_fire
{
	NAME fx_channel_fire;
	INCLUDE fx_channel_scalar;
	
	GROUP GRIDCHANNEL_SPECIFICS
	{
		REAL GRIDCHANNEL_FIRE_COOLING_POINT {MIN 1; MAX 5000; STEP 0.01;}
		REAL GRIDCHANNEL_FIRE_DEATHRATE	{MIN 0.001; MAX 100; STEP 0.001;}
		REAL GRIDCHANNEL_FIRE_AFTERLIFE	{MIN 0.001; MAX 100; STEP 0.001;}
	}
}