CONTAINER fx_channel_base
{
	NAME fx_channel_base;
	INCLUDE fx_force_base;
	INCLUDE fx_base_display;
	
	GROUP FX_BASE_QUICKTAB
	{		
		BUTTON GRIDCHANNEL_CREATEADVECTION {}
	}
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		LONG GRIDCHANNEL_DATATYPE
		{
			HIDDEN;
			CYCLE
			{
				GRIDCHANNEL_DATATYPE_SCALAR;
				GRIDCHANNEL_DATATYPE_VECTOR;
			}
		}
		GROUP GRIDCHANNEL_SPECIFICS
		{
			COLUMNS 2;
		}
		BOOL GRIDCHANNEL_CLEAR {}
		BOOL GRIDCHANNEL_CONTRIBUTE {}
		BOOL GRIDCHANNEL_CONVECT {}
		LONG GRIDCHANNEL_ADAPTIVE { HIDDEN; MIN 0; }
	}
	GROUP FX_BASE_DISPLAYTAB
	{
		BOOL GRIDCHANNEL_DRAWBOUNDS {}		

		SEPARATOR {LINE;}

		LONG GRIDCHANNEL_DISPLAY_TYPE
		{
			CYCLE
			{
				GRIDCHANNEL_DISPLAY_TYPE_MEDIUM;
				GRIDCHANNEL_DISPLAY_TYPE_DOTSLICE;
			}
		}

		//DOT SLICE MODE
		LONG GRIDCHANNEL_DISPLAY_PLANE 
		{
			CYCLE {
			GRIDCHANNEL_DISPLAY_PLANE_OFF;
			GRIDCHANNEL_DISPLAY_PLANE_X;
			GRIDCHANNEL_DISPLAY_PLANE_Y;
			GRIDCHANNEL_DISPLAY_PLANE_Z;
			}
		}
		REAL GRIDCHANNEL_DISPLAY_MIX { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		BOOL GRIDCHANNEL_DISPLAY_AUTOTRANSPARENCY {}
		COLOR GRIDCHANNEL_DISPLAY_COLOR {}
		REAL GRIDCHANNEL_DISPLAY_CUTOFF { MIN 0; MAX 99; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		REAL GRIDCHANNEL_DISPLAY_MAX { MIN 1; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR {LINE;}

		//MEDIUM MODE
		LONG GRIDCHANNEL_DISPLAY_MEDIUM_HIGHSUB { MIN 1; }
		LONG GRIDCHANNEL_DISPLAY_MEDIUM_LOWSUB { MIN 1; }
		REAL GRIDCHANNEL_DISPLAY_MEDIUM_ALBEDO { MIN 0; MAX 100; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
		REAL GRIDCHANNEL_DISPLAY_MEDIUM_ABSORPTION { MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER;}
	}
}