#ifndef FX_CONSTRAINT_COLLISION_H
#define FX_CONSTRAINT_COLLISION_H

enum
{
	CONSTRAINT_COLLISION_PARTICLES = 1000,
	CONSTRAINT_COLLISION_PARTICLES_SELECTOR,
	PARTICLE_COLLISION_FACTORY = 1002,
		PARTICLE_COLLISION_FACTORY_PASSIVE = 0,
		PARTICLE_COLLISION_FACTORY_VORTICITY,
		PARTICLE_COLLISION_FACTORY_LIQUID,
		PARTICLE_COLLISION_FACTORY_DIFFUSE,
	CONSTRAINT_COLLISION_MAXDISTANCE = 1003,

	CONSTRAINT_COLLISION_DUMMY_
};

#endif