#ifndef FX_CONSTRAINT_SOUND_H
#define FX_CONSTRAINT_SOUND_H

enum
{	
	CONSTRAINT_SOUND_MAP = 1050,
		CONSTRAINT_SOUND_MAP_WORLD = 0,
		CONSTRAINT_SOUND_MAP_PHYSICAL,
		CONSTRAINT_SOUND_MAP_OBJECT,
		CONSTRAINT_SOUND_MAP_INDEX,
	CONSTRAINT_SOUND_MAP_PLANE = 1051,
		CONSTRAINT_SOUND_MAP_PLANE_XY = 0,
		CONSTRAINT_SOUND_MAP_PLANE_YZ,
		CONSTRAINT_SOUND_MAP_PLANE_XZ,
	CONSTRAINT_SOUND_MAP_COORDINATES = 1052,
		CONSTRAINT_SOUND_MAP_COORDINATES_LINEAR = 0,
		CONSTRAINT_SOUND_MAP_COORDINATES_POLAR,
	CONSTRAINT_SOUND_SAMPLEMODE = 1053,
		CONSTRAINT_SOUND_SAMPLEMODE_MAX,
		CONSTRAINT_SOUND_SAMPLEMODE_AVERAGE,
	CONSTRAINT_SOUND_MAP_USEBOUNDS = 1054,
	CONSTRAINT_SOUND_MAP_STARTUV,
	CONSTRAINT_SOUND_MAP_ENDUV,
	CONSTRAINT_SOUND_MAP_STARTPOLAR,
	CONSTRAINT_SOUND_MAP_ENDPOLAR,
	CONSTRAINT_SOUND_FREQGRAPH,
	CONSTRAINT_SOUND_FREQMIN,
	CONSTRAINT_SOUND_FREQMAX,
	CONSTRAINT_SOUND,
	CONSTRAINT_SOUND_SELECTOR,
	CONSTRAINT_SOUND_PREVIEWSIZE,
	CONSTRAINT_SOUND_MAP_COLOR,
	
	CONSTRAINT_SOUND_SAMPLING_G = 1500,
	CONSTRAINT_SOUND_MAPPING_G
};

#endif