CONTAINER fx_cache
{
	NAME fx_cache;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	HIDE FX_BASE_PIPELINESTAGE;
	
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			IN_EXCLUDE GRID_CACHE_CHANNELS
			{
				SEND_SELCHNGMSG 1;
				NUM_FLAGS 0; 
				ACCEPT 
				{  
					fx_channel_velocity; 
					fx_channel_levelset;
					fx_channel_scalar; 
					fx_surface_reconstruction; 
					fx_channel_temp; 
					fx_channel_fuel; 
					fx_channel_fire; 
					fx_channel_vector; 
					fx_fluid; 
					fx_liquid;
				}
			}
			BUTTON GRID_CACHE_CHANNELS_SELECTOR {}

			LINK GRID_CACHE_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON GRID_CACHE_DURATION_SELECTOR {}
		}
		
		SEPARATOR{LINE;}
		
		BOOL GRID_CACHE_RENDERONLY {}
		LONG GRID_CACHE_MODE 
		{
			CYCLE
			{
				GRID_CACHE_MODE_LOAD;
				GRID_CACHE_MODE_SAVE;
				//GRID_CACHE_MODE_LOADSAVE;
			}
		}
		LONG GRID_CACHE_PATHMODE 
		{
			ANIM OFF;
			CYCLE
			{
				GRID_CACHE_PATHMODE_SCENEPATH;
				GRID_CACHE_PATHMODE_CUSTOM;
			}
		}

		SEPARATOR{LINE;}

		GROUP
		{
			COLUMNS 2;
			STRING GRID_CACHE_FILEPATH {ANIM OFF;SCALE_H;}
			BUTTON GRID_CACHE_FILESELECT {FIT_H;}

			STRING GRID_CACHE_FILENAME {ANIM OFF;SCALE_H;}
			LONG GRID_CACHE_SAVE_GRIDS
			{
				ANIM OFF;
				CYCLE
				{
					GRID_CACHE_SAVE_GRIDS_EFFEX;
					//GRID_CACHE_SAVE_GRIDS_FIELD3D;
					GRID_CACHE_SAVE_GRIDS_OPENVDB;
					GRID_CACHE_SAVE_GRIDS_OPENVDBFX;
				}
			}			
			BUTTON GRID_CACHE_DELETE {FIT_H;}
			LONG GRID_CACHE_PADDING 
			{
				CYCLE
				{
					GRID_CACHE_PADDING_OFF;
					GRID_CACHE_PADDING_3;
					GRID_CACHE_PADDING_4;
					GRID_CACHE_PADDING_5;
					GRID_CACHE_PADDING_6;
				}
			}

			STRING GRID_CACHE_SEQUENCEINFO { CUSTOMGUI MULTISTRING; READONLY; }
			
		}
		
		SEPARATOR {}
				
		GROUP GRID_CACHE_LOAD
		{
			DEFAULT 1; SCALE_V;
			BOOL GRID_CACHE_LOAD_KEEPCACHED {}
			BOOL GRID_CACHE_LOAD_FRAME_REVERSE {}
			LONG GRID_CACHE_LOAD_FRAME {MIN -1; }
			LONG GRID_CACHE_LOAD_OFFSET { }
			REAL GRID_CACHE_LOAD_SCALE { MIN 0.001; STEP 0.1;}
			LONG GRID_CACHE_LOAD_RESAMPLE_IPOL
			{
				ANIM OFF;
				CYCLE
				{
					GRID_CACHE_LOAD_RESAMPLE_IPOL_LINEAR;
					GRID_CACHE_LOAD_RESAMPLE_IPOL_CUBIC;
					GRID_CACHE_LOAD_RESAMPLE_IPOL_HERMITE;
				}
			}
			LONG GRID_CACHE_LOAD_RESAMPLE_IPOLVDB
			{
				ANIM OFF;
				CYCLE
				{
					GRID_CACHE_LOAD_RESAMPLE_IPOLVDB_NEAREST;
					GRID_CACHE_LOAD_RESAMPLE_IPOLVDB_LINEAR;
					GRID_CACHE_LOAD_RESAMPLE_IPOLVDB_QUADRATIC;
				}
			}						
			SEPARATOR{LINE;}
			
			STRING GRID_CACHEFILE_INFO { CUSTOMGUI MULTISTRING; SCALE_V;}
		}
		GROUP GRID_CACHE_SAVE
		{
			DEFAULT 1;
			BOOL GRID_CACHE_SAVE_COMPRESS {ANIM OFF; }
			LONG GRID_CACHE_SAVE_FRAME 
			{
				ANIM OFF;
				CYCLE
				{
					GRID_CACHE_SAVE_FRAME_SIM;
					GRID_CACHE_SAVE_FRAME_C4D;
				}
			}
			REAL GRID_CACHE_SAVE_THRESHOLD { STEP 0.01; } //OPENVDB ONLY
		}
	}
}