CONTAINER fx_c4d_effector_sampler
{
	NAME	fx_c4d_effector_sampler;
	INCLUDE Obaseeffector;

	GROUP	ID_MG_BASEEFFECTOR_GROUPEFFECTOR
	{
		GROUP
		{
			COLUMNS 2;
			LINK FX_EFFS_CHANNEL { ACCEPT{fx_channel_base; }}
			BUTTON FX_EFFS_CHANNEL_SELECTOR {}
		}
		
		SEPARATOR {LINE;}

		LONG FX_EFFS_WEIGHT_TARGET
		{
			CYCLE
			{
				FX_EFFS_WEIGHT_TARGET_ALL;
				FX_EFFS_WEIGHT_TARGET_POS;
				FX_EFFS_WEIGHT_TARGET_ROT;
				FX_EFFS_WEIGHT_TARGET_SCALE;
				FX_EFFS_WEIGHT_TARGET_COLOROPACITY;
				FX_EFFS_WEIGHT_TARGET_VISIBILITY;
				FX_EFFS_WEIGHT_TARGET_WEIGHT;				
				FX_EFFS_WEIGHT_TARGET_INDEX;
				FX_EFFS_WEIGHT_TARGET_TIME;
			}
		}
		LONG FX_EFFS_VECMODE
		{
			CYCLE
			{
				FX_EFFS_VECMODE_LENGTH;
				FX_EFFS_VECMODE_SUM;
				FX_EFFS_VECMODE_AVERAGE;
				FX_EFFS_VECMODE_X;
				FX_EFFS_VECMODE_Y;
				FX_EFFS_VECMODE_Z;
			}
		}
		REAL FX_EFFS_VMAXLEN { MIN 0.001; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL FX_EFFS_SCALE { UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
	}
}
