CONTAINER fx_constraint_collision
{
	NAME fx_constraint_collision;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK CONSTRAINT_COLLISION_PARTICLES { ACCEPT { fx_particlegroup; fx_group;}; }
			BUTTON CONSTRAINT_COLLISION_PARTICLES_SELECTOR {}
		}

		GROUP CONSTRAINT_PARAMS_SID
		{			
			LONG PARTICLE_COLLISION_FACTORY
			{
				CYCLE
				{
					PARTICLE_COLLISION_FACTORY_PASSIVE;
					PARTICLE_COLLISION_FACTORY_VORTICITY;
					PARTICLE_COLLISION_FACTORY_LIQUID;
					PARTICLE_COLLISION_FACTORY_DIFFUSE;
				}
			}
			REAL CONSTRAINT_COLLISION_MAXDISTANCE { MIN 0.0; STEP 0.001; }
		}
	}
}