#ifndef FX_CONSTRAINT_VOLUME_H
#define FX_CONSTRAINT_VOLUME_H

enum
{
	CONSTRAINT_VOLUME = 1000,
	CONSTRAINT_VOLUME_USEFALLOFF,
	CONSTRAINT_VOLUME_SPLINE,
	CONSTRAINT_VOLUME_SELECTOR,
	CONSTRAINT_VOLUME_OFFSET,

	CONSTRAINT_VOLUME_DUMMY_
};

#endif