CONTAINER fx_channelop_remap
{
	NAME fx_channelop_remap;
	INCLUDE fx_constraint;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK CHANNELOP_REMAP_CHANNEL { ACCEPT {Obase;} }
			BUTTON CHANNELOP_REMAP_CHANNEL_SELECTOR { }
		}
		GROUP CONSTRAINT_PARAMS_SID
		{	
			BOOL CHANNELOP_REMAP_ISVECTOR {}
			GRADIENT CHANNELOP_REMAP_GRADIENT {COLOR; ANIM ON;}
		}
	}
}
			