CONTAINER fx_constraint_noise
{
	NAME fx_constraint_noise;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{		
		GROUP ID_PORT_BASE
		{
			BITMAPBUTTON CONSTRAINT_NOISE_PREVIEW {BORDER; SCALE_H;}
		}
		
		GROUP CONSTRAINT_PARAMS_SID
		{			
			LONG CONSTRAINT_NOISE_SEED { MIN 0; }
			LONG CONSTRAINT_NOISE_TYPE { CYCLE{} }
			REAL CONSTRAINT_NOISE_SCALE {MIN 0.0; UNIT PERCENT;}
			VECTOR CONSTRAINT_NOISE_SCALE3D {MIN 0 0 0; UNIT PERCENT;}
			REAL CONSTRAINT_NOISE_OCTAVES {MIN 0.0; MAX 50; }
			REAL CONSTRAINT_NOISE_ANIMATION {MIN 0.0; UNIT PERCENT;}
			LONG CONSTRAINT_NOISE_LOOP { MIN 0; }
			REAL CONSTRAINT_NOISE_DETAILATT {MIN 0.0; UNIT PERCENT;}
			REAL CONSTRAINT_NOISE_SAMPLINGDELTA {UNIT PERCENT;}

			SEPARATOR {LINE;}

			BOOL CONSTRAINT_NOISE_ABSOLUTE {}
			REAL CONSTRAINT_NOISE_LOWCLIP {MIN 0.0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL CONSTRAINT_NOISE_HIGHCLIP {MIN 0.0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL CONSTRAINT_NOISE_BRIGHTNESS {MIN -100.0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL CONSTRAINT_NOISE_CONTRAST {MIN 0.0; MAX 1000; UNIT PERCENT; CUSTOMGUI REALSLIDER;}	
		}
	}
}