CONTAINER fx_constraint_particle_property
{
	NAME fx_constraint_particle_property;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{		
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK CONSTRAINT_PARTICLE_PROPERTY { ACCEPT { fx_property_scalar; fx_property_vector; fx_property_state; fx_group;}; }
			BUTTON CONSTRAINT_PARTICLE_PROPERTY_SELECTOR {}
		}

		GROUP CONSTRAINT_PARAMS_SID
		{			
			REAL	CONSTRAINT_PARTICLE_PROPERTY_SCALARMIN { HIDDEN; STEP 0.1;}
			REAL	CONSTRAINT_PARTICLE_PROPERTY_SCALARMAX { HIDDEN; STEP 0.1;}
			VECTOR	CONSTRAINT_PARTICLE_PROPERTY_VECTOR {HIDDEN;}
			BOOL	CONSTRAINT_PARTICLE_PROPERTY_STATE {HIDDEN;}
		}
	}
}