CONTAINER fx_constraint_random
{
	NAME fx_constraint_random;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{				
		GROUP CONSTRAINT_PARAMS_SID
		{			
			LONG CONSTRAINT_RND_SEED { MIN 0; }
			BOOL CONSTRAINT_RND_CONSTANTINIT {}
			LONG CONSTRAINT_RND_TYPE 
			{ 
				CYCLE
				{
					CONSTRAINT_RND_TYPE_UNIFORM;
					CONSTRAINT_RND_TYPE_EXPONENTIAL;
					CONSTRAINT_RND_TYPE_GAMMA;
					CONSTRAINT_RND_TYPE_WEIBULL;
					CONSTRAINT_RND_TYPE_EXTREMEVALUE;
					CONSTRAINT_RND_TYPE_NORMAL;
					CONSTRAINT_RND_TYPE_LOGNORMAL;
					CONSTRAINT_RND_TYPE_CAUCHY;
				}
			}
			
			SEPARATOR { LINE; }

			BOOL CONSTRAINT_RND_BINARY {}
			REAL CONSTRAINT_RND_BINARYTHRESHOLD {MIN 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		}
	}
}