#ifndef FX_EFFECTOR_MULTI_H
#define FX_EFFECTOR_MULTI_H

enum
{
	ID_MULTIVOLUME_EFFECTOR = 2000,

	MULTIVOLUME_EFFECTOR_STRENGTH = 1000, //Effector Value
	MULTIVOLUME_EFFECTOR_VOLUME = 1100,

	MULTIVOLUME_EFFECTOR_END
};

#endif