#ifndef FX_CONSTRAINT_QUADRATIC_H
#define FX_CONSTRAINT_QUADRATIC_H

enum
{
	CONSTRAINT_QUADRATIC = 1000,
		CONSTRAINT_QUADRATIC_SPHERE = 0,
		CONSTRAINT_QUADRATIC_ELLIPSOID,
		CONSTRAINT_QUADRATIC_BOX,
		CONSTRAINT_QUADRATIC_TORUS,
		CONSTRAINT_QUADRATIC_CYLINDER,
	CONSTRAINT_QUADRATIC_RADIUS = 1001,
	CONSTRAINT_QUADRATIC_RADIUS_SPHERE,

	CONSTRAINT_QUADRATIC_DUMMY_
};

#endif