CONTAINER fx_c4d_couple
{
	NAME fx_c4d_couple;	
	INCLUDE Texpression;

	//Basic Tab
	GROUP ID_TAGPROPERTIES
	{		
		BUTTON COUPLE_SETMATRIX {}
		
		LINK COUPLE_DYNAMICS {ACCEPT{fx_fluid; fx_liquid; fx_channel_vector; }}
		REAL COUPLE_DRAG {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL COUPLE_BLEND {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL COUPLE_ROTATION { MIN 0; MAXSLIDER 100; MAX 1000; UNIT PERCENT; CUSTOMGUI REALSLIDER;	}
		LONG COUPLE_INTEGRATOR
		{
			CYCLE
			{
				COUPLE_INTEGRATOR_EULER1ST;
				COUPLE_INTEGRATOR_RUNGA2ND;
				COUPLE_INTEGRATOR_RUNGA3RD;
				COUPLE_INTEGRATOR_RUNGA4TH;
			}
		}

		SEPARATOR {LINE;}

		REAL COUPLE_BUOYANCY { STEP 0.01; }
	}
}