#ifndef FX_CHANNELVALUE_H
#define FX_CHANNELVALUE_H

enum
{	
	CHANNELVALUE_CHANNEL = 1000,
	CHANNELVALUE_SCALAR,
	CHANNELVALUE_VECTOR,
	CHANNELVALUE_VAR,
	CHANNELVALUE_PROPERTY,
	CHANNELVALUE_CHANNEL_SELECTOR,
	CHANNELVALUE_PROPERTY_SELECTOR,
	CHANNELVALUE_STATE,
	CHANNELVALUE_CHANNEL_SOLVER = 1008,
		CHANNELVALUE_CHANNEL_SOLVER_DIVERGENCE = 0,
		CHANNELVALUE_CHANNEL_SOLVER_SURFACE,
		CHANNELVALUE_CHANNEL_SOLVER_VELOCITY,
	CHANNELVALUE_VALUEMULTIPLIER = 1009,

	CHANNELVALUE_DUMMY_

};

#endif