CONTAINER fx_cache_particle
{
	NAME fx_cache_particle;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	HIDE FX_BASE_PIPELINESTAGE;
	
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			IN_EXCLUDE PARTICLE_CACHE_CHANNELS
			{
				SEND_SELCHNGMSG 1;
				NUM_FLAGS 4; 
				INIT_STATE 2;
				IMAGE_01_ON 1024284;
				IMAGE_01_OFF 1024283;
				IMAGE_02_ON 1024285;
				IMAGE_02_OFF 1024283;
				IMAGE_03_ON 1024286;
				IMAGE_03_OFF 1024283;
				IMAGE_04_ON 1024287;
				IMAGE_04_OFF 1024283;
				ACCEPT { fx_particlegroup; 1001381; Obase; Oparticle;};
			}
			BUTTON PARTICLE_CACHE_CHANNELS_SELECTOR {}
			LINK PARTICLE_CACHE_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON PARTICLE_CACHE_DURATION_SELECTOR {}
		}
		
		SEPARATOR{LINE;}
		
		BOOL PARTICLE_CACHE_RENDERONLY {}
		LONG PARTICLE_CACHE_MODE 
		{
			ANIM OFF;
			CYCLE
			{
				PARTICLE_CACHE_MODE_LOAD;
				PARTICLE_CACHE_MODE_SAVE;
				PARTICLE_CACHE_MODE_LOADSAVE;
			}
		}
		LONG PARTICLE_CACHE_PATHMODE 
		{
			ANIM OFF;
			CYCLE
			{
				PARTICLE_CACHE_PATHMODE_SCENEPATH;
				PARTICLE_CACHE_PATHMODE_CUSTOM;
			}
		}
		SEPARATOR{LINE;}
		
		GROUP
		{
			COLUMNS 2;
			STRING PARTICLE_CACHE_FILEPATH {ANIM OFF; SCALE_H;}
			BUTTON PARTICLE_CACHE_FILESELECT {FIT_H;}

			STRING PARTICLE_CACHE_FILENAME {ANIM OFF;SCALE_H;}
			LONG PARTICLE_CACHE_SAVE_PARTICLES
			{
				ANIM OFF;SCALE_H;
				CYCLE
				{
					//PARTICLE_CACHE_SAVE_PARTICLES_EFFEX;
					PARTICLE_CACHE_SAVE_PARTICLES_EFFEXNEW;
					PARTICLE_CACHE_SAVE_PARTICLES_PRT;
					//PARTICLE_CACHE_SAVE_PARTICLES_BGEOJSON;
					PARTICLE_CACHE_SAVE_PARTICLES_BGEO;
					PARTICLE_CACHE_SAVE_PARTICLES_BHCLASSIC;
					PARTICLE_CACHE_SAVE_PARTICLES_GEO;					
					PARTICLE_CACHE_SAVE_PARTICLES_HCLASSIC;
					PARTICLE_CACHE_SAVE_PARTICLES_ITBL;
					PARTICLE_CACHE_SAVE_PARTICLES_ATBL;
					PARTICLE_CACHE_SAVE_PARTICLES_BIN;
					PARTICLE_CACHE_SAVE_PARTICLES_PDA;
					PARTICLE_CACHE_SAVE_PARTICLES_PDB;
					PARTICLE_CACHE_SAVE_PARTICLES_PDB32;
					PARTICLE_CACHE_SAVE_PARTICLES_PDB64;
					PARTICLE_CACHE_SAVE_PARTICLES_PDC;
					PARTICLE_CACHE_SAVE_PARTICLES_PTC;
					PARTICLE_CACHE_SAVE_PARTICLES_PTS;
					PARTICLE_CACHE_SAVE_PARTICLES_RIB;
					PARTICLE_CACHE_SAVE_PARTICLES_XYZ;
					PARTICLE_CACHE_SAVE_PARTICLES_MC;
					PARTICLE_CACHE_SAVE_PARTICLES_ICE;
				}
			}
			BUTTON PARTICLE_CACHE_DELETE {FIT_H;}
			LONG PARTICLE_CACHE_PADDING 
			{
				CYCLE
				{
					PARTICLE_CACHE_PADDING_OFF;
					PARTICLE_CACHE_PADDING_3;
					PARTICLE_CACHE_PADDING_4;
					PARTICLE_CACHE_PADDING_5;
					PARTICLE_CACHE_PADDING_6;
				}
			}
			STRING PARTICLE_CACHEFILE_INFO { CUSTOMGUI MULTISTRING; READONLY; }
			
		}
		SEPARATOR {}
				
		GROUP PARTICLE_CACHE_LOAD
		{
			DEFAULT 1;
			REAL PARTICLE_CACHE_LOAD_TIMING { MIN 0; MAX 1000; MAXSLIDER 200; CUSTOMGUI REALSLIDER; UNIT PERCENT; }
			BOOL PARTICLE_CACHE_LOAD_FRAME_REVERSE {}
			LONG PARTICLE_CACHE_LOAD_FRAME {MIN -1; }
			LONG PARTICLE_CACHE_LOAD_OFFSET { }	
			STRING PARTICLE_CACHE_LOAD_INFO { CUSTOMGUI MULTISTRING; READONLY; }		
		}
		GROUP PARTICLE_CACHE_SAVE
		{
			DEFAULT 1;
			BOOL PARTICLE_CACHE_SAVE_COMPRESS {ANIM OFF; }			
			LONG PARTICLE_CACHE_SAVE_FRAME 
			{
				ANIM OFF;
				CYCLE
				{
					PARTICLE_CACHE_SAVE_FRAME_SIM;
					PARTICLE_CACHE_SAVE_FRAME_C4D;
				}
			}
			IN_EXCLUDE PARTICLE_CACHE_SAVE_PROPERTIES
			{
				SEND_SELCHNGMSG 1;
				ACCEPT { fx_property_scalar; fx_property_vector; };
			}
		}
	}
}