#ifndef FX_CONSTRAINT_GRIDAVERAGE_H
#define FX_CONSTRAINT_GRIDAVERAGE_H

enum
{	
	CONSTRAINT_GRIDAVERAGE_CHANNEL = 1000,
	CONSTRAINT_GRIDAVERAGE_THRESHOLD,
	CONSTRAINT_GRIDAVERAGE_CHANNEL_SELECTOR,

	CONSTRAINT_GRIDAVERAGE_DUMMY_
};

#endif