#ifndef FX_CHANNEL_BASE_H
#define FX_CHANNEL_BASE_H

enum
{
	GRIDCHANNEL_SPECIFICS = 2000,
	ID_CHANNEL_DISPLAY,

	GRIDCHANNEL_DATATYPE = 1000,
		GRIDCHANNEL_DATATYPE_SCALAR = 0,
		GRIDCHANNEL_DATATYPE_VECTOR,
		GRIDCHANNEL_DATATYPE_COLOR,	
	GRIDCHANNEL_CLEAR = 1001,
	GRIDCHANNEL_CONVECT,
	GRIDCHANNEL_ADAPTIVE,
	GRIDCHANNEL_INTEGRATOR = 1004,
		GRIDCHANNEL_INTEGRATOR_EULER1ST = 0,
		GRIDCHANNEL_INTEGRATOR_RUNGA2ND,
		GRIDCHANNEL_INTEGRATOR_RUNGA3RD,
		GRIDCHANNEL_INTEGRATOR_RUNGA4TH,
	GRIDCHANNEL_INTERPOLATOR = 1005,
		GRIDCHANNEL_INTERPOLATOR_LINEAR = 0,
		GRIDCHANNEL_INTERPOLATOR_COSINE,
		GRIDCHANNEL_INTERPOLATOR_HERMITE,
	GRIDCHANNEL_DIFFUSION = 1006,
	GRIDCHANNEL_CACHE,
	GRIDCHANNEL_DRAWBOUNDS,
	GRIDCHANNEL_CELLOPERATORS,
	GRIDCHANNEL_DIFFUSION_SELECTOR,
	GRIDCHANNEL_CELLOPERATORS_MOEFFECTORS,

	GRIDCHANNEL_DISPLAY_PLANE = 1012,
		GRIDCHANNEL_DISPLAY_PLANE_OFF = 0,
		GRIDCHANNEL_DISPLAY_PLANE_X,
		GRIDCHANNEL_DISPLAY_PLANE_Y,
		GRIDCHANNEL_DISPLAY_PLANE_Z,
	GRIDCHANNEL_DISPLAY_MIX = 1013,
	GRIDCHANNEL_DISPLAY_CUTOFF,
	GRIDCHANNEL_DISPLAY_MAX,
	GRIDCHANNEL_DISPLAY_COLOR,
	GRIDCHANNEL_DISPLAY_AUTOTRANSPARENCY,
	GRIDCHANNEL_DISPLAY_TYPE = 1018,
		GRIDCHANNEL_DISPLAY_TYPE_MEDIUM = 0,
		GRIDCHANNEL_DISPLAY_TYPE_DOTSLICE,
	GRIDCHANNEL_DISPLAY_MEDIUM_ALBEDO = 1019,
	GRIDCHANNEL_DISPLAY_MEDIUM_ABSORPTION,
	GRIDCHANNEL_CONTRIBUTE,
	GRIDCHANNEL_DISPLAY_MEDIUM_HIGHSUB,
	GRIDCHANNEL_DISPLAY_MEDIUM_LOWSUB,
	GRIDCHANNEL_CREATEADVECTION,

	GRIDCHANNEL_DUMMY_
};

#endif