#ifndef FX_C4D_TRACER_H
#define FX_C4D_TRACER_H

enum
{
    FXC4D_TRACER_PARTICLES = 1000,
	FXC4D_TRACER_PARTICLES_SELECTOR,
	FXC4D_TRACER_MINMOVEMENT,
	FXC4D_TRACER_DURATION,
	FXC4D_TRACER_DURATION_SELECTOR,
	FXC4D_TRACER_FACTORY = 1005,
		FXC4D_TRACER_FACTORY_PASSIVE = 0,
		FXC4D_TRACER_FACTORY_VORTICITY,
		FXC4D_TRACER_FACTORY_IMPLICIT,
		FXC4D_TRACER_FACTORY_DIFFUSE,
	FXC4D_TRACER_SPLINEOBJECT_TYPE = 1006,
		FXC4D_TRACER_SPLINEOBJECT_TYPE_LINEAR			= 0,
		FXC4D_TRACER_SPLINEOBJECT_TYPE_CUBIC				= 1,
		FXC4D_TRACER_SPLINEOBJECT_TYPE_AKIMA				= 2,
		FXC4D_TRACER_SPLINEOBJECT_TYPE_BSPLINE		= 3,
		FXC4D_TRACER_SPLINEOBJECT_TYPE_BEZIER			= 4,
	FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION	= 1007,
		FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_NONE       = 0,
		FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_NATURAL  = 1,
		FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_UNIFORM  = 2,
		FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_ADAPTIVE = 3,
		FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_SUBDIV   = 4,
	FXC4D_TRACER_SPLINEOBJECT_CLOSED	= 1008,
	FXC4D_TRACER_SPLINEOBJECT_SUB,
	FXC4D_TRACER_SPLINEOBJECT_ANGLE,
	FXC4D_TRACER_SPLINEOBJECT_MAXIMUMLENGTH,
	FXC4D_TRACER_MAXAGE_VAR,
	FXC4D_TRACER_MAXAGE,
	FXC4D_TRACER_MAXMOVEMENT,
	FXC4D_TRACER_DEATHRATE,
	FXC4D_TRACER_DEATHRATE_VAR,
	FXC4D_TRACER_DEATHMODE = 1017,
		FXC4D_TRACER_DEATHMODE_FRAMEVERTEX = 0,
		FXC4D_TRACER_DEATHMODE_LENGTH,
		FXC4D_TRACER_DEATHMODE_PERCENT,
	FXC4D_TRACER_DEATHONCE = 1018,
	FXC4D_TRACER_DEATHRATEPERCENT,

	FXC4D_TRACER_DUMMY_
		
};

#endif