#ifndef fx_c4d_couple_H_
#define fx_c4d_couple_H_

enum
{
	COUPLE_SETMATRIX = 2000,
	COUPLE_DYNAMICS,
	COUPLE_ROTATION,
	COUPLE_INTEGRATOR = 2003,
		COUPLE_INTEGRATOR_EULER1ST = 0,
		COUPLE_INTEGRATOR_RUNGA2ND,
		COUPLE_INTEGRATOR_RUNGA3RD,
		COUPLE_INTEGRATOR_RUNGA4TH,
	COUPLE_DRAG = 2004,
	COUPLE_BUOYANCY,
	COUPLE_BLEND,

	COUPLE_DUMMY_

};

#endif