CONTAINER fx_constraint_c4dtexchannel
{
	NAME fx_constraint_c4dtexchannel;
	
	GROUP ID_OBJECTPROPERTIES
	{
		DEFAULT 1;
		INCLUDE fx_constraint;

		LINK CONSTRAINT_C4DTEXCHANNEL_TEXTAG {ACCEPT{Ttexture;}}
		LONG CONSTRAINT_C4DTEXCHANNEL_CHANNEL
		{
			CYCLE
			{
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_NONE;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_COLOR;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_LUMINANCE;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_TRANSPARENCY;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_REFLECTION;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_ENVIRONMENT;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_FOG;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_BUMP;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_ALPHA;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_DISPLACEMENT;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_DIFFUSION;
				CONSTRAINT_C4DTEXCHANNEL_CHANNEL_NORMAL;
			}
		}
	}
}