CONTAINER fx_constraint_particlecount
{
	NAME fx_constraint_particlecount;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;			
			LINK CONSTRAINT_PARTICLECOUNT_PARTICLES	
			{ 
				//NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
				ACCEPT {  Obase; }; 
			}
			BUTTON CONSTRAINT_PARTICLECOUNT_PARTICLES_SELECTOR {}
		}
						
		LONG CONSTRAINT_PARTICLECOUNT_FACTORY
		{
			CYCLE
			{
				CONSTRAINT_PARTICLECOUNT_FACTORY_PASSIVE;
				CONSTRAINT_PARTICLECOUNT_FACTORY_VORTICITY;
				CONSTRAINT_PARTICLECOUNT_FACTORY_LIQUID;
				CONSTRAINT_PARTICLECOUNT_FACTORY_DIFFUSE;
			}
		}
		GROUP CONSTRAINT_PARAMS_SID
		{	
			REAL CONSTRAINT_PARTICLECOUNT_RADIUS {MIN 0.001; STEP 0.1;}
			LONG CONSTRAINT_PARTICLECOUNT_MINCNT {MIN 0;}
			LONG CONSTRAINT_PARTICLECOUNT_MAXCNT {MIN 1;}

			BOOL CONSTRAINT_PARTICLECOUNT_RANGED { }
			LONG CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX 
			{
				CYCLE
				{
					CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX_UNBOUND;
					CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX_CLAMPMAX;
					CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX_CLAMPMIN;
				}
			}
		}
	}
}