#ifndef FX_CONSTRAINT_ROTATION_H
#define FX_CONSTRAINT_ROTATION_H

enum
{
	CONSTRAINT_ROTATION_CHANNEL = 1000,
	CONSTRAINT_ROTATION_CHANNEL_SELECTOR,
	CONSTRAINT_ROTATION_MODE = 1002,
		CONSTRAINT_ROTATION_MODE_CURL = 0,
		CONSTRAINT_ROTATION_MODE_HELICITY,
	CONSTRAINT_ROTATION_ABSOLUTE = 1003,

	CONSTRAINT_ROTATION_DUMMY_
};

#endif