#ifndef FX_CONSTRAINT_PARTICLECOUNT_H
#define FX_CONSTRAINT_PARTICLECOUNT_H

enum
{
	CONSTRAINT_PARTICLECOUNT_PARTICLES = 1000,
	CONSTRAINT_PARTICLECOUNT_RADIUS,
	CONSTRAINT_PARTICLECOUNT_PARTICLES_SELECTOR,
	CONSTRAINT_PARTICLECOUNT_FACTORY = 1003,
		CONSTRAINT_PARTICLECOUNT_FACTORY_PASSIVE = 0,
		CONSTRAINT_PARTICLECOUNT_FACTORY_VORTICITY,
		CONSTRAINT_PARTICLECOUNT_FACTORY_LIQUID,
		CONSTRAINT_PARTICLECOUNT_FACTORY_DIFFUSE,
	CONSTRAINT_PARTICLECOUNT_MAXCNT = 1004,
	CONSTRAINT_PARTICLECOUNT_MINCNT,
	CONSTRAINT_PARTICLECOUNT_RANGED,
	CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX = 1007,
		CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX_UNBOUND = 0,
		CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX_CLAMPMAX,
		CONSTRAINT_PARTICLECOUNT_BOUNDEDMAX_CLAMPMIN,

	CONSTRAINT_PARTICLECOUNT_DUMMY_
};

#endif