#ifndef FX_CHANNELSETTINGS_H
#define FX_CHANNELSETTINGS_H

enum
{	
	CHANNELSETTINGS_CHANNEL = 1000,
	CHANNELSETTINGS_SETTINGS,
	CHANNELSETTINGS_CHANNEL_SELECTOR,
	CHANNELSETTINGS_SETTINGS_SELECTOR,

	CHANNELSETTINGS_DUMMY_

};

#endif