#ifndef FX_CHANNELOP_REMAP_H
#define FX_CHANNELOP_REMAP_H

enum
{	
	CHANNELOP_REMAP_GRADIENT = 1000,
	CHANNELOP_REMAP_CHANNEL,
	CHANNELOP_REMAP_CHANNEL_SELECTOR,
	CHANNELOP_REMAP_ISVECTOR,

	CHANNELOP_REMAP_DUMMY_

};

#endif