#ifndef FX_CACHE_MESH_H
#define FX_CACHE_MESH_H

enum
{
	MESH_CACHE_LOAD = 2000,
	MESH_CACHE_SAVE,

	MESH_CACHE_RENDERONLY = 1000,
	MESH_CACHE_MODE = 1001,
		MESH_CACHE_MODE_LOAD = 0,
		MESH_CACHE_MODE_SAVE,
		MESH_CACHE_MODE_LOADSAVE,
	MESH_CACHE_FILESELECT = 1002,
	MESH_CACHE_FILEPATH,
	MESH_CACHE_FILENAME,
	
	MESH_CACHE_LOAD_FRAME_INITIALISE,
	MESH_CACHE_LOAD_FRAME,
	MESH_CACHE_LOAD_OFFSET,
	MESH_CACHEFILE_INFO,

	MESH_CACHE_SAVE_COMPRESS,
	MESH_CACHE_SAVE_FORMAT = 1010,
		MESH_CACHE_SAVE_FORMAT_EFFEX = 0,
		MESH_CACHE_SAVE_FORMAT_C4D,
	MESH_CACHE_SAVE_FRAME = 1011,
		MESH_CACHE_SAVE_FRAME_SIM = 0,
		MESH_CACHE_SAVE_FRAME_C4D,
	MESH_CACHE_MESHERS = 1012,
	MESH_CACHE_PATHMODE = 1013,
		MESH_CACHE_PATHMODE_SCENEPATH = 0,
		MESH_CACHE_PATHMODE_CUSTOM,
	MESH_CACHE_LOAD_FRAME_REVERSE = 1014,
	MESH_CACHE_SEQUENCEINFO,
	MESH_CACHE_DELETE,
	MESH_CACHE_MESHERS_SELECTOR,
	MESH_CACHE_DURATION,
	MESH_CACHE_DURATION_SELECTOR,
	MESH_CACHE_PADDING = 1020,
		MESH_CACHE_PADDING_OFF = -1,
		MESH_CACHE_PADDING_3 = 3,
		MESH_CACHE_PADDING_4,
		MESH_CACHE_PADDING_5,
		MESH_CACHE_PADDING_6,

	MESH_CACHE_DUMMY_
};

#endif