CONTAINER fx_constraint_gradient
{
	NAME fx_constraint_gradient;
	INCLUDE fx_constraint;
	
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;

		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK CONSTRAINT_GRADIENT_ALIGNMENT { ACCEPT{fx_alignment; fx_group;} }
			BUTTON CONSTRAINT_GRADIENT_ALIGNMENT_SELECTOR {}

			LINK CONSTRAINT_GRADIENT_ORIGIN {ACCEPT{Obase;}}
		}

		GROUP CONSTRAINT_PARAMS_SID
		{			
			LONG CONSTRAINT_GRADIENT_AXIS
			{
				CYCLE
				{
					CONSTRAINT_GRADIENT_AXIS_X;
					CONSTRAINT_GRADIENT_AXIS_Y;
					CONSTRAINT_GRADIENT_AXIS_Z;
					CONSTRAINT_GRADIENT_AXIS_SPHERE;
				}
			}
			BOOL CONSTRAINT_GRADIENT_CLAMPAXIS {}
			BOOL CONSTRAINT_GRADIENT_SQUARED {}
			REAL CONSTRAINT_GRADIENT_DISTANCE {MIN 0.001; UNIT METER; }
			GRADIENT CONSTRAINT_GRADIENT {ALPHA; ANIM ON;}
		}
	}
}