CONTAINER fx_c4d_tracer
{
	NAME fx_c4d_tracer;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FXC4D_TRACER_PARTICLES { ACCEPT { fx_particlegroup;1001381; 1027133; Obase; Oparticle; fx_group;} }
			BUTTON FXC4D_TRACER_PARTICLES_SELECTOR {SCALE_V; FIT_H;}
			LINK FXC4D_TRACER_DURATION { ACCEPT { fx_duration; fx_group; }}
			BUTTON FXC4D_TRACER_DURATION_SELECTOR {}
		}
		
		LONG FXC4D_TRACER_FACTORY
		{
			CYCLE
			{
				FXC4D_TRACER_FACTORY_PASSIVE;
				FXC4D_TRACER_FACTORY_VORTICITY;
				FXC4D_TRACER_FACTORY_IMPLICIT;
				FXC4D_TRACER_FACTORY_DIFFUSE;
			}
		}
		GROUP
		{
			COLUMNS 2;
			REAL FXC4D_TRACER_MINMOVEMENT { MIN 0.001; UNIT METER; STEP 0.01; }
			REAL FXC4D_TRACER_MAXMOVEMENT { MIN 0.001; UNIT METER; STEP 0.01; }

			SEPARATOR { LINE; }			
			STATICTEXT { JOINENDSCALE;}

			LONG FXC4D_TRACER_MAXAGE { MIN 2; }
			REAL FXC4D_TRACER_MAXAGE_VAR { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}

			LONG FXC4D_TRACER_DEATHMODE
			{
				CYCLE
				{
					FXC4D_TRACER_DEATHMODE_FRAMEVERTEX;
					FXC4D_TRACER_DEATHMODE_LENGTH;
					FXC4D_TRACER_DEATHMODE_PERCENT;
				}
			}	
			BOOL FXC4D_TRACER_DEATHONCE {}

			REAL FXC4D_TRACER_DEATHRATE { MIN 0.001; STEP 0.1; UNIT METER;}
			REAL FXC4D_TRACER_DEATHRATEPERCENT { MIN 0.01; MAX 100; UNIT PERCENT;}
			REAL FXC4D_TRACER_DEATHRATE_VAR { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}
		}
		SEPARATOR { LINE; }

		LONG FXC4D_TRACER_SPLINEOBJECT_TYPE
		{
			CYCLE
			{
				FXC4D_TRACER_SPLINEOBJECT_TYPE_LINEAR;
				FXC4D_TRACER_SPLINEOBJECT_TYPE_CUBIC;
				FXC4D_TRACER_SPLINEOBJECT_TYPE_AKIMA;
				FXC4D_TRACER_SPLINEOBJECT_TYPE_BSPLINE;
				FXC4D_TRACER_SPLINEOBJECT_TYPE_BEZIER;
			}
		}

		BOOL FXC4D_TRACER_SPLINEOBJECT_CLOSED {}

		LONG FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION
		{
			CYCLE
			{
				FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_NONE;
				FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_NATURAL;
				FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_UNIFORM;
				FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_ADAPTIVE;
				FXC4D_TRACER_SPLINEOBJECT_INTERPOLATION_SUBDIV;
			}
		}

		LONG FXC4D_TRACER_SPLINEOBJECT_SUB		{ MIN 0; MAX 5000; }
		REAL FXC4D_TRACER_SPLINEOBJECT_ANGLE		{ UNIT DEGREE; MIN 0.0; MAX 90.0; }
		REAL FXC4D_TRACER_SPLINEOBJECT_MAXIMUMLENGTH	{ UNIT METER; MIN 0.01; }
	}	
}