CONTAINER fx_c4d_splinelength
{
	NAME fx_c4d_splinelength;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		DEFAULT 1;
		LONG FXC4D_SPLINELENGTH_TYPE
		{
			CYCLE
			{
				FXC4D_SPLINELENGTH_TYPE_A;
				FXC4D_SPLINELENGTH_TYPE_B;
			}
		}
		BOOL FXC4D_SPLINELENGTH_INVERT {}
		REAL FXC4D_SPLINELENGTH_LENGTH {MIN 0.0; MAX 100.0; STEP 0.1; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
	}	
}