#ifndef FX_CHANNELOP_MATH_H
#define FX_CHANNELOP_MATH_H

enum
{	
	CHANNELOP_MATH_CHANNEL = 1000,
	CHANNELOP_MATH_OPERATION = 1001,
		CHANNELOP_MATH_OPERATION_ADD = 0,
		CHANNELOP_MATH_OPERATION_SUBSTRACT,
		CHANNELOP_MATH_OPERATION_MULTIPLY,
		CHANNELOP_MATH_OPERATION_DOT,
		CHANNELOP_MATH_OPERATION_MIN,
		CHANNELOP_MATH_OPERATION_MAX,
		CHANNELOP_MATH_OPERATION_BLEND,
	CHANNELOP_MATH_VALUE_SCALAR = 1002,
	CHANNELOP_MATH_VALUE_VECTOR,
	CHANNELOP_MATH_CHANNEL_SELECTOR,
	CHANNELOP_MATH_ISVECTOR,
	CHANNELOP_MATH_COLORMODE = 1006,
		CHANNELOP_MATH_COLORMODE_OFF = 0,
		CHANNELOP_MATH_COLORMODE_COLOR,
		CHANNELOP_MATH_COLORMODE_CONSTRAINTS,
		CHANNELOP_MATH_COLORMODE_CONSTRAINTS_PARENT,
	CHANNELOP_MATH_COLOR = 1007,
	CHANNELOP_MATH_BLENDMODE,		
		CHANNELOP_MATH_BLENDMODE_NORMAL = 0,
		CHANNELOP_MATH_BLENDMODE_MULTIPLY,
		CHANNELOP_MATH_BLENDMODE_DARKEN,
		CHANNELOP_MATH_BLENDMODE_LIGHTEN,
		CHANNELOP_MATH_BLENDMODE_SCREEN,
		CHANNELOP_MATH_BLENDMODE_OVERLAY,
		CHANNELOP_MATH_BLENDMODE_HARDLIGHT,
		CHANNELOP_MATH_BLENDMODE_SOFTLIGHT,
		CHANNELOP_MATH_BLENDMODE_COLORDODGE,
		CHANNELOP_MATH_BLENDMODE_COLORDODGEINV,
		CHANNELOP_MATH_BLENDMODE_COLORBURN,
		CHANNELOP_MATH_BLENDMODE_SOFTBURN,
		CHANNELOP_MATH_BLENDMODE_DIFFERENCE,
		CHANNELOP_MATH_BLENDMODE_NDIFFERENCE,
		CHANNELOP_MATH_BLENDMODE_EXCLUDE,
		CHANNELOP_MATH_BLENDMODE_REFLECT,
		CHANNELOP_MATH_BLENDMODE_ADD,
		CHANNELOP_MATH_BLENDMODE_SUB,
	CHANNELOP_MATH_BLENDVALUE = 1009,

	CHANNELOP_MATH_DUMMY_

};

#endif