#ifndef FX_C4D_SPLINELENGTH_H
#define FX_C4D_SPLINELENGTH_H

enum
{
	FXC4D_SPLINELENGTH_LENGTH = 1000,
	FXC4D_SPLINELENGTH_TYPE = 1001,
		FXC4D_SPLINELENGTH_TYPE_A = 0,
		FXC4D_SPLINELENGTH_TYPE_B,
	FXC4D_SPLINELENGTH_INVERT = 1002
	
};

#endif