#ifndef FX_DURATION_H
#define FX_DURATION_H

enum
{
	DURATION_TIMER_LENGTH = 1000,
	DURATION_TIMER_START,
	DURATION_TIMER_LOOPS,
	DURATION_TIMER_LOOPOFFSET,
	DURATION_TIMER_SPLINE,
	DURATION_TIMER_LENGTH_FRAMES,
	DURATION_TIMER_START_FRAMES,
	DURATION_TIMER_LOOPOFFSET_FRAMES,
	DURATION_TIMER_FRAMES,
	
	DURATION_DUMMY_

};

#endif