#ifndef FX_EMISSION_SETTINGS_H
#define FX_EMISSION_SETTINGS_H

enum
{
	EMISSION_SETTINGS_RATE_MODE = 1000,
		EMISSION_SETTINGS_RATE_MODE_RATE = 0,
		EMISSION_SETTINGS_RATE_MODE_SET,
		EMISSION_SETTINGS_RATE_MODE_LIMIT,
	EMISSION_SETTINGS_PERFRAME = 1001,
	EMISSION_SETTINGS_RATE,
	EMISSION_SETTINGS_RATE_LIMIT,
	EMISSION_SETTINGS_DURATION,
	EMISSION_SETTINGS_TEMPORAL_INTENSITY,
	EMISSION_SETTINGS_FALLOFFMODE = 1006,
		EMISSION_SETTINGS_FALLOFFMODE_CONST = 0,
		EMISSION_SETTINGS_FALLOFFMODE_LINEAR,
		EMISSION_SETTINGS_FALLOFFMODE_SPLINE,
	EMISSION_SETTINGS_FPS = 1007,
	EMISSION_SETTINGS_NOISE,
	EMISSION_SETTINGS_RATE_SELECTOR,
	EMISSION_SETTINGS_RATE_LIMIT_SELECTOR,
	EMISSION_SETTINGS_DURATION_SELECTOR,
	EMISSION_SETTINGS_INTERPOLATED,
	EMISSION_SETTINGS_RATESCALAR,
	EMISSION_SETTINGS_RATEVECTOR,	
	EMISSION_SETTINGS_RATETYPE,
	
	EMISSION_SETTINGS_DUMMY_

};

#endif