CONTAINER fx_force_swirling
{
	NAME fx_force_swirling;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	INCLUDE fx_base_display_inspector;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FORCE_SWIRLING_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON FORCE_SWIRLING_DURATION_SELECTOR {}		
		}
		SEPARATOR {LINE;}

		BOOL FORCE_SWIRLING_CONSERVE {}
		BOOL FORCE_SWIRLING_ADAPTIVE {}
		REAL FORCE_SWIRLING_INTENSITY { MIN 0.0; MAX 30000.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; MAXSLIDER 100.0;}
	}
}