#ifndef FX_FORCE_GRAVITY_H
#define FX_FORCE_GRAVITY_H

enum
{	
	FORCE_GRAVITY = 1000,
	FORCE_GRAVITY_ALIGNMENT,
	FORCE_GRAVITY_INTENSITY,
	FORCE_GRAVITY_SETTINGS,
	FORCE_GRAVITY_ALIGNMENT_SELECTOR,
	FORCE_GRAVITY_SETTINGS_SELECTOR,

	FORCE_GRAVITY_DUMMY_

};

#endif