CONTAINER fx_force_gravity
{
	NAME fx_force_gravity;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	INCLUDE fx_base_display_inspector;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FORCE_GRAVITY_ALIGNMENT { ACCEPT {fx_alignment; fx_group;}; }
			BUTTON FORCE_GRAVITY_ALIGNMENT_SELECTOR {}
			LINK FORCE_GRAVITY_SETTINGS { ACCEPT {fx_emission_setting; fx_group;}}
			BUTTON FORCE_GRAVITY_SETTINGS_SELECTOR {}
		}
		SEPARATOR{LINE;}

		REAL FORCE_GRAVITY_INTENSITY { UNIT METER; MIN -100000; MAX 100000; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		VECTOR FORCE_GRAVITY {STEP 0.01; MIN -1 -1 -1; MAX 1 1 1;}
	}
}
			