CONTAINER fx_foamspraybubbles
{
	NAME fx_foamspraybubbles;
	INCLUDE fx_force_base;

	//Basic Tab
	GROUP ID_FORCE_BASE
	{			
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FSB_GROUP {ACCEPT{fx_particlegroup; fx_group;}; }			BUTTON FSB_GROUP_SELECTOR {}
			LINK FSB_GROUP_TARGET {ACCEPT{fx_particlegroup;1001381;1027133; fx_group;}; }		BUTTON FSB_GROUP_TARGET_SELECTOR {}
			LINK FSB_FOAM_TARGET {ACCEPT{fx_particlegroup;1001381;1027133; fx_group;}; }			BUTTON FSB_FOAM_TARGET_SELECTOR {}
			//LINK FSB_SPRAY_TARGET {ACCEPT{fx_particlegroup; 1001381; fx_group;}; }	BUTTON FSB_SPRAY_TARGET_SELECTOR {}
						
			LINK FSB_DYNAMICS {ACCEPT{fx_liquid; fx_group;}; }			BUTTON FSB_DYNAMICS_SELECTOR {}
			LINK FSB_MESHER {ACCEPT{fx_mesher; fx_group;}; }				BUTTON FSB_MESHER_SELECTOR {}
			LINK FSB_RECONSTRUCTOR {ACCEPT{fx_surface_reconstruction; fx_group;}; }	BUTTON FSB_RECONSTRUCTOR_SELECTOR {}
		}
		
		LONG FSB_MODE
		{
			CYCLE
			{
				FSB_MODE_GEOMETRY;
				FSB_MODE_PARTICLES;
			}
		}

		REAL FSB_VOXELSCALE {MIN 1.0; STEP 0.1;}
		REAL FSB_DENSITY { MIN 0.001; UNIT METER; STEP 0.01;}
		LONG FSB_SMOOTHING { MIN 0; MAX 10; }
		
		SEPARATOR {LINE;}

		BOOL FOAM_ON {}
		BOOL SPRAY_ON {}
		BOOL BUBBLES_ON {}		
	}
	GROUP UNIFIED_SID
	{
		REAL FSB_ENERGY_MIN { MIN 0; MAX 500; MAXSLIDER 100; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL FSB_ENERGY_MAX { MIN 0; MAX 500; MAXSLIDER 100; STEP 0.1; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR {LINE;}
		
		LONG FSB_WAVECREST_SAMPLES { MIN 0; }
		REAL FSB_WAVECREST_MIN { MIN 0; MAX 100; MAXSLIDER 20; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL FSB_WAVECREST_MAX { MIN 0; MAX 100; MAXSLIDER 20; STEP 0.1; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR {LINE;}
		
		LONG FSB_TRAPPEDAIR_SAMPLES { MIN 0; }
		REAL FSB_TRAPPEDAIR_MIN { MIN 0; MAX 100; MAXSLIDER 40; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL FSB_TRAPPEDAIR_MAX { MIN 0; MAX 100; MAXSLIDER 40; STEP 0.1; CUSTOMGUI REALSLIDER;}
	}
	GROUP FOAM_SID
	{
			
		GROUP
		{
			COLUMNS 2; 
			BOOL FOAM_OUTTOSPRAY {} STATICTEXT {}
			BOOL FOAM_CLAMPTOFLUIDSIM {} STATICTEXT {}
			REAL FOAM_OFFSET { STEP 0.001; } STATICTEXT {}
			
			SEPARATOR {LINE;} STATICTEXT {JOINEND;}
			
			REAL FOAM_CURVATURE { SCALE_H; MIN 0; MAX 300; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			STATICTEXT {}

			//Geometry
			REAL FOAM_VELOCITY { MIN 0; MAXSLIDER 100; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL FOAM_VELOCITYRND { MIN 0; MAX 100; UNIT PERCENT;}
			REAL FOAM_VORTICITY { MIN 0; MAXSLIDER 100; STEP 0.01; CUSTOMGUI REALSLIDER;}
			REAL FOAM_VORTICITYRND { MIN 0; MAX 100; UNIT PERCENT;}
			//Particles
			REAL FOAM_AGE { MIN 0.001; STEP 0.1; MAXSLIDER 5; CUSTOMGUI REALSLIDER;}
			REAL FOAM_AGERND { MIN 0; MAX 100; UNIT PERCENT;}
		}
	}
	GROUP SPRAY_SID
	{		
			
		GROUP
		{
			COLUMNS 2; 
			BOOL SPRAY_OUTTOFOAM {} STATICTEXT {}
			BOOL SPRAY_CLAMPTOFLUIDSIM {} STATICTEXT {}
			REAL SPRAY_MASS { MIN 0.001; } STATICTEXT {}
			REAL SPRAY_DRAG { } STATICTEXT {}
			
			SEPARATOR {LINE;} STATICTEXT {JOINEND;}

			REAL SPRAY_CURVATURE { SCALE_H; MIN 0; MAX 300; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }	
			STATICTEXT {}
			REAL SPRAY_VELOCITY { MIN 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
			REAL SPRAY_VELOCITYRND { MIN 0; MAX 100; UNIT PERCENT;}
			REAL SPRAY_VORTICITY { MIN 0; MAXSLIDER 50; CUSTOMGUI REALSLIDER; }
			REAL SPRAY_VORTICITYRND { MIN 0; MAX 100; UNIT PERCENT;}
			
			SEPARATOR {LINE;} STATICTEXT {JOINEND;}

			REAL SPRAY_AGE { MIN 0.001; MAXSLIDER 100; STEP 1; CUSTOMGUI REALSLIDER; }
			REAL SPRAY_AGERND { MIN 0; MAX 100; UNIT PERCENT;}
			REAL SPRAY_SPEED { MIN 0; MAXSLIDER 5; STEP 0.01; CUSTOMGUI REALSLIDER; }
			REAL SPRAY_SPEEDRND { MIN 0; MAX 100; UNIT PERCENT;}
			REAL SPRAY_SPEEDNORMAL {MIN 0; MAXSLIDER 5; CUSTOMGUI REALSLIDER; }
			REAL SPRAY_SPEEDNORMALRND { MIN 0; MAX 100; UNIT PERCENT;}
			
			SEPARATOR {LINE;} STATICTEXT {JOINEND;}

			REAL SPRAY_SPEEDANGLE {MIN -90; MAX 90; UNIT DEGREE; CUSTOMGUI REALSLIDER; }
			REAL SPRAY_SPEEDANGLERND { MIN 0; MAX 100; UNIT PERCENT;}
			BOOL SPRAY_KEEPLENGTH {}
		}
	}
	INCLUDE fx_base_constraints;
}