CONTAINER fx_force_trigowave
{
	NAME fx_force_trigowave;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	INCLUDE fx_base_display_inspector;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FORCE_TRIGOWAVE_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON FORCE_TRIGOWAVE_DURATION_SELECTOR {}
		}
		SEPARATOR {LINE;}

		REAL FORCE_TRIGOWAVE_STRENGTH { UNIT METER;}
		VECTOR FORCE_TRIGOWAVE_SCALE {MIN 0.001 0.001 0.001; STEP 0.1;}
		REAL FORCE_TRIGOWAVE_WAVESPEED {MIN 0; STEP 0.1; UNIT METER;}
		REAL FORCE_TRIGOWAVE_WAVELENGTH {MIN 0; STEP 0.1; UNIT METER;}
		LONG FORCE_TRIGOWAVE_WAVEDIRECTION
		{
			CYCLE
			{
				FORCE_TRIGOWAVE_WAVEDIRECTION_STANDARD;
				FORCE_TRIGOWAVE_WAVEDIRECTION_AXIAL;
				FORCE_TRIGOWAVE_WAVEDIRECTION_RADIAL;
				FORCE_TRIGOWAVE_WAVEDIRECTION_CIRCULAR;
				FORCE_TRIGOWAVE_WAVEDIRECTION_TWISTER;
				FORCE_TRIGOWAVE_WAVEDIRECTION_NOISE;
			}
		}
		LONG FORCE_TRIGOWAVE_WAVETYPE {MIN 0; MAX 10;}
		BOOL FORCE_TRIGOWAVE_AUTOTIME {}
		REAL FORCE_TRIGOWAVE_WAVETIME {MIN 0; }
		REAL FORCE_TRIGOWAVE_WAVEOFFSET {STEP 0.1;}
	}
}