#ifndef FX_FORCE_TRIGOWAVE_H
#define FX_FORCE_TRIGOWAVE_H

enum
{	
	FORCE_TRIGOWAVE_STRENGTH = 1000,
	FORCE_TRIGOWAVE_WAVESPEED,
	FORCE_TRIGOWAVE_WAVELENGTH,
	FORCE_TRIGOWAVE_WAVEDIRECTION = 1003,
		FORCE_TRIGOWAVE_WAVEDIRECTION_STANDARD = 0,
		FORCE_TRIGOWAVE_WAVEDIRECTION_AXIAL,
		FORCE_TRIGOWAVE_WAVEDIRECTION_RADIAL,
		FORCE_TRIGOWAVE_WAVEDIRECTION_CIRCULAR,
		FORCE_TRIGOWAVE_WAVEDIRECTION_TWISTER,
		FORCE_TRIGOWAVE_WAVEDIRECTION_NOISE,
	FORCE_TRIGOWAVE_WAVETYPE = 1004,
	FORCE_TRIGOWAVE_WAVEOFFSET,
	FORCE_TRIGOWAVE_DURATION,
	FORCE_TRIGOWAVE_DURATION_SELECTOR,
	FORCE_TRIGOWAVE_SCALE,
	FORCE_TRIGOWAVE_AUTOTIME,
	FORCE_TRIGOWAVE_WAVETIME,

	FORCE_TRIGOWAVE_DUMMY_

};

#endif