#ifndef FX_FALLOFF_VOLUME_H_
#define FX_FALLOFF_VOLUME_H_

enum
{
	//Falloff controls
	VOLUMEFALLOFF_VOLUME =	5200,
	VOLUMEFALLOFF_SCALE_SPACE,
		VOLUMEFALLOFF_SCALE_SPACE_FALLOFF = 0,
		VOLUMEFALLOFF_SCALE_SPACE_VOLUME,
		VOLUMEFALLOFF_SCALE_SPACE_VOLUMELINK,
	VOLUMEFALLOFF_UNCLAMPED = 5202

};
#endif
