#ifndef FX_FOAMSPRAYBUBBLES_H
#define FX_FOAMSPRAYBUBBLES_H

enum
{
	FOAM_SID = 2000,
	SPRAY_SID,
	UNIFIED_SID,

	FSB_GROUP = 1000,
	FSB_GROUP_SELECTOR,
	FSB_FOAM_TARGET,
	FSB_FOAM_TARGET_SELECTOR,
	FSB_SPRAY_TARGET,
	FSB_SPRAY_TARGET_SELECTOR,
	FSB_DYNAMICS,
	FSB_DYNAMICS_SELECTOR,
	FSB_MESHER,
	FSB_MESHER_SELECTOR,
	FSB_RECONSTRUCTOR,
	FSB_RECONSTRUCTOR_SELECTOR,
	FSB_GROUP_TARGET,
	FSB_GROUP_TARGET_SELECTOR,

	FSB_VOXELSCALE = 1025,
	FSB_DENSITY,
	FSB_SMOOTHING,
	FSB_MODE = 1028,
		FSB_MODE_GEOMETRY = 0,
		FSB_MODE_PARTICLES,

	FOAM_ON = 1050,
	FOAM_OUTTOSPRAY,
	FOAM_CLAMPTOFLUIDSIM,
	FOAM_CURVATURE,
	FOAM_OFFSET,
	FOAM_VELOCITY,
	FOAM_VELOCITYRND,
	FOAM_VORTICITY,
	FOAM_VORTICITYRND,
	FOAM_AGE,
	FOAM_AGERND,

	SPRAY_ON = 1100,
	SPRAY_OUTTOFOAM,
	SPRAY_CLAMPTOFLUIDSIM,
	SPRAY_MASS,
	SPRAY_DRAG,
	SPRAY_CURVATURE,
	SPRAY_VELOCITY,
	SPRAY_VELOCITYRND,
	SPRAY_VORTICITY,
	SPRAY_VORTICITYRND,
	SPRAY_AGE,
	SPRAY_AGERND,
	SPRAY_SPEED,
	SPRAY_SPEEDRND,
	SPRAY_SPEEDNORMAL,
	SPRAY_SPEEDNORMALRND,
	SPRAY_SPEEDANGLE,
	SPRAY_SPEEDANGLERND,
	BUBBLES_ON,
	SPRAY_KEEPLENGTH,

	FSB_WAVECREST_SAMPLES = 1150,
	FSB_WAVECREST_MIN,
	FSB_WAVECREST_MAX,
	FSB_TRAPPEDAIR_SAMPLES,
	FSB_TRAPPEDAIR_MIN,
	FSB_TRAPPEDAIR_MAX,
	FSB_ENERGY_MIN,
	FSB_ENERGY_MAX,

	FSB_DUMMY_
		
};

#endif