CONTAINER fx_force_particleturbulence
{
	NAME fx_force_particleturbulence;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FORCE_PARTICLEVORTICITY_PARTICLES { ACCEPT { fx_particlegroup; fx_group; } }
			BUTTON FORCE_PARTICLEVORTICITY_PARTICLES_SELECTOR {}
			LINK FORCE_PARTICLEVORTICITY_KERNELPTR { ACCEPT { fx_kernel;  fx_group;} }
			BUTTON FORCE_PARTICLEVORTICITY_KERNELPTR_SELECTOR {}
			LINK FORCE_PARTICLEVORTICITY_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON FORCE_PARTICLEVORTICITY_DURATION_SELECTOR {}	
		}

		SEPARATOR {LINE;}
		
		BOOL FORCE_PARTICLEVORTICITY_ADAPTIVE {}
		REAL FORCE_PARTICLEVORTICITY_INTENSITY { MIN 0.0; MAX 100000.0; STEP 0.01;}
		REAL FORCE_PARTICLEVORTICITY_RADIUS {MIN 1;}			
		REAL FORCE_PARTICLEVORTICITY_STRETCH_MIN { MIN 0.001; MAX 200.0; STEP 0.001;}
		REAL FORCE_PARTICLEVORTICITY_STRETCH_MAX { MIN 0.001; MAX 200.0; STEP 0.001;}
		LONG FORCE_PARTICLEVORTICITY_KERNEL
		{
			CYCLE
			{
				FORCE_PARTICLEVORTICITY_KERNEL_GAUSS;
				FORCE_PARTICLEVORTICITY_KERNEL_POLY6;
				FORCE_PARTICLEVORTICITY_KERNEL_POLY6SMOOTH;
				FORCE_PARTICLEVORTICITY_KERNEL_VISCOSITY;
				FORCE_PARTICLEVORTICITY_KERNEL_SPIKEY;
				FORCE_PARTICLEVORTICITY_KERNEL_SPIKEYSMOOTH;
				FORCE_PARTICLEVORTICITY_KERNEL_SMOOTH;
				FORCE_PARTICLEVORTICITY_KERNEL_SHARP;
				FORCE_PARTICLEVORTICITY_KERNEL_WYVILL;
				FORCE_PARTICLEVORTICITY_KERNEL_BLINN;
				FORCE_PARTICLEVORTICITY_KERNEL_SPLINE;
				FORCE_PARTICLEVORTICITY_KERNEL_POLYNOMIAL;
				FORCE_PARTICLEVORTICITY_KERNEL_CUSTOM;
			}
		}
		REAL FORCE_PARTICLEVORTICITY_KERNEL_LENGTH { MIN 0.001; }
		SPLINE FORCE_PARTICLEVORTICITY_KERNEL_SPLINE 
		{
			SHOWGRID_H; X_MIN 0; X_MAX 1; Y_MIN 0; Y_MAX 1; X_STEPS 0.01; Y_STEPS 0.01; 
		}
	}		
}