#ifndef FX_FORCE_FOLLOWSPLINE_H
#define FX_FORCE_FOLLOWSPLINE_H

enum
{	
	FORCE_FOLLOWSPLINE_STEER = 2000,
	FORCE_FOLLOWSPLINE_FOLLOW,
	
	FORCE_FOLLOWSPLINE_SPLINE = 1000,
	FORCE_FOLLOWSPLINE_SPLINE_SELECTOR,
	FORCE_FOLLOWSPLINE_DURATION,
	FORCE_FOLLOWSPLINE_DURATION_SELECTOR,
		
	FORCE_FOLLOWSPLINE_STEERACUTENESS,
	FORCE_FOLLOWSPLINE_STEERDISTANCE,
	FORCE_FOLLOWSPLINE_STEERMODE = 1006,
		FORCE_FOLLOWSPLINE_STEERMODE_NEAREST = 0,
		FORCE_FOLLOWSPLINE_STEERMODE_NEARESTVERTEX,
		FORCE_FOLLOWSPLINE_STEERMODE_VERTEX,
		FORCE_FOLLOWSPLINE_STEERMODE_PERCENT,
	FORCE_FOLLOWSPLINE_STEERMAXVELOCITY = 1007,
	FORCE_FOLLOWSPLINE_STEERINTENSITY,
	FORCE_FOLLOWSPLINE_STEERSEGMENT,
	FORCE_FOLLOWSPLINE_STEERVERTEX,
	FORCE_FOLLOWSPLINE_STEERPERCENT,
	
	FORCE_FOLLOWSPLINE_FOLLOWDISTANCE,
	FORCE_FOLLOWSPLINE_FOLLOWMODE = 1013,
		FORCE_FOLLOWSPLINE_FOLLOWMODE_FORWARD = 0,
		FORCE_FOLLOWSPLINE_FOLLOWMODE_BACKWARD,
	FORCE_FOLLOWSPLINE_FOLLOWMAXVELOCITY = 1014,
	FORCE_FOLLOWSPLINE_FOLLOWINTENSITY,
	FORCE_FOLLOWSPLINE_FOLLOWACUTENESS,

	FORCE_FOLLOWSPLINE_DUMMY_

};

#endif