#ifndef FX_FORCE_BOUYANCY_H
#define FX_FORCE_BOUYANCY_H

enum
{	
	FORCE_BOUYANCY_TEMPERATURE = 1000,
	FORCE_BOUYANCY_FUEL,
	FORCE_BOUYANCY_SMOKE,
	FORCE_BOUYANCY_DIRECTION,
	FORCE_BOUYANCY_RISING,
	FORCE_BOUYANCY_FALLING,
	FORCE_BOUYANCY_TEMPERATURE_SELECTOR,
	FORCE_BOUYANCY_FUEL_SELECTOR,
	FORCE_BOUYANCY_SMOKE_SELECTOR,
	FORCE_BOUYANCY_DURATION,
	FORCE_BOUYANCY_DURATION_SELECTOR,

	FORCE_BOUYANCY_DUMMY_

};

#endif