CONTAINER fx_force_followspline
{
	NAME fx_force_followspline;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	INCLUDE fx_base_display_inspector;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK	FORCE_FOLLOWSPLINE_SPLINE {ACCEPT{Ospline;}}
			BUTTON	FORCE_FOLLOWSPLINE_SPLINE_SELECTOR {}
			LINK	FORCE_FOLLOWSPLINE_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON	FORCE_FOLLOWSPLINE_DURATION_SELECTOR {}
		}

		SEPARATOR {LINE;}

		GROUP FORCE_FOLLOWSPLINE_STEER
		{
			DEFAULT 1;
			REAL FORCE_FOLLOWSPLINE_STEERDISTANCE	{ MIN 0.001; STEP 0.1; UNIT METER;}
			LONG FORCE_FOLLOWSPLINE_STEERMODE
			{
				CYCLE
				{
					FORCE_FOLLOWSPLINE_STEERMODE_NEAREST;
					FORCE_FOLLOWSPLINE_STEERMODE_NEARESTVERTEX;
					FORCE_FOLLOWSPLINE_STEERMODE_VERTEX;
					FORCE_FOLLOWSPLINE_STEERMODE_PERCENT;
				}
			}
			LONG FORCE_FOLLOWSPLINE_STEERSEGMENT { MIN 1; }
			LONG FORCE_FOLLOWSPLINE_STEERVERTEX { MIN 0; }
			REAL FORCE_FOLLOWSPLINE_STEERPERCENT { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }

			SEPARATOR {LINE;}
			
			REAL FORCE_FOLLOWSPLINE_STEERMAXVELOCITY{ MIN 0; MAXSLIDER 100; UNIT METER;}
			REAL FORCE_FOLLOWSPLINE_STEERACUTENESS	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL FORCE_FOLLOWSPLINE_STEERINTENSITY	{ MIN 0; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			

		}
		GROUP FORCE_FOLLOWSPLINE_FOLLOW
		{
			DEFAULT 1;
			REAL FORCE_FOLLOWSPLINE_FOLLOWDISTANCE	{ MIN 0.001; STEP 0.1; UNIT METER;}
			LONG FORCE_FOLLOWSPLINE_FOLLOWMODE
			{
				CYCLE
				{
					FORCE_FOLLOWSPLINE_FOLLOWMODE_FORWARD;
					FORCE_FOLLOWSPLINE_FOLLOWMODE_BACKWARD;
				}
			}
			REAL FORCE_FOLLOWSPLINE_FOLLOWMAXVELOCITY{ MIN 0; MAXSLIDER 100; UNIT METER;}
			REAL FORCE_FOLLOWSPLINE_FOLLOWACUTENESS	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL FORCE_FOLLOWSPLINE_FOLLOWINTENSITY	{ MIN 0; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		}		
	}
}