#ifndef FX_FLUID_PBF_H
#define FX_FLUID_PBF_H

enum
{	
	FLUID_PBF_GROUP_MATERIAL = 2000,
	FLUID_PBF_GROUP_DYNAMICS,
	FLUID_PBF_GROUP_SOLVER,
		
	FLUID_PBF_PARTICLES = 1000,
	FLUID_PBF_RADIUS,
	FLUID_PBF_DENSITY,
	FLUID_PBF_VISCOSITY,
	FLUID_PBF_COLLIDE,
	FLUID_PBF_CMARGIN,
	FLUID_PBF_RELAX,
	FLUID_PBF_SOLVER_ITERATIONS,
	FLUID_PBF_DELTAQ,
	FLUID_PBF_PK,
	FLUID_PBF_PN,
	FLUID_PBF_OPERATORS,
	FLUID_PBF_MAXNEIGHBORS,
	FLUID_PBF_VORTICITY,

	//SELECTORS
	FLUID_PBF_PARTICLES_SELECTOR = 1100,
	FLUID_PBF_OPERATORS_SELECTOR

};

#endif