#ifndef FX_FORCE_SWIRLING_H
#define FX_FORCE_SWIRLING_H

enum
{	
	FORCE_SWIRLING_INTENSITY = 1000,
	FORCE_SWIRLING_DURATION,
	FORCE_SWIRLING_DURATION_SELECTOR,
	FORCE_SWIRLING_CONSERVE,
	FORCE_SWIRLING_ADAPTIVE,

	FORCE_SWIRLING_DUMMY_

};

#endif