#ifndef FX_FORCE_COFFEE_H
#define FX_FORCE_COFFEE_H

enum
{	
	FORCE_COFFEE_INTENSITY = 1000,
	FORCE_COFFEE_SETTINGS,
	FORCE_COFFEE_SETTINGS_SELECTOR,
	FORCE_COFFEE_DURATION,
	FORCE_COFFEE_DURATION_SELECTOR,

	FORCE_COFFEE_DUMMY_

};

#endif