#ifndef FX_GRID_COOLING_H
#define FX_GRID_COOLING_H

enum
{	
	GRID_COOLING_TEMPERATURE = 1000,
	GRID_COOLING_FIRE,
	GRID_COOLING_FACTOR,
	GRID_COOLING_CONSTRAINTS,
	GRID_COOLING_TYPE = 1004,
		GRID_COOLING_TYPE_PHYSICAL = 0,
		GRID_COOLING_TYPE_EXPONENT,
		GRID_COOLING_TYPE_DISIPATE,
	GRID_COOLING_TEMPERATURE_SELECTOR = 1005,
	GRID_COOLING_FIRE_SELECTOR,
	GRID_COOLING_MOEFFECTORS,

	GRID_COOLING_DUMMY_

};

#endif