#ifndef fx_grid_sand_H
#define fx_grid_sand_H

enum
{	
	FXGRID_SAND_SOLVER = 1000,
	FXGRID_SAND_DENSITY,

	FXGRID_SAND_FRICTION,	
	FXGRID_SAND_COHESION,
	FXGRID_SAND_FRICTION_YIELD,
	FXGRID_SAND_FRICTION_WALLS,

	FXGRID_SAND_SOLVER_SELECTOR = 1050,
	FXGRID_SAND_DENSITY_SELECTOR,
	
	FXGRID_SAND_DUMMY

};

#endif