#ifndef FX_GROUP_H
#define FX_GROUP_H

enum
{	
	FX_GROUP_SHOW = 1000,
	FX_GROUP_ICON = 1001,
		FX_GROUP_ICON_DEFAULT = 0,
	FX_GROUP_PORTTAB = 1002,
	FX_GROUP_RESET,
	FX_GROUP_SAVE,
	FX_GROUP_USEGROUP,
	FX_GROUP_HIDEQUICKTAB,
	FX_GROUP_LOCK,
	FX_GROUP_UNLOCK,
	FX_GROUP_LOCKLIST
};

#endif