CONTAINER fx_gridemitter
{
	NAME fx_gridemitter;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP FX_BASE_QUICKTAB
	{
		COLUMNS 4;
		BUTTON GRIDEMITTER_QUICK_STANDARD {}
		BUTTON GRIDEMITTER_QUICK_LOOPED {}
		BUTTON GRIDEMITTER_QUICK_PRESSURE {}
	}
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK GRIDEMITTER_VOLUME { ACCEPT { fx_volume; fx_csg; fx_volume_multi; fx_group; }; }
			BUTTON GRIDEMITTER_VOLUME_SELECTOR {}

			IN_EXCLUDE GRIDEMITTER_CHANNELSETTINGS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
				ACCEPT {  fx_channelsettings; };
			}
			BUTTON GRIDEMITTER_CHANNELSETTINGS_SELECTOR {}
		}
	}
}