CONTAINER fx_gop_particletolevelset
{
	NAME fx_gop_particletolevelset;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			IN_EXCLUDE GOP_PTL_GROUP
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0; SCALE_H;
				ACCEPT
				{
					fx_liquid; 
					fx_particlegroup; 
					1001381; 
					Obase; 
					Oparticle;
					1027133;
				}
			}
			BUTTON GOP_PTL_GROUP_SELECTOR {}

			LINK   GOP_PTL_TARGET { ACCEPT{ fx_liquid; fx_channel_levelset; fx_group;} }
			BUTTON GOP_PTL_TARGET_SELECTOR {}

			LINK	GOP_PTL_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON	GOP_PTL_DURATION_SELECTOR {SCALE_V; FIT_H;}
		}
		LONG GOP_PTL_PARTICLES
		{
			ANIM OFF;
			CYCLE
			{
				GOP_PTL_PARTICLES_PASSIVE;
				GOP_PTL_PARTICLES_VORTICITY;
				GOP_PTL_PARTICLES_LIQUID;
				GOP_PTL_PARTICLES_FOAM;
			}
		}
		LONG GOP_PTL_MODE
		{
			CYCLE
			{
				GOP_PTL_MODE_INCELL;
				GOP_PTL_MODE_DENSITY;
				GOP_PTL_MODE_SPHERE;
				//GOP_PTL_MODE_POSITIONS;
			}
		}
		BOOL GOP_PTL_EXTRAPOLATESOLIDS {}
		LONG GOP_PTL_EXTRAPOLATEMODE { CYCLE {GOP_PTL_EXTRAPOLATEMODE_SIMPLE; GOP_PTL_EXTRAPOLATEMODE_ADVANCED;} }
		LONG GOP_PTL_MODE_INCELL_LEVELSETRATE { MIN 0; MAX 4;}
		REAL GOP_PTL_MODE_DENSITY_LEVELSETRATE { MIN 0.0; MAX 1.0; STEP 0.001;}

		SEPARATOR {LINE;}

		REAL GOP_PTL_RADIUS { MIN 0.001; STEP 0.1; }
	}
}
			