#ifndef FX_GOP_TOLEVELSET_H
#define FX_GOP_TOLEVELSET_H

enum
{	
	GOP_TL_SOURCE = 1000,
	GOP_TL_SOURCE_SELECTOR,
	GOP_TL_DURATION,
	GOP_TL_DURATION_SELECTOR,
	GOP_TL_MODE = 1004,
		GOP_TL_MODE_DENSITY = 0,
		GOP_TL_MODE_SPHERE,
	GOP_TL_MODE_DENSITY_THRESHOLD = 1005,
	GOP_TL_MODE_SPHERE_RADIUS,
	GOP_TL_TARGET,
	GOP_TL_TARGET_SELECTOR,
	GOP_TL_MERGE
};

#endif