CONTAINER fx_group
{
	NAME fx_group;
	INCLUDE fx_base;
	HIDE Obaselist;
	HIDE ID_BASEOBJECT_GROUP1;

	GROUP FX_BASE_QUICKTAB
	{
		COLUMNS 3;
		BOOL FX_GROUP_SHOW { ANIM OFF;}
		BOOL FX_GROUP_PORTTAB {ANIM OFF; }
		BOOL FX_GROUP_USEGROUP { ANIM OFF; }
		LONG FX_GROUP_ICON { ANIM OFF; CYCLE { FX_GROUP_ICON_DEFAULT~1300151; } }
		BUTTON FX_GROUP_RESET { ANIM OFF; }
		BUTTON FX_GROUP_SAVE { ANIM OFF; }
	}
	GROUP FX_BASE
	{
		BOOL FX_GROUP_HIDEQUICKTAB {}
		BUTTON FX_GROUP_LOCK {HIDDEN;}
		BUTTON FX_GROUP_UNLOCK {HIDDEN;}
		IN_EXCLUDE FX_GROUP_LOCKLIST
		{
			HIDDEN;
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0; SCALE_H;
			ACCEPT {  Obase; }
		}
	}
}