#ifndef FX_GOP_FORCES_H
#define FX_GOP_FORCES_H

enum
{	
	GOP_FORCES_INPUT = 1000,
	GOP_FORCES_INPUT_SELECTOR,
	GOP_FORCES_DURATION,
	GOP_FORCES_DURATION_SELECTOR,
	GOP_FORCES_INTENSITY,
	GOP_FORCES_USEGRAVITY,
	GOP_FORCES_MODE = 1006,
		GOP_FORCES_MODE_ADD = 0,
		GOP_FORCES_MODE_SET,
	GOP_FORCES_VELOCITY = 1007,
	GOP_FORCES_VELOCITY_SELECTOR,	

	GOP_FORCES_END
};

#endif