#ifndef FX_GRID_DIFFUSION_H
#define FX_GRID_DIFFUSION_H

enum
{
	GRID_DIFFUSION_ITER_INTENSITY = 1000,
	GRID_DIFFUSION,
	GRID_DIFFUSION_ITER,
	GRID_DIFFUSION_CHANNEL,
	GRID_DIFFUSION_CHANNEL_SELECTOR,
	GRID_DIFFUSION_TYPE = 1005,
		GRID_DIFFUSION_TYPE_KERNEL = 0,
		GRID_DIFFUSION_TYPE_NEARESTNEIGHBOR,

	GRID_DIFFUSION_DUMMY_
		
};

#endif