#ifndef FX_GRID_COMBUSTION_FIRE_H
#define FX_GRID_COMBUSTION_FIRE_H

enum
{	
	GRID_COMBUSTION_TEMPERATURE = 1000,
	GRID_COMBUSTION_FIRE,
	GRID_COMBUSTION_FUEL,
	GRID_COMBUSTION_SMOKE,
	GRID_COMBUSTION_MODE,
		GRID_COMBUSTION_MODE_FUEL = 0,
		GRID_COMBUSTION_MODE_FUEL_OXYGEN,
	GRID_COMBUSTION_BURNINGRATE,
	GRID_COMBUSTION_OXYGEN,
	GRID_COMBUSTION_IGNITION_TEMP,
	GRID_COMBUSTION_HEAT,
	GRID_COMBUSTION_HEATUPCURVE,
	GRID_COMBUSTION_SOOT,
	GRID_COMBUSTION_SOOTCURVE,
	GRID_COMBUSTION_EXPANSION,
	GRID_COMBUSTION_COOLINGFACTOR,
	GRID_COMBUSTION_CONSTRAINTS,
	GRID_COMBUSTION_DIVERGENCE,
	GRID_COMBUSTION_TEMPERATURE_SELECTOR,
	GRID_COMBUSTION_FIRE_SELECTOR,
	GRID_COMBUSTION_FUEL_SELECTOR,
	GRID_COMBUSTION_SMOKE_SELECTOR,
	GRID_COMBUSTION_DIVERGENCE_SELECTOR,
	GRID_COMBUSTION_MOEFFECTORS,

	GRID_COMBUSTION_DUMMY_

};

#endif