#ifndef FX_GRID_VARIABLEDENSITY_H
#define FX_GRID_VARIABLEDENSITY_H

enum
{	
	GRID_VARIABLEDENSITY_TARGET = 1000,
	GRID_VARIABLEDENSITY_SMOKE,
	GRID_VARIABLEDENSITY_TEMP,

	GRID_VARIABLEDENSITY_ALPHA,	
	GRID_VARIABLEDENSITY_AIRDENSITY,	
	GRID_VARIABLEDENSITY_SOOTDENSITY,
	GRID_VARIABLEDENSITY_DENSITY_MODE = 1006,
		GRID_VARIABLEDENSITY_DENSITY_MODE_CUSTOM = 0,
		GRID_VARIABLEDENSITY_DENSITY_MODE_PHYSICAL,

	GRID_VARIABLEDENSITY_TARGET_SELECTOR = 1007,
	GRID_VARIABLEDENSITY_SMOKE_SELECTOR,
	GRID_VARIABLEDENSITY_TEMP_SELECTOR,
	
	GRID_VARIABLEDENSITY_DUMMY

};

#endif