#ifndef FX_GRID_ADVECTION_H
#define FX_GRID_ADVECTION_H

enum
{	
	FX_GRIDADVECTION_CHANNEL = 1000,
	FX_GRIDADVECTION_CHANNEL_SELECTOR,
	FX_GRIDADVECTION_PRECISION = 1002,
		FX_GRIDADVECTION_PRECISION_1ST = 0,
		FX_GRIDADVECTION_PRECISION_2ND = 1,
		FX_GRIDADVECTION_PRECISION_MASSMOMENTUM = 2,
		FX_GRIDADVECTION_PRECISION_2ND_MASSMOMENTUM = 3,
	FX_GRIDADVECTION_INTEGRATOR = 1003,
		FX_GRIDADVECTION_INTEGRATOR_EULER1ST = 0,
		FX_GRIDADVECTION_INTEGRATOR_RUNGA2ND,
		FX_GRIDADVECTION_INTEGRATOR_RUNGA3RD,
		FX_GRIDADVECTION_INTEGRATOR_RUNGA4TH,
	FX_GRIDADVECTION_INTERPOLATOR = 1004,
		FX_GRIDADVECTION_INTERPOLATOR_LINEAR = 0,
		FX_GRIDADVECTION_INTERPOLATOR_CUBIC,
		FX_GRIDADVECTION_INTERPOLATOR_HERMITE,
	FX_GRIDADVECTION_VELOCITY = 1005,
	FX_GRIDADVECTION_VELOCITY_SELECTOR,
	FX_GRIDADVECTION_MIX,

	FX_GRIDADVECTION_DUMMY_

};

#endif