CONTAINER fx_grid_variabledensity
{
	NAME fx_grid_variabledensity;
	INCLUDE fx_force_base;

	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP
		{
			COLUMNS 2;
			LINK GRID_VARIABLEDENSITY_SMOKE
			{
				ACCEPT { fx_channel_scalar; fx_group; };
			}
			BUTTON GRID_VARIABLEDENSITY_SMOKE_SELECTOR {}
			
			LINK GRID_VARIABLEDENSITY_TEMP
			{
				ACCEPT { fx_channel_scalar; fx_channel_temp; fx_group;};
			}
			BUTTON GRID_VARIABLEDENSITY_TEMP_SELECTOR {}

			LINK GRID_VARIABLEDENSITY_TARGET
			{
				ACCEPT { fx_channel_scalar; fx_channel_vector;  fx_group;};
			}
			BUTTON GRID_VARIABLEDENSITY_TARGET_SELECTOR {}
		}

		SEPARATOR {LINE;}

		REAL	GRID_VARIABLEDENSITY_ALPHA { MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; UNIT PERCENT; }
		LONG	GRID_VARIABLEDENSITY_DENSITY_MODE
		{
			CYCLE
			{
				GRID_VARIABLEDENSITY_DENSITY_MODE_CUSTOM;
				GRID_VARIABLEDENSITY_DENSITY_MODE_PHYSICAL;
			}
		}
		REAL	GRID_VARIABLEDENSITY_AIRDENSITY { MIN 0.01; STEP 0.01;}
		REAL	GRID_VARIABLEDENSITY_SOOTDENSITY { MIN 0.01; STEP 0.01; }
	}
}