#ifndef FX_GRID_CELLITERATOR_H
#define FX_GRID_CELLITERATOR_H

enum
{	
	FX_CELLEMITTER_CHANNEL = 1000,
	FX_CELLEMITTER_CELLOPERATORS,
	FX_CELLEMITTER_CHANNEL_SELECTOR,
	FX_CELLEMITTER_CELLOPERATORS_SELECTOR,
	FX_CELLEMITTER_CHANNEL_SOLVER = 1004,
		FX_CELLEMITTER_CHANNEL_SOLVER_DIVERGENCE = 0,
		FX_CELLEMITTER_CHANNEL_SOLVER_SURFACE,
		FX_CELLEMITTER_CHANNEL_SOLVER_VELOCITY,

	FX_CELLEMITTER_DUMMY_

};

#endif