CONTAINER fx_gop_cl
{
	NAME fx_gop_cl;
	INCLUDE fx_force_base;

	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			IN_EXCLUDE GOP_CL_SOURCE
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
				ACCEPT 
				{ 
					fx_particlegroup; 
					fx_liquid;  
					fx_fluid; 
					fx_channel_base;
					fx_rate;
				};
			}
			BUTTON GOP_CL_SOURCE_SELECTOR {SCALE_V; FIT_H;}
			LINK GOP_CL_TARGET
			{
				ACCEPT 
				{ 
					fx_liquid;  
					fx_fluid; 
					fx_channel_base;
					fx_particlegroup;
				};
			}
			BUTTON GOP_CL_TARGET_SELECTOR {SCALE_V; FIT_H;}

			LINK	GOP_CL_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON	GOP_CL_DURATION_SELECTOR {SCALE_V; FIT_H;}
		}
		//LONG GOP_CL_KERNEL_COUNT { MIN 1; MAX 50; }
	}
	GROUP GOP_CL_KERNEL_0
	{
		DEFAULT 1; 
		SCALE_V; 
		GROUP GOP_CL_KERNEL_LAYOUT_G
		{
			COLUMNS 2;
			LAYOUTGROUP;
			SCALE_H;
			SCALE_V; 
			GROUP GOP_CL_KERNEL_CODE_G
			{
				SCALE_H;
				SCALE_V;
				GROUP
				{
					COLUMNS 5;
					BUTTON GOP_CL_KERNELCOMPILE { }
					BOOL GOP_CL_SHOWINLINE {ANIM OFF;}
					SEPARATOR{}
					STATICTEXT {JOINENDSCALE;}
					BOOL GOP_CL_SHOWLIBRARIES {CUSTOMGUI BITMAP_BOOL; ANIM OFF; SCALE_V;}
				}
				
				SEPARATOR {}

				STRING GOP_CL_KERNELNAME {ANIM OFF; SCALE_H;}
				STRING GOP_CL_KERNELSIGNATURE
				{
					ANIM OFF;
					SCALE_H;
					CUSTOMGUI MULTISTRING;
					PYTHON;
					READONLY;
				}
				STRING GOP_CL_KERNELCODEINLINE
				{
					ANIM OFF;
					CUSTOMGUI MULTISTRING;
					PYTHON;
					SCALE_H;
					SCALE_V;
				}
				STRING GOP_CL_KERNELCODE
				{
					ANIM OFF;
					CUSTOMGUI MULTISTRING;
					PYTHON;
					SCALE_H;
					SCALE_V;
				}
				STRING GOP_CL_KERNELERROR
				{
					ANIM OFF; HIDDEN;
					CUSTOMGUI MULTISTRING;
					PYTHON;
					SCALE_H;
					SCALE_V;
					READONLY;
				}
				
				GROUP GOP_CL_KERNEL_PRESETS_G
				{
					DEFAULT 1;
					COLUMNS 5;
					SCALE_H;

					LONG GOP_CL_KERNEL_PRESETS
					{
						CYCLE
						{
							GOP_CL_KERNEL_PRESET_DEFAULT;
						}
					}
					BUTTON GOP_CL_KERNEL_PRESETS_SET {}
					BUTTON GOP_CL_KERNEL_PRESETS_SAVE {}
					BUTTON GOP_CL_KERNEL_PRESETS_SAVEAS {}
					BUTTON GOP_CL_KERNEL_PRESETS_DE {}
					STATICTEXT {JOINENDSCALE;}					
				}
			}	
			GROUP GOP_CL_KERNEL_LIBS_G
			{			
				BOOL GOP_CL_LIB_MATH		{PARENTCOLLAPSE; ANIM OFF; OPEN;}
				BOOL GOP_CL_LIB_MATH_BITS	{ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_MATH; PARENTID GOP_CL_LIB_MATH;}
				BOOL GOP_CL_LIB_MATH_CONSTANTS	{ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_MATH; PARENTID GOP_CL_LIB_MATH;}
				BOOL GOP_CL_LIB_MATH_TEMPLATES	{ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_MATH; PARENTID GOP_CL_LIB_MATH;}
				BOOL GOP_CL_LIB_MATH_INTERPOLATION {ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_MATH; PARENTID GOP_CL_LIB_MATH;}
				BOOL GOP_CL_LIB_MATH_VECTOR	{ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_MATH; PARENTID GOP_CL_LIB_MATH;}
				
				BOOL GOP_CL_LIB_GRIDS		{PARENTCOLLAPSE; ANIM OFF; OPEN;}
				BOOL GOP_CL_LIB_GRIDS_SPACE	{ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_GRIDS; PARENTID GOP_CL_LIB_GRIDS;}
				BOOL GOP_CL_LIB_GRIDS_INDEXER	{ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_GRIDS; PARENTID GOP_CL_LIB_GRIDS;}
				BOOL GOP_CL_LIB_GRIDS_CELLACCESS {ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_GRIDS; PARENTID GOP_CL_LIB_GRIDS;}
				BOOL GOP_CL_LIB_GRIDS_SAMPLER	{ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_GRIDS; PARENTID GOP_CL_LIB_GRIDS;}
				BOOL GOP_CL_LIB_GRIDS_NORMALSAMPLER {ANIM OFF; PARENTCOLLAPSE GOP_CL_LIB_GRIDS; PARENTID GOP_CL_LIB_GRIDS;}
				BOOL GOP_CL_LIB_GRIDS_VELSAMPLER {ANIM OFF; PARENTID GOP_CL_LIB_GRIDS;}
				
				BOOL GOP_CL_LIB_PARTICLES	{PARENTCOLLAPSE; ANIM OFF; OPEN;}

				BOOL GOP_CL_LIB_COLLISION	{PARENTCOLLAPSE; ANIM OFF; OPEN;}
			}
		}
	}
	INCLUDE fx_base_constraints;
}
			