#ifndef FX_GOP_PARTICLETOLEVELSET_H
#define FX_GOP_PARTICLETOLEVELSET_H

enum
{	
	GOP_PTL_GROUP = 1000,
	GOP_PTL_GROUP_SELECTOR,
	GOP_PTL_DURATION,
	GOP_PTL_DURATION_SELECTOR,
	GOP_PTL_PARTICLES = 1004,
		GOP_PTL_PARTICLES_PASSIVE = 0,
		GOP_PTL_PARTICLES_VORTICITY,
		GOP_PTL_PARTICLES_LIQUID,
		GOP_PTL_PARTICLES_FOAM,
	GOP_PTL_MODE = 1005,
		GOP_PTL_MODE_INCELL = 0,
		GOP_PTL_MODE_DENSITY,
		GOP_PTL_MODE_SPHERE,
		GOP_PTL_MODE_POSITIONS,
	GOP_PTL_MODE_INCELL_LEVELSETRATE = 1006,
	GOP_PTL_MODE_DENSITY_LEVELSETRATE,
	GOP_PTL_EXTRAPOLATESOLIDS,
	GOP_PTL_TARGET,
	GOP_PTL_TARGET_SELECTOR,
	GOP_PTL_RADIUS,
	GOP_PTL_EXTRAPOLATEMODE = 1012,
		GOP_PTL_EXTRAPOLATEMODE_SIMPLE = 0,
		GOP_PTL_EXTRAPOLATEMODE_ADVANCED,
	
	GOP_PTL_COUNT
};

#endif