#ifndef FX_GOP_CL_H
#define FX_GOP_CL_H

enum
{	
	GOP_CL_SOURCE = 1000,
	GOP_CL_SOURCE_SELECTOR,
	GOP_CL_TARGET,
	GOP_CL_TARGET_SELECTOR,
	GOP_CL_DURATION,
	GOP_CL_DURATION_SELECTOR,

	GOP_CL_KERNELSIGNATURE = 1100,
	GOP_CL_KERNELCODE,
	GOP_CL_KERNELNAME,
	GOP_CL_KERNELCODEINLINE,
	GOP_CL_KERNELCOMPILE,
	GOP_CL_SHOWINLINE,
	GOP_CL_KERNELERROR,

	GOP_CL_SHOWLIBRARIES = 1120,
	GOP_CL_LIB_MATH,
	GOP_CL_LIB_MATH_BITS,
	GOP_CL_LIB_MATH_CONSTANTS,
	GOP_CL_LIB_MATH_TEMPLATES,
	GOP_CL_LIB_MATH_INTERPOLATION,
	GOP_CL_LIB_MATH_VECTOR,
	GOP_CL_LIB_GRIDS,
	GOP_CL_LIB_GRIDS_SPACE,
	GOP_CL_LIB_GRIDS_INDEXER,
	GOP_CL_LIB_GRIDS_CELLACCESS,
	GOP_CL_LIB_GRIDS_SAMPLER,
	GOP_CL_LIB_GRIDS_VELSAMPLER,
	GOP_CL_LIB_GRIDS_NORMALSAMPLER,
	GOP_CL_LIB_PARTICLES,
	GOP_CL_LIB_COLLISION,
		
	GOP_CL_KERNEL_0 = 1950,
	GOP_CL_KERNEL_LAYOUT_G,
	GOP_CL_KERNEL_CODE_G,
	GOP_CL_KERNEL_LIBS_G,
		
	GOP_CL_KERNEL_PRESETS = 2100,
		GOP_CL_KERNEL_PRESET_DEFAULT = 0,
	GOP_CL_KERNEL_PRESETS_SET = 2101,
	GOP_CL_KERNEL_PRESETS_SAVE,
	GOP_CL_KERNEL_PRESETS_SAVEAS,
	GOP_CL_KERNEL_PRESETS_DE,
	GOP_CL_KERNEL_PRESETS_G,

	GOP_CL_END
};

#endif