#ifndef FX_GOP_REDISTANCE_H
#define FX_GOP_REDISTANCE_H

enum
{	
	GOP_REDISTANCE_TARGET = 1000,
	GOP_REDISTANCE_TARGET_SELECTOR,
	GOP_REDISTANCE_DURATION,
	GOP_REDISTANCE_DURATION_SELECTOR,
	GOP_REDISTANCE_MODE = 1004,
		GOP_REDISTANCE_MODE_SWEEP = 0,
		GOP_REDISTANCE_MODE_MARCH,
	
	GOP_REDISTANCE_LAST
};

#endif