#ifndef FX_GRIDEMITTER_H
#define FX_GRIDEMITTER_H

enum
{
	GRIDEMITTER_CHANNELSETTINGS = 1000,
	GRIDEMITTER_CONSTRAINTS,
	GRIDEMITTER_VOLUME,
	GRIDEMITTER_VOLUME_SELECTOR,
	GRIDEMITTER_MOEFFECTORS,
	GRIDEMITTER_CHANNELSETTINGS_SELECTOR,
	
	GRIDEMITTER_QUICK_STANDARD = 1100,
	GRIDEMITTER_QUICK_LOOPED,
	GRIDEMITTER_QUICK_PRESSURE,
	
	GRIDEMITTER_DUMMY_
};

#endif