#ifndef FX_IOP_REPULSION_H
#define FX_IOP_REPULSION_H

enum
{	
	IOP_REPULSION_BOUNCE = 1000,
	IOP_REPULSION_DURATION,
	IOP_REPULSION_DURATION_SELECTOR,
	IOP_REPULSION_POSITIONBASED,
	IOP_REPULSION_SLIDEDRAG,

	IOP_REPULSION_DUMMY_

};

#endif