#ifndef FX_IOP_VOLUMEPROJECT_H
#define FX_IOP_VOLUMEPROJECT_H

enum
{	
	IOP_VOLUMEPROJECT_VOLUME = 1000,
	IOP_VOLUMEPROJECT_VOLUME_SELECTOR,
	IOP_VOLUMEPROJECT_PROPERTY,
	IOP_VOLUMEPROJECT_PROPERTY_SELECTOR,
	IOP_VOLUMEPROJECT_POSITIONBASED,
	IOP_VOLUMEPROJECT_MIX,
	IOP_VOLUMEPROJECT_SURFACEOFFSET,
	IOP_VOLUMEPROJECT_DURATION,
	IOP_VOLUMEPROJECT_DURATION_SELECTOR,
	IOP_VOLUMEPROJECT_MIXORIGINAL,
	IOP_VOLUMEPROJECT_CONSTRAINTS_MIXORIG,
	IOP_VOLUMEPROJECT_CONSTRAINTS_MIXORIG_SELECTOR,

	IOP_VOLUMEPROJECT_DUMMY_

};

#endif