CONTAINER fx_iop_volumeproject
{
	NAME fx_iop_volumeproject;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK IOP_VOLUMEPROJECT_VOLUME { ACCEPT { fx_volume; fx_volume_multi; fx_surface_reconstruction; fx_group;}; }
			BUTTON IOP_VOLUMEPROJECT_VOLUME_SELECTOR {}

			LINK IOP_VOLUMEPROJECT_PROPERTY { ACCEPT { fx_property_vector; fx_group;}; }
			BUTTON IOP_VOLUMEPROJECT_PROPERTY_SELECTOR {}

			LINK IOP_VOLUMEPROJECT_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON IOP_VOLUMEPROJECT_DURATION_SELECTOR {}
		}
		BOOL IOP_VOLUMEPROJECT_POSITIONBASED {}
		REAL IOP_VOLUMEPROJECT_MIX		{MIN 0; MAXSLIDER 500; UNIT PERCENT; CUSTOMGUI REALSLIDER; FIT_H;}
		REAL IOP_VOLUMEPROJECT_MIXORIGINAL	{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; FIT_H;}
		REAL IOP_VOLUMEPROJECT_SURFACEOFFSET	{UNIT METER; STEP 0.1; }
	}
	GROUP ID_FORCE_BASE_CONSTRAINTS_SUB
	{
		IN_EXCLUDE IOP_VOLUMEPROJECT_CONSTRAINTS_MIXORIG
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0; SCALE_H;
			ACCEPT 
			{  
				fx_constraint;
				fx_constraint_plugin;
			};
		}
		BUTTON IOP_VOLUMEPROJECT_CONSTRAINTS_MIXORIG_SELECTOR { SCALE_V; FIT_H;}
	}
}
			