CONTAINER fx_iop_spawn
{
	NAME fx_iop_spawn;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK IOP_SPAWN_PARTICLESOUT { ACCEPT { Obase;} }
			BUTTON IOP_SPAWN_PARTICLESOUT_SELECTOR {}
			LINK IOP_SPAWN_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON IOP_SPAWN_DURATION_SELECTOR {}
		}
		
		SEPARATOR{LINE;}
		
		LONG IOP_SPAWN_PARTICLES_FACTORY
		{
			CYCLE
			{
				IOP_SPAWN_PARTICLES_FACTORY_PASSIVE;
				IOP_SPAWN_PARTICLES_FACTORY_VORTICITY;
				IOP_SPAWN_PARTICLES_FACTORY_LIQUID;
				IOP_SPAWN_PARTICLES_FACTORY_DIFFUSE;
			}
		} 
		BOOL IOP_SPAWN_POSITIONBASED {}
		BOOL IOP_SPAWN_KILLORIGINAL {}
		BOOL IOP_SPAWN_ALLOWRESPAWNING {}
		BOOL IOP_SPAWN_ALLOWSPAWNING_SPAWNED {}
		LONG IOP_SPAWN_DISTRIBUTION_MODE
		{
			CYCLE
			{
				IOP_SPAWN_DISTRIBUTION_MODE_UNIFORM;
				IOP_SPAWN_DISTRIBUTION_MODE_UNIFORM_RANDOM;
				IOP_SPAWN_DISTRIBUTION_MODE_CUSTOM;
				IOP_SPAWN_DISTRIBUTION_MODE_CUSTOM_RANDOM;
			}
		}

		SEPARATOR{LINE;}
		GROUP
		{
			COLUMNS 2; 
			LONG IOP_SPAWN_SEED {MIN 0;}STATICTEXT {NEWLINE;}
			LONG IOP_SPAWN_COUNT {MIN 0;} STATICTEXT {NEWLINE;}
			LONG IOP_SPAWN_COUNT_RENDER {MIN 0;}	
			REAL IOP_SPAWN_COUNT_VAR {MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; FIT_H;}

			LONG IOP_SPAWN_AGE		{MIN 1;}	
			REAL IOP_SPAWN_AGE_VAR		{MIN 0; MAX 100; UNIT PERCENT;CUSTOMGUI REALSLIDER; FIT_H;}
			
			REAL IOP_SPAWN_ANGLE		{MIN 0; MAX 180; UNIT DEGREE;}	
			REAL IOP_SPAWN_ANGLE_VAR	{MIN 0; MAX 100; UNIT PERCENT;CUSTOMGUI REALSLIDER;  FIT_H;}
			
			REAL IOP_SPAWN_DISTRIBUTE	{MIN 0; MAX 360; UNIT DEGREE;}	
			REAL IOP_SPAWN_DISTRIBUTE_VAR	{MIN 0; MAX 100; UNIT PERCENT;CUSTOMGUI REALSLIDER;  FIT_H;}

			REAL IOP_SPAWN_VELOCITY		{MIN 0; UNIT PERCENT;}	
			REAL IOP_SPAWN_VELOCITY_VAR	{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}	

			REAL IOP_SPAWN_ACCELERATION	{MIN 0; UNIT PERCENT;}	
			REAL IOP_SPAWN_ACCELERATION_VAR	{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}	
		}
	}
}
			