#ifndef FX_IOP_SPAWN_H
#define FX_IOP_SPAWN_H

enum
{	
	IOP_SPAWN_SEED = 1000,
	IOP_SPAWN_COUNT,
	IOP_SPAWN_COUNT_RENDER,
	IOP_SPAWN_COUNT_VAR,
	IOP_SPAWN_AGE,
	IOP_SPAWN_AGE_VAR,			
	IOP_SPAWN_ANGLE,
	IOP_SPAWN_ANGLE_VAR,
	IOP_SPAWN_VELOCITY,
	IOP_SPAWN_VELOCITY_VAR,
	IOP_SPAWN_PARTICLESOUT,
	IOP_SPAWN_PARTICLESOUT_SELECTOR,
	IOP_SPAWN_DURATION,
	IOP_SPAWN_DURATION_SELECTOR,
	IOP_SPAWN_PARTICLES_FACTORY = 1014,
		IOP_SPAWN_PARTICLES_FACTORY_PASSIVE = 0,
		IOP_SPAWN_PARTICLES_FACTORY_VORTICITY,
		IOP_SPAWN_PARTICLES_FACTORY_LIQUID,
		IOP_SPAWN_PARTICLES_FACTORY_DIFFUSE,
	IOP_SPAWN_POSITIONBASED = 1015,
	IOP_SPAWN_ALLOWRESPAWNING,
	IOP_SPAWN_ALLOWSPAWNING_SPAWNED,
	IOP_SPAWN_DISTRIBUTION_MODE = 1018,
		IOP_SPAWN_DISTRIBUTION_MODE_UNIFORM = 0,
		IOP_SPAWN_DISTRIBUTION_MODE_UNIFORM_RANDOM,
		IOP_SPAWN_DISTRIBUTION_MODE_CUSTOM,
		IOP_SPAWN_DISTRIBUTION_MODE_CUSTOM_RANDOM,
	IOP_SPAWN_DISTRIBUTE = 1019,
	IOP_SPAWN_DISTRIBUTE_VAR,
	IOP_SPAWN_ACCELERATION,
	IOP_SPAWN_ACCELERATION_VAR,
	IOP_SPAWN_KILLORIGINAL,

	IOP_SPAWN_DUMMY_

};

#endif