CONTAINER fx_iop_repulsion
{
	NAME fx_iop_repulsion;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK IOP_REPULSION_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON IOP_REPULSION_DURATION_SELECTOR {}
		}
		
		SEPARATOR{LINE;}

		BOOL IOP_REPULSION_POSITIONBASED {}
		REAL IOP_REPULSION_BOUNCE	{MIN 0; MAX 100000; MAXSLIDER 100; UNIT PERCENT;CUSTOMGUI REALSLIDER; }
		REAL IOP_REPULSION_SLIDEDRAG {MIN -100; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
	}
}
			