CONTAINER fx_kernel
{
	NAME fx_kernel;
	INCLUDE fx_force_base;
	
	GROUP ID_FORCE_BASE
	{
		LONG KERNEL
		{
			CYCLE
			{
				KERNEL_GAUSS;
				KERNEL_POLY6;
				KERNEL_POLY6SMOOTH;
				KERNEL_VISCOSITY;
				KERNEL_SPIKEY;
				KERNEL_SPIKEYSMOOTH;
				KERNEL_SMOOTH;
				KERNEL_SHARP;
				KERNEL_WYVILL;
				KERNEL_BLINN;
				KERNEL_SPLINE;
				KERNEL_POLYNOMIAL;
				KERNEL_CUSTOM;
			}
		}
		SPLINE KERNEL_SPLINEGRAPH { SHOWGRID_H; X_MIN 0; X_MAX 1; Y_MIN 0; Y_MAX 1; X_STEPS 0.01; Y_STEPS 0.01; }
	}
}