#ifndef FX_KERNEL_H
#define FX_KERNEL_H

enum
{	
	KERNEL = 7150,
		KERNEL_GAUSS = 0,
		KERNEL_POLY6,
		KERNEL_POLY6SMOOTH,
		KERNEL_VISCOSITY,
		KERNEL_SPIKEY,
		KERNEL_SPIKEYSMOOTH,
		KERNEL_SMOOTH,
		KERNEL_SHARP,
		KERNEL_WYVILL,
		KERNEL_BLINN,
		KERNEL_SPLINE,
		KERNEL_POLYNOMIAL,
		KERNEL_CUSTOM,
	KERNEL_SPLINEGRAPH
};

#endif