CONTAINER fx_liquid
{
	NAME fx_liquid;
	INCLUDE fx_fluid;
	HIDE FX_BASE;
	SHOW FLUID_QUICK_VARIABLEVISCOSITY;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			IN_EXCLUDE LIQUID_PARTICLES
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0; SCALE_H;
				ACCEPT {  fx_particlegroup; }
			}
			BUTTON LIQUID_PARTICLES_SELECTOR { SCALE_V; FIT_H; }

			LINK LIQUID_SURFACE_TRACKER { ACCEPT{fx_channel_levelset;}}
			BUTTON LIQUID_SURFACE_TRACKER_SELECTOR {}
		}
		GROUP SOLVER_GROUP_ID
		{		
			SEPARATOR {LINE;}

			LONG LIQUID_TRACKING_TYPE 
			{
				CYCLE
				{
					LIQUID_TRACKING_TYPE_OFF;
					LIQUID_TRACKING_TYPE_INCELL;
					LIQUID_TRACKING_TYPE_DENSITY;
				}
			}
			REAL LIQUID_TRACKING_TYPE_DENSITY_LEVELSETRATE { MIN 0.0; MAX 1.0; STEP 0.001;}
			LONG LIQUID_TRACKING_TYPE_INCELL_LEVELSETRATE { MIN 0; MAX 4;}
		}
		GROUP FLUID_GROUP_DYNAMICS
		{				
			SEPARATOR LIQUID_FLIP {}

			LONG LIQUID_FLIP_MODE 
			{
				CYCLE
				{
					LIQUID_FLIP_MODE_FLIP;
					LIQUID_FLIP_MODE_APIC;
				}
			}
			//FLIP
			BOOL LIQUID_FLIP_GTP {}
			REAL LIQUID_FLIP_PICFLIP { MIN 0.0; MAX 200; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			BOOL LIQUID_FLIP_SPH {}
			REAL LIQUID_FLIP_SPHRADIUS { MIN 1.0; MAX 4.0; STEP 0.1; PARENTID LIQUID_FLIP_SPH; }
			LINK LIQUID_FLIP_SPHKERNEL {  PARENTID LIQUID_FLIP_SPH; ACCEPT { fx_kernel;  fx_group;} }

			//HFAFLIP
			//REAL LIQUID_FLIP_HFA_THRESHOLD_VELOCITY { MIN 0.0; MAX 10000; STEP 0.5;}
			//LONG LIQUID_FLIP_HFA_THRESHOLD_PARTICLES { MIN 1; }
			//LONG LIQUID_FLIP_HFA_THRESHOLD_ZONECELLS { MIN 1; }
		}
	}
}