CONTAINER fx_levelset_smoother
{
	NAME fx_levelset_smoother;
	INCLUDE fx_force_base;

	//Basic Tab
	GROUP ID_FORCE_BASE
	{			
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK LEVELSET_SMOOTHER_VOLUME { ACCEPT{fx_volume; fx_csg; fx_channel_levelset; fx_surface_reconstruction; fx_group;}; }
			BUTTON LEVELSET_SMOOTHER_VOLUME_SELECTOR {}
		}
		
		SEPARATOR{LINE;}

		BOOL LEVELSET_SMOOTHER_INITIALREDISTANCE {}		
		LONG LEVELSET_SMOOTHER_LAPLACE_ITER { MIN 0; MAX 1000; }
		LONG LEVELSET_SMOOTHER_BIHARMONIC_ITER { MIN 0; MAX 1000; }
		REAL LEVELSET_SMOOTHER_BIHARMONIC_GAIN { MIN 0.1; STEP 0.1; }
		LONG LEVELSET_SMOOTHER_REDISTANCE_ITER { MIN 1; MAX 1000; }
		
		SEPARATOR {LINE;}

		REAL LEVELSET_SMOOTHER_RINIT { MIN 0.0; MAX 100; UNIT PERCENT;}
		REAL LEVELSET_SMOOTHER_RMIN { MIN -10.0; STEP 0.1; }
		REAL LEVELSET_SMOOTHER_RMAX { MIN 0.0; STEP 0.1; }
	}
}