#ifndef FX_LEVELSET_SMOOTHER_H
#define FX_LEVELSET_SMOOTHER_H

enum
{
	LEVELSET_SMOOTHER_INITIALREDISTANCE = 1000,
	LEVELSET_SMOOTHER_VOLUME,
	LEVELSET_SMOOTHER_LAPLACE_ITER,
	LEVELSET_SMOOTHER_BIHARMONIC_ITER,
	LEVELSET_SMOOTHER_REDISTANCE_ITER,
	LEVELSET_SMOOTHER_BIHARMONIC_GAIN,
		
	LEVELSET_SMOOTHER_RINIT,
	LEVELSET_SMOOTHER_RMIN,
	LEVELSET_SMOOTHER_RMAX,
	LEVELSET_SMOOTHER_VOLUME_SELECTOR,

	LEVELSET_SMOOTHER_DUMMY_
		
};

#endif