#ifndef FX_LIQUID_H
#define FX_LIQUID_H

enum
{
	LIQUID_SURFACE_TRACKER = 1200,
	LIQUID_PARTICLES,
	LIQUID_FLIP_MODE = 1203,
		LIQUID_FLIP_MODE_FLIP = 0,
		LIQUID_FLIP_MODE_HFAFLIP,
		LIQUID_FLIP_MODE_APIC,
	LIQUID_FLIP_PICFLIP = 1204,
	LIQUID_FLIP_HFA_ZONEFACTOR,
	LIQUID_FLIP_HFA_THRESHOLD_VELOCITY,
	LIQUID_FLIP_HFA_THRESHOLD_PARTICLES,
	LIQUID_FLIP_HFA_THRESHOLD_ZONECELLS,
	LIQUID_FLIP_SPH,
	LIQUID_TRACKING_TYPE = 1210,
		LIQUID_TRACKING_TYPE_INCELL = 0,
		LIQUID_TRACKING_TYPE_DENSITY,
		LIQUID_TRACKING_TYPE_OFF = 50,
	LIQUID_FLIP_SPHRADIUS = 1211,
	LIQUID_TRACKING_TYPE_DENSITY_LEVELSETRATE,
	LIQUID_SURFACE_TRACKER_SELECTOR,
	LIQUID_TRACKING_TYPE_INCELL_LEVELSETRATE,
	LIQUID_PARTICLES_SELECTOR,
	LIQUID_FLIP_GTP,
	LIQUID_FLIP_SPHKERNEL,
	LIQUID_FLIP,

	LIQUID_DUMMY_

};

#endif