CONTAINER fx_mop_to_levelset
{
	NAME fx_mop_to_levelset;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK MOP_TOLEVELSET_MESH { ACCEPT{ fx_mesher; fx_mesh; fx_group;} }
			BUTTON MOP_TOLEVELSET_MESH_SELECTOR {}
			
			LINK   MOP_TOLEVELSET_TARGET { ACCEPT{ fx_liquid; fx_channel_levelset; fx_group;} }
			BUTTON MOP_TOLEVELSET_TARGET_SELECTOR {}
			
			IN_EXCLUDE MOP_TOLEVELSET_COPS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
				ACCEPT {  fx_channelop_coffee; fx_channelop_math; }
			}
			BUTTON MOP_TOLEVELSET_COPS_SELECTOR {}
			
			LINK	MOP_TOLEVELSET_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON	MOP_TOLEVELSET_DURATION_SELECTOR {SCALE_V; FIT_H;}
		}

		LONG MOP_TOLEVELSET_SHAPE
		{
			HIDDEN;
			CYCLE
			{
				MOP_TOLEVELSET_SHAPE_CUBE;
				MOP_TOLEVELSET_SHAPE_SPHERE;
				MOP_TOLEVELSET_SHAPE_TORUS;
				MOP_TOLEVELSET_SHAPE_CYLINDER;
				MOP_TOLEVELSET_SHAPE_CONE;
			}
			ANIM OFF;
		}
		BOOL MOP_TOLEVELSET_MERGE {}
		BOOL MOP_TOLEVELSET_INVERT {}		
		REAL MOP_TOLEVELSET_SPHERE_RADIUS {MIN 0.001; UNIT METER;  HIDDEN;}
		VECTOR MOP_TOLEVELSET_PRIMITIVE_SIZE {MIN 0.001 0.001 0.001; UNIT METER;HIDDEN;}
		REAL MOP_TOLEVELSET_INNER_RADIUS {MIN 0.01; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR G_MOP_TOLEVELSET_MESHIN {}

		LONG MOP_TOLEVELSET_LEVELSETQUALITY {MIN 1; MAX 3; PARENTID MOP_TOLEVELSET_MESH; CUSTOMGUI LONGSLIDER; }
		LONG MOP_TOLEVELSET_SAFESWEEP { MIN 0; PARENTID MOP_TOLEVELSET_MESH;}	
	}
}