#ifndef FX_MOP_SMOOTHING_H
#define FX_MOP_SMOOTHING_H

enum
{	
	FX_MOP_SMOOTHING_MESH = 1000,
	FX_MOP_SMOOTHING_MESH_SELECTOR,
	FX_MOP_SMOOTHING_DURATION,
	FX_MOP_SMOOTHING_DURATION_SELECTOR,
	FX_MOP_SMOOTHING_ITERATIONS,

	FX_MOP_SMOOTHING_DUMMY_

};

#endif