#ifndef FX_MESHER_H
#define FX_MESHER_H

enum
{
	ID_MESHER_DISPLAY = 2000,

	MESHER_RENDERONLY = 1000,
	MESHER_VOLUME,
	MESHER_TYPE = 1002,
		MESHER_TYPE_CUBES = 0,
		MESHER_TYPE_TETRA,
		MESHER_TYPE_TILES,
	MESHER_VOXELSIZE = 1003,
	MESHER_VOXELSIZE_RENDER,
	MESHER_CALCNORMALS,
	MESHER_OPTIMIZE,
	MESHER_ADVECTION,
	MESHER_ISOSURFACE,
	MESHER_SOLVER,
	MESHER_VOLUME_SELECTOR,
	MESHER_SOLVER_SELECTOR,
	MESHER_INTERPOLATION = 1012,
		MESHER_INTERPOLATION_LINEAR = 0,
		MESHER_INTERPOLATION_COSINE,
		MESHER_INTERPOLATION_CUBIC,
		MESHER_INTERPOLATION_HERMITE,
		MESHER_INTERPOLATION_QUADRATIC,
	MESHER_DISPLAY_PROPERTY = 1013,

	MESHER_DUMMY_
		
};

#endif