#ifndef fx_multivariance_H_
#define fx_multivariance_H_

enum
{
	FX_MULTIVARIANCE_RND_TYPE=1000,
			FX_MULTIVARIANCE_RND_RANDOM=0,
			FX_MULTIVARIANCE_RND_ROW,
			FX_MULTIVARIANCE_RND_NOISE,
			FX_MULTIVARIANCE_RND_INDEX,
			FX_MULTIVARIANCE_RND_EXCEPTION,
			FX_MULTIVARIANCE_RND_SERIES,
			FX_MULTIVARIANCE_RND_HEIGHT,
	FX_MULTIVARIANCE_SEED=1001,
	FX_MULTIVARIANCE_NUMBER,
	FX_MULTIVARIANCE_SERIESLEN,
	FX_MULTIVARIANCE_START,
	FX_MULTIVARIANCE_HEIGHT_G,
	FX_MULTIVARIANCE_HEIGHT_DISTRIBUTION,
	FX_MULTIVARIANCE_HEIGHT_MIN,
	FX_MULTIVARIANCE_HEIGHT_MAX,

	FX_MULTIVARIANCE_DUMMY
};

#endif