CONTAINER fx_mesher
{
	NAME fx_mesher;
	INCLUDE fx_force_base;
	INCLUDE fx_base_display;

	//Basic Tab
	GROUP ID_FORCE_BASE
	{			
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK MESHER_VOLUME { SCALE_H; ACCEPT{fx_channel_levelset; fx_volume;fx_surface_reconstruction;fx_csg; fx_group;}; }
			BUTTON MESHER_VOLUME_SELECTOR {SCALE_V; FIT_H;}

			LINK MESHER_SOLVER { ACCEPT{fx_fluid; fx_liquid; fx_group;}; }
			BUTTON MESHER_SOLVER_SELECTOR {SCALE_V; FIT_H;}
		}
		
		SEPARATOR{LINE;}

		LONG MESHER_TYPE
		{
			CYCLE
			{
				MESHER_TYPE_CUBES;
				MESHER_TYPE_TETRA;
				MESHER_TYPE_TILES;
			}
		}
		LONG MESHER_INTERPOLATION
		{
			CYCLE
			{
				MESHER_INTERPOLATION_LINEAR;
				MESHER_INTERPOLATION_COSINE;
				MESHER_INTERPOLATION_QUADRATIC;
				//MESHER_INTERPOLATION_CUBIC;
				MESHER_INTERPOLATION_HERMITE;
			}
		}

		SEPARATOR{LINE;}

		REAL MESHER_ISOSURFACE { MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER;}
		REAL MESHER_ADVECTION {MIN 0.0; MAX 1.0; STEP 0.001;}
		BOOL MESHER_RENDERONLY {}
		BOOL MESHER_CALCNORMALS {}
		//BOOL MESHER_OPTIMIZE {}
		
		REAL MESHER_VOXELSIZE {MIN 1.; HIDDEN;}
		REAL MESHER_VOXELSIZE_RENDER {MIN 1.; HIDDEN;}
	}
	GROUP FX_BASE_DISPLAYTAB
	{
		LINK MESHER_DISPLAY_PROPERTY { ACCEPT{fx_property_scalar; fx_property_state; fx_property_vector;} }
	}
}