#ifndef FX_MOP_TO_LEVELSET_H
#define FX_MOP_TO_LEVELSET_H

enum
{
	G_MOP_TOLEVELSET_MESHIN = 3000,

	MOP_TOLEVELSET_SHAPE = 1000,
		MOP_TOLEVELSET_SHAPE_CUBE = 0,
		MOP_TOLEVELSET_SHAPE_SPHERE,
		MOP_TOLEVELSET_SHAPE_ELLIPSOID,
		MOP_TOLEVELSET_SHAPE_TORUS,
		MOP_TOLEVELSET_SHAPE_CYLINDER,
		MOP_TOLEVELSET_SHAPE_CONE,
	MOP_TOLEVELSET_MESH = 1001,
	MOP_TOLEVELSET_MESH_SELECTOR,
	MOP_TOLEVELSET_SPHERE_RADIUS,
	MOP_TOLEVELSET_PRIMITIVE_SIZE,
	MOP_TOLEVELSET_INNER_RADIUS,
	MOP_TOLEVELSET_INVERT,
	MOP_TOLEVELSET_LEVELSETQUALITY,
	MOP_TOLEVELSET_SAFESWEEP,
	MOP_TOLEVELSET_TARGET,
	MOP_TOLEVELSET_TARGET_SELECTOR,
	MOP_TOLEVELSET_DURATION,
	MOP_TOLEVELSET_DURATION_SELECTOR,
	MOP_TOLEVELSET_COPS,
	MOP_TOLEVELSET_COPS_SELECTOR,
	MOP_TOLEVELSET_MERGE,

	MOP_TOLEVELSET_DUMMY_

};

#endif