#ifndef FX_MESH_H
#define FX_MESH_H

enum
{
	ID_FXMESH_DISPLAY = 2000,

	FXMESH_MESH = 1000,
	FXMESH_MESH_SELECTOR,
	FXMESH_DISPLAY_PROPERTY,
	FXMESH_DISPLAY_DRAW,
	FXMESH_MESHMOTION,
	FXMESH_DISPLAY_THRESHOLD,
	FXMESH_DISPLAY_PROPERTY_BRUSH,
	FXMESH_DISPLAY_THRESHOLD_BRUSH,
	FXMESH_DISPLAY_PROPERTY_SELECTOR,
	FXMESH_DISPLAY_PROPERTY_BRUSH_SELECTOR,

	FXMESH_QUICKTAB_OBSTACLE = 1100,
	FXMESH_QUICKTAB_VOLUME,
	FXMESH_QUICKTAB_CURVATURE,
	FXMESH_QUICKTAB_SMOOTHING,

	FXMESH_MESH_DUMMY_
		
};

#endif