CONTAINER fx_mesh
{
	NAME fx_mesh;
	INCLUDE fx_force_base;
	INCLUDE fx_base_display;

	GROUP FX_BASE_QUICKTAB
	{
		COLUMNS 4;
		BUTTON FXMESH_QUICKTAB_OBSTACLE {}
		BUTTON FXMESH_QUICKTAB_VOLUME {}
		BUTTON FXMESH_QUICKTAB_CURVATURE {}
		BUTTON FXMESH_QUICKTAB_SMOOTHING {HIDDEN;}
	}
	//Basic Tab
	GROUP ID_FORCE_BASE
	{			
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FXMESH_MESH { SCALE_H; ACCEPT{Obase;}; }
			BUTTON FXMESH_MESH_SELECTOR {SCALE_V; FIT_H;}
		}
		BOOL FXMESH_MESHMOTION {}
	}
	GROUP FX_BASE_DISPLAYTAB
	{
		BOOL FXMESH_DISPLAY_DRAW {}
		
		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			LINK FXMESH_DISPLAY_PROPERTY	{ ACCEPT{fx_property_scalar; fx_property_state; fx_property_vector; fx_group;} }
			BUTTON FXMESH_DISPLAY_PROPERTY_SELECTOR {SCALE_V; FIT_H;}

			REAL FXMESH_DISPLAY_THRESHOLD	{ MIN 0.001; STEP 0.1; }
			STATICTEXT { NEWLINE; }
			
			SEPARATOR { LINE; }
			STATICTEXT { NEWLINE; }
			
			LINK FXMESH_DISPLAY_PROPERTY_BRUSH { ACCEPT{fx_property_scalar; fx_property_vector; fx_group;} }
			BUTTON FXMESH_DISPLAY_PROPERTY_BRUSH_SELECTOR {SCALE_V; FIT_H;}
			REAL FXMESH_DISPLAY_THRESHOLD_BRUSH {MIN 0.001; STEP 0.1; }
		}
		

	}
}