#ifndef FX_MOP_VNORMALS_H
#define FX_MOP_VNORMALS_H

enum
{	
	FX_MOP_VNORMALS_MESH = 1000,
	FX_MOP_VNORMALS_MESH_SELECTOR,
	FX_MOP_VNORMALS_DURATION,
	FX_MOP_VNORMALS_DURATION_SELECTOR,

	FX_MOP_VNORMALS_DUMMY_

};

#endif