CONTAINER fx_obstacle_dynamic
{
	NAME fx_obstacle_dynamic;
	INCLUDE Tbase;
	
	GROUP ID_TAGPROPERTIES
	{
		DEFAULT 1;

		LINK DYNAMIC_OBSTACLE_VOLUME { ACCEPT{fx_volume; fx_group;} }

		REAL DYNAMIC_OBSTACLE_LINEARSTRENGTH { STEP 0.1; }
		REAL DYNAMIC_OBSTACLE_ANGULARSTRENGTH { STEP 0.1; }
	}
}