#ifndef FX_EMISSION_SETTINGS_FIRE_H
#define FX_EMISSION_SETTINGS_FIRE_H

enum
{
	DYNAMIC_OBSTACLE_VOLUME,
	DYNAMIC_OBSTACLE_LINEARSTRENGTH,
	DYNAMIC_OBSTACLE_ANGULARSTRENGTH,

	DYNAMIC_OBSTACLE_DUMMY_

};

#endif