#ifndef FX_PSHEET_H
#define FX_PSHEET_H

enum
{	
	ID_PSHEET_BASE = 2000,
	
	PSHEET_PARTICLES = 1000,
	PSHEET_RADIUS_DENSITY,
	PSHEET_ANISOTROPIC_RATE,
	PSHEET_CANDIDATES_MINDISTANCE,
	PSHEET_CANDIDATES_MAXDISTANCE_FINDING,
	PSHEET_CANDIDATES_MAXDISTANCE_INSERTION,
	PSHEET_CANDIDATES_MINDENSITY,
	PSHEET_CANDIDATES_MAXDENSITY,
	PSHEET_COLLAPSE_MAXDENSITY,
	PSHEET_COLLAPSE_MINDISTANCE,
	PSHEET_PARTICLES_SELECTOR,
	PSHEET_RECALCULATE_ANISOTROPY,

	PSHEET_INPUT_FACTORY = 1012,
		PSHEET_INPUT_FACTORY_PASSIVE = 0,
		PSHEET_INPUT_FACTORY_VORTICITY,
		PSHEET_INPUT_FACTORY_IMPLICIT,
		PSHEET_INPUT_FACTORY_DIFFUSE,
	PSHEET_DISTANCE_INCREASE = 1013,
	
	PSHEET_DUMMY_

};

#endif