CONTAINER fx_particlemeshemitter
{
	NAME fx_particlemeshemitter;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	
	GROUP FX_BASE_QUICKTAB
	{
		BUTTON PARTICLEMESHEMITTER_CONVERT_TO_BRUSHDATA {}
	}
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK PARTICLEMESHEMITTER_MESH { ACCEPT {  fx_volume; fx_mesh; fx_group;} }
			BUTTON PARTICLEMESHEMITTER_MESH_SELECTOR {}
			LINK PARTICLEMESHEMITTER_PARTICLEFACTORY { ACCEPT {  fx_particlegroup;  fx_group;} }
			BUTTON PARTICLEMESHEMITTER_PARTICLEFACTORY_SELECTOR {}
			
			LINK PARTICLEMESHEMITTER_SETTINGS { ACCEPT {  fx_particlemesh_emission_setting;  fx_group;} }
			BUTTON PARTICLEMESHEMITTER_SETTINGS_SELECTOR {}
			IN_EXCLUDE PARTICLEMESHEMITTER_PROPS
			{ 
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
				ACCEPT {  fx_property_scalar; fx_property_vector; fx_property_state; }; 
			}
			BUTTON PARTICLEMESHEMITTER_PROPS_SELECTOR {SCALE_V; FIT_H;}
		}
		LONG PARTICLEMESHEMITTER_PARTICLETYPE
		{
			CYCLE
			{
				PARTICLEMESHEMITTER_PARTICLETYPE_PASSIVE;
				PARTICLEMESHEMITTER_PARTICLETYPE_VORTICITY;
				PARTICLEMESHEMITTER_PARTICLETYPE_LIQUID;
				PARTICLEMESHEMITTER_PARTICLETYPE_DIFFUSE;
			}
		}
		LONG PARTICLEMESHEMITTER_SOURCETYPE
		{
			CYCLE
			{
				PARTICLEMESHEMITTER_SOURCETYPE_POLYGON;
				PARTICLEMESHEMITTER_SOURCETYPE_POINTS;
				PARTICLEMESHEMITTER_SOURCETYPE_BRUSH;
			}
		}
		BOOL PARTICLEMESHEMITTER_CALCVNORMALS {}
		BOOL PARTICLEMESHEMITTER_SAMPLING_NORANDOM {}
		REAL PARTICLEMESHEMITTER_SAMPLING_MINIMUM { MIN 0.0; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL PARTICLEMESHEMITTER_SPEED {MIN -10000.0; MAX 10000.0; MAXSLIDER 100.0; MINSLIDER -100.0;CUSTOMGUI REALSLIDER;}
		REAL PARTICLEMESHEMITTER_SPEED_JITTER {MIN 0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR PARTICLEMESHEMITTER_SEP_PROPERTIES {}

		BOOL PARTICLEMESHEMITTER_FILLPROP_UVW {}
		BOOL PARTICLEMESHEMITTER_FILLPROP_NORMAL {}
		BOOL PARTICLEMESHEMITTER_FILL_COLOR {}
		
		IN_EXCLUDE PARTICLEMESHEMITTER_PROPS_BRUSH
		{ 
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
			ACCEPT {  fx_property_scalar; fx_property_vector; }; 
		}

		SEPARATOR PARTICLEMESHEMITTER_SAMPLING {}
		
		LONG PARTICLEMESHEMITTER_MATERIALSPACE
		{
			CYCLE
			{
				PARTICLEMESHEMITTER_MATERIALSPACE_UV;
				PARTICLEMESHEMITTER_MATERIALSPACE_3D;
			}
		}
		LONG PARTICLEMESHEMITTER_POINTSPACE
		{
			CYCLE
			{
				PARTICLEMESHEMITTER_POINTSPACE_C4D;
				PARTICLEMESHEMITTER_POINTSPACE_PHYSICAL;
			}
		}
		SHADERLINK PARTICLEMESHEMITTER_COLORSHADER {}
		LONG PARTICLEMESHEMITTER_FILLPROP_COLOR
		{
			CYCLE
			{
				PARTICLEMESHEMITTER_FILLPROP_COLOR_OFF;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_COLOR;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_LUMINANCE;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_DIFFUSION;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_TRANSPARENCY;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_REFLECTION;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_ENVIRONMENT;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_BUMP;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_NORMAL;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_SPECCOLOR;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_GLOW;
				PARTICLEMESHEMITTER_FILLPROP_COLOR_DISPLACEMENT;
			}
		}
	}
	GROUP ID_FORCE_BASE_CONSTRAINTS
	{
		SEPARATOR {LINE;}

		SHADERLINK PARTICLEMESHEMITTER_CONSTRAINT_SHADER {}
		REAL PARTICLEMESHEMITTER_CONSTRAINT_SHADERTHRESHOLD { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }

		SEPARATOR {LINE;}

		BOOL PARTICLEMESHEMITTER_CONSTRAINT_CURVATURE {}
		REAL PARTICLEMESHEMITTER_CONSTRAINT_CURVATURETHRESHOLD { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
	}
}