CONTAINER fx_pforce_tension
{
	NAME fx_pforce_tension;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK PFORCE_TENSION_PARTICLES { ACCEPT { fx_particlegroup;  fx_group;} }
			BUTTON PFORCE_TENSION_PARTICLES_SELECTOR {}
			LINK PFORCE_TENSION_DYNAMICS { ACCEPT { fx_liquid;  fx_group;}}
			BUTTON PFORCE_TENSION_DYNAMICS_SELECTOR {}
		}

		LONG PFORCE_TENSION_INPUT_FACTORY
		{
			CYCLE
			{
				PFORCE_TENSION_INPUT_FACTORY_PASSIVE;
				PFORCE_TENSION_INPUT_FACTORY_VORTICITY;
				PFORCE_TENSION_INPUT_FACTORY_IMPLICIT;
				PFORCE_TENSION_INPUT_FACTORY_DIFFUSE;
			}
		}
				
		LONG PFORCE_TENSION_MODE	
		{
			CYCLE
			{
				PFORCE_TENSION_MODE_COHESION;
				PFORCE_TENSION_MODE_COLOR;
			}
		}
		REAL PFORCE_TENSION_K		{ MIN 0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER;}
		REAL PFORCE_TENSION_RADIUS	{ MIN 1; MAX 5; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL PFORCE_TENSION_MINDENSITY	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; HIDDEN; }
		REAL PFORCE_TENSION_MAXDENSITY	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; HIDDEN; }
	}
}
			