CONTAINER fx_particlegroup
{
	NAME fx_particlegroup;
	INCLUDE fx_force_base;
	INCLUDE fx_base_display;
	
	HIDE Obaselist;
	HIDE ID_BASEOBJECT_GROUP1;

	GROUP FX_BASE_QUICKTAB
	{
		COLUMNS 4;
		BUTTON FLUIDGROUP_QUICK_CREATE_ADVECTION { }
		BUTTON FLUIDGROUP_QUICK_CREATE_FORCES {}
		BUTTON FLUIDGROUP_QUICK_CREATE_MESHING {}
		BUTTON FLUIDGROUP_QUICK_CREATE_EMITTER {}

		BUTTON FLUIDGROUP_QUICK_CREATE_MESHCOLOR {}
		BUTTON FLUIDGROUP_QUICK_CREATE_THINSHEET {}
		BUTTON FLUIDGROUP_QUICK_CREATE_SURFACETENSION {}
		BUTTON FLUIDGROUP_QUICK_CREATE_TURBULENCE {}
	}
	GROUP ID_FORCE_BASE
	{
		REAL	FLUIDGROUP_PASSIVE_SIZE { MIN 0; UNIT METER;}
		REAL	FLUIDGROUP_LIQUID_SIZE { MIN 0; UNIT METER;}
		REAL	FLUIDGROUP_VORTICITY_SIZE { MIN 0; UNIT METER;}	

		REAL  FLUIDGROUP_FOAM_SIZE { MIN 0; UNIT METER;}
		REAL  FLUIDGROUP_SPRAY_SIZE { MIN 0; UNIT METER;}
		REAL  FLUIDGROUP_BUBBLE_SIZE { MIN 0; UNIT METER;}	
	}
	GROUP FX_BASE_DISPLAYTAB
	{
		DEFAULT 1;
		GROUP ID_FLUIDGROUP_PASSIVE
		{			
			LONG	FLUIDGROUP_PASSIVE_DRAW {MIN 0; MAX 100; }
			LONG	FLUIDGROUP_PASSIVE_DRAWSIZE
			{
				CYCLE
				{
					FLUIDGROUP_DRAWSIZE_MINI;
					FLUIDGROUP_DRAWSIZE_SMALL;
					FLUIDGROUP_DRAWSIZE_NORMAL;
				}
			}

			COLOR	FLUIDGROUP_PASSIVE_COLOR {}
			BOOL	FLUIDGROUP_PASSIVE_DEFORMED {}
			BOOL	FLUIDGROUP_PASSIVE_DRAWRADIUS {}
			BOOL	FLUIDGROUP_PASSIVE_DRAWRADIUS2D {}
			SEPARATOR {LINE;}
			GROUP
			{
				COLUMNS 2;
				LINK	FLUIDGROUP_PASSIVE_PROPERTY { ACCEPT{fx_property_scalar; fx_property_vector; fx_property_state;  fx_group;} }
				BUTTON  FLUIDGROUP_PASSIVE_PROPERTY_SELECTOR {SCALE_V; FIT_H;}
			}
			REAL	FLUIDGROUP_PASSIVE_THRESHOLD { MIN 0; }		
		}
		GROUP ID_FLUIDGROUP_VORTICITY
		{			
			LONG	FLUIDGROUP_VORTICITY_DRAW {MIN 0; MAX 100; }
			LONG	FLUIDGROUP_VORTICITY_DRAWSIZE
			{
				CYCLE
				{
					FLUIDGROUP_DRAWSIZE_MINI;
					FLUIDGROUP_DRAWSIZE_SMALL;
					FLUIDGROUP_DRAWSIZE_NORMAL;
				}
			}
			COLOR	FLUIDGROUP_VORTICITY_COLOR {}	
			BOOL	FLUIDGROUP_VORTICITY_DEFORMED {}	
			BOOL	FLUIDGROUP_VORTICITY_DRAWRADIUS {}
			BOOL	FLUIDGROUP_VORTICITY_DRAWRADIUS2D {}	
			SEPARATOR {LINE;}			
			GROUP
			{
				COLUMNS 2;
				LINK	FLUIDGROUP_VORTICITY_PROPERTY { ACCEPT{fx_property_scalar; fx_property_vector; fx_property_state;  fx_group;} }
				BUTTON  FLUIDGROUP_VORTICITY_PROPERTY_SELECTOR {SCALE_V; FIT_H;}
			}
			REAL	FLUIDGROUP_VORTICITY_THRESHOLD { MIN 0; }		
		}
		GROUP ID_FLUIDGROUP_LIQUID
		{
			DEFAULT 1;
			LONG	FLUIDGROUP_LIQUID_DRAW {MIN 0; MAX 100; }
			LONG	FLUIDGROUP_LIQUID_DRAWSIZE
			{
				CYCLE
				{
					FLUIDGROUP_DRAWSIZE_MINI;
					FLUIDGROUP_DRAWSIZE_SMALL;
					FLUIDGROUP_DRAWSIZE_NORMAL;
				}
			}
			COLOR	FLUIDGROUP_LIQUID_COLOR {}		
			BOOL	FLUIDGROUP_LIQUID_DEFORMED {}	
			BOOL	FLUIDGROUP_LIQUID_DRAWRADIUS {}
			BOOL	FLUIDGROUP_LIQUID_DRAWRADIUS2D {}
			SEPARATOR {LINE;}
			GROUP
			{
				COLUMNS 2;
				LINK	FLUIDGROUP_LIQUID_PROPERTY { ACCEPT{fx_property_scalar; fx_property_vector; fx_property_state;  fx_group;} }
				BUTTON  FLUIDGROUP_LIQUID_PROPERTY_SELECTOR {SCALE_V; FIT_H;}
			}
			REAL	FLUIDGROUP_LIQUID_VELTHRESHOLD { MIN 0; }
		}
		GROUP ID_FLUIDGROUP_FOAM
		{	
			LONG  FLUIDGROUP_FOAM_DRAW {MIN 0; MAX 100;}
			LONG	FLUIDGROUP_FOAM_DRAWSIZE
			{
				CYCLE
				{
					FLUIDGROUP_DRAWSIZE_MINI;
					FLUIDGROUP_DRAWSIZE_SMALL;
					FLUIDGROUP_DRAWSIZE_NORMAL;
				}
			}
			COLOR FLUIDGROUP_FOAM_COLOR {}
			BOOL  FLUIDGROUP_FOAM_DEFORMED {}
			REAL  FLUIDGROUP_FOAM_THRESHOLD { MIN 0; }			
		}
	}
}