#ifndef FX_PFORCE_CORRECT_H
#define FX_PFORCE_CORRECT_H

enum
{	
	ID_PFORCE_BASE = 2000,
	
	PFORCE_CORRECTOR_PARTICLES = 1000,
	PFORCE_CORRECTOR_DYNAMICS,
	PFORCE_CORRECTOR_SPRINGFORCE,
	PFORCE_CORRECTOR_PARTICLES_SELECTOR,
	PFORCE_CORRECTOR_DYNAMICS_SELECTOR,
	PFORCE_CORRECTOR_INPUT_FACTORY = 1005,
		PFORCE_CORRECTOR_INPUT_FACTORY_PASSIVE = 0,
		PFORCE_CORRECTOR_INPUT_FACTORY_VORTICITY,
		PFORCE_CORRECTOR_INPUT_FACTORY_IMPLICIT,
		PFORCE_CORRECTOR_INPUT_FACTORY_DIFFUSE,
	PFORCE_CORRECTOR_DURATION = 1006,
	PFORCE_CORRECTOR_DURATION_SELECTOR,
	PFORCE_CORRECTOR_SPACING,
	PFORCE_CORRECTOR_ITERATIONS,
	PFORCE_CORRECTOR_FORCERESAMPLING,
	PFORCE_CORRECTOR_BOUNDARYPARTICLE,

	PFORCE_CORRECTOR_DUMMY_

};

#endif