#ifndef FX_PARTICLEGRIDEMITTER_H
#define FX_PARTICLEGRIDEMITTER_H

enum
{
	PARTICLEGRIDEMITTER_PARTICLEFACTORY = 1000,
	PARTICLEGRIDEMITTER_PARTICLETYPE = 1001,
		PARTICLEGRIDEMITTER_PARTICLETYPE_PASSIVE = 0,
		PARTICLEGRIDEMITTER_PARTICLETYPE_VORTICITY,
		PARTICLEGRIDEMITTER_PARTICLETYPE_LIQUID,
		PARTICLEGRIDEMITTER_PARTICLETYPE_DIFFUSE,
	PARTICLEGRIDEMITTER_SEP_LOCATION = 1002,
	PARTICLEGRIDEMITTER_SETTINGS,
	PARTICLEGRIDEMITTER_PROPS,
	PARTICLEGRIDEMITTER_VOLUME,
	PARTICLEGRIDEMITTER_SOLVERS,
	PARTICLEGRIDEMITTER_CONSTRAINTS_EXACT,
	PARTICLEGRIDEMITTER_VOLUME_SELECTOR,
	PARTICLEGRIDEMITTER_PARTICLEFACTORY_SELECTOR,
	PARTICLEGRIDEMITTER_SETTINGS_SELECTOR,
	PARTICLEGRIDEMITTER_SEP_SAMPLING,
	PARTICLEGRIDEMITTER_PROPS_SELECTOR,
	PARTICLEGRIDEMITTER_PHI_MIN,
	PARTICLEGRIDEMITTER_PHI_MAX,
	PARTICLEGRIDEMITTER_GRIDSUBDIVISIONS_PHI,
	PARTICLEGRIDEMITTER_GRIDSUBDIVISIONS_MIN,
	PARTICLEGRIDEMITTER_GRIDSUBDIVISIONS_MAX,
	PARTICLEGRIDEMITTER_COLORSHADER,
	PARTICLEGRIDEMITTER_SAMPLING_MINIMUM,
	PARTICLEGRIDEMITTER_JITTER,
	PARTICLEGRIDEMITTER_SPEED,
	PARTICLEGRIDEMITTER_SPEED_JITTER,
	PARTICLEGRIDEMITTER_COLORMODE = 1023,
		PARTICLEGRIDEMITTER_COLORMODE_COLOR = 0,
		PARTICLEGRIDEMITTER_COLORMODE_SHADER,
		PARTICLEGRIDEMITTER_COLORMODE_CONSTRAINTS,
	PARTICLEGRIDEMITTER_COLOR = 1024,
	PARTICLEGRIDEMITTER_ALIGNMENT,
	PARTICLEGRIDEMITTER_ALIGNMENT_SELECTOR,
	PARTICLEGRIDEMITTER_DURATION,
	PARTICLEGRIDEMITTER_DURATION_SELECTOR,
		
	PARTICLEGRIDEMITTER_DUMMY_
};

#endif