#ifndef FX_PFORCE_COHESION_H
#define FX_PFORCE_COHESION_H

enum
{		
	PFORCE_COHESION_INTENSITY = 1000,
	PFORCE_COHESION_DURATION,
	PFORCE_COHESION_DURATION_SELECTOR,
	PFORCE_COHESION_RADIUS,
	
	PFORCE_COHESION_DUMMY_

};

#endif