#ifndef FX_PARTICLE_CONVERTER_H
#define FX_PARTICLE_CONVERTER_H

enum
{	
	PARTICLE_CONVERTER_TO_IMPLICITPARTICLES = 2000,
	PARTICLE_CONVERTER_TO_SIMPLEPARTICLES,
	PARTICLE_CONVERTER_TO_THINKINGPARTICLES,
	PARTICLE_CONVERTER_TO_PASSIVEPARTICLES,
	PARTICLE_CONVERTER_TO_VORTICITYPARTICLES,
	PARTICLE_CONVERTER_CONVERSION,

	PARTICLE_CONVERTER_INPUT = 1000,
	PARTICLE_CONVERTER_INPUT_FACTORY = 1001,
		PARTICLE_CONVERTER_INPUT_FACTORY_PASSIVE = 0,
		PARTICLE_CONVERTER_INPUT_FACTORY_VORTICITY,
		PARTICLE_CONVERTER_INPUT_FACTORY_IMPLICIT,
		PARTICLE_CONVERTER_INPUT_FACTORY_DIFFUSE,
	PARTICLE_CONVERTER_OUTPUT = 1002,
	PARTICLE_CONVERTER_OUTPUT_FACTORY = 1003,
		PARTICLE_CONVERTER_OUTPUT_FACTORY_PASSIVE = 0,
		PARTICLE_CONVERTER_OUTPUT_FACTORY_VORTICITY,
		PARTICLE_CONVERTER_OUTPUT_FACTORY_IMPLICIT,
		PARTICLE_CONVERTER_OUTPUT_FACTORY_DIFFUSE,
		PARTICLE_CONVERTER_OUTPUT_FACTORY_KILL = 100,

	PARTICLE_CONVERTER_CONSTRAINTS = 1004,
	PARTICLE_CONVERTER_ONLY_PARTICLE_LOCATION,
	PARTICLE_CONVERTER_CREATE,
	PARTICLE_CONVERTER_SAMPLES,
	PARTICLE_CONVERTER_SAMPLESVAR,
	
	PARTICLE_CONVERTER_TO_SIMPLEPARTICLES_VELOCITY,	
	PARTICLE_CONVERTER_TO_THINKINGPARTICLES_VELOCITY,	
	PARTICLE_CONVERTER_TO_PASSIVEPARTICLES_VELOCITY,
	PARTICLE_CONVERTER_TO_VORTICITYPARTICLES_ALIGNMENT,
	PARTICLE_CONVERTER_TO_IMPLICITPARTICLES_ACCELERATION,
	PARTICLE_CONVERTER_PROPERTIES,
	PARTICLE_CONVERTER_INPUT_SELECTOR,
	PARTICLE_CONVERTER_OUTPUT_SELECTOR,
	PARTICLE_CONVERTER_SAMPLES_SELECTOR,
	PARTICLE_CONVERTER_PROPERTIES_SELECTOR,
	PARTICLE_CONVERTER_EXTERNAL_FILL,
	PARTICLE_CONVERTER_SAMPLERADIUS,
	PARTICLE_CONVERTER_SAMPLERADIUS_VAR,

	PARTICLE_CONVERTER_DUMMY_
};

#endif