CONTAINER fx_pop_flock
{	
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	NAME fx_pop_flock;
	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2; 
			LINK POP_FLOCK_BOIDS  { SCALE_H; ACCEPT{fx_particlegroup; fx_group;}}
			BUTTON POP_FLOCK_BOIDS_SELECTOR {SCALE_V; FIT_H;}
			
			LINK POP_FLOCK_PREDATORS  { SCALE_H; ACCEPT{fx_particlegroup; fx_group;}}
			BUTTON POP_FLOCK_PREDATORS_SELECTOR {SCALE_V; FIT_H;}

			//LINK POP_FLOCK_LEADER  { SCALE_H; ACCEPT{fx_particlegroup; Obase;}}
			//BUTTON POP_FLOCK_LEADER_SELECTOR {SCALE_V; FIT_H;}
			
			LINK POP_FLOCK_DURATION { ACCEPT { fx_duration; fx_group; }}
			BUTTON POP_FLOCK_DURATION_SELECTOR {SCALE_V; FIT_H;}
		}
		
		GROUP POP_FLOCK_BOIDS_SUB
		{
			COLUMNS 2;
			DEFAULT 1;
		
			LONG POP_FLOCK_BOIDS_FACTORY
			{
				CYCLE
				{
					POP_FLOCK_BOIDS_FACTORY_PASSIVE;
					POP_FLOCK_BOIDS_FACTORY_VORTICITY;
					POP_FLOCK_BOIDS_FACTORY_IMPLICIT;
					POP_FLOCK_BOIDS_FACTORY_DIFFUSE;
				}
			}
			REAL POP_FLOCK_MAXVELOCITY { MIN 0.1; STEP 0.1;}
			REAL POP_FLOCK_COHESION { MIN 0.0; MAX 100.0; MAXSLIDER 1000; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}
			REAL POP_FLOCK_COHESION_RADIUS { MIN 0.1; MAX 100.0; STEP 0.1;}
			REAL POP_FLOCK_SEPARATION { MIN 0.0; MAX 100.0; MAXSLIDER 1000; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}
			REAL POP_FLOCK_SEPARATION_RADIUS { MIN 0.1; MAX 100.0;  STEP 0.1; }
			REAL POP_FLOCK_ALIGNMENT { MIN 0.0; MAX 100.0; MAXSLIDER 1000; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}
			REAL POP_FLOCK_ALIGNMENT_RADIUS { MIN 0.1; MAX 100.0;  STEP 0.1; }
			REAL POP_FLOCK_FLEE { MIN 0.0; MAX 100.0; MAXSLIDER 1000; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H;}
			REAL POP_FLOCK_FLEE_RADIUS { MIN 0.1; MAX 100.0;  STEP 0.1; }
		}
		GROUP POP_FLOCK_PREDATORS_SUB
		{
			COLUMNS 2;
			DEFAULT 1;
		
			LONG POP_FLOCK_PREDATORS_FACTORY
			{
				CYCLE
				{
					POP_FLOCK_PREDATORS_FACTORY_PASSIVE;
					POP_FLOCK_PREDATORS_FACTORY_VORTICITY;
					POP_FLOCK_PREDATORS_FACTORY_IMPLICIT;
					POP_FLOCK_PREDATORS_FACTORY_DIFFUSE;
				}
			}
			REAL POP_FLOCK_PREDATORS_MAXVELOCITY { MIN 0.1;  STEP 0.1;}
			REAL POP_FLOCK_PREDATORS_COHESION { MIN 0.0; MAX 200.0; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H; }
			REAL POP_FLOCK_PREDATORS_COHESION_RADIUS { MIN 0.1; MAX 100.0; STEP 0.1; }
			REAL POP_FLOCK_PREDATORS_SEPARATION { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; SCALE_H; }
			REAL POP_FLOCK_PREDATORS_SEPARATION_RADIUS { MIN 0.1; MAX 100.0; STEP 0.1; }
			BOOL POP_FLOCK_PREDATORS_EATPREY {}
			REAL POP_FLOCK_PREDATORS_EATPREY_RADIUS { MIN 0.1; MAX 100.0; STEP 0.1; }
		}
		//SEPARATOR {LINE;}
		//LONG POP_FLOCK_LEADERS_FACTORY
		//{
		//	CYCLE
		//	{
		//		POP_FLOCK_LEADERS_FACTORY_PASSIVE;
		//		POP_FLOCK_LEADERS_FACTORY_VORTICITY;
		//		POP_FLOCK_LEADERS_FACTORY_IMPLICIT;
		//		POP_FLOCK_LEADERS_FACTORY_DIFFUSE;
		//	}
		//}
	}
	GROUP ID_FORCE_BASE_CONSTRAINTS_SUB
	{
	}
}