CONTAINER fx_particlemesh_emission_setting
{
	NAME fx_particlemesh_emission_setting;
	INCLUDE fx_force_base;
	
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;

		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK PARTICLEMESH_EMISSION_SETTINGS_RATE { ACCEPT{fx_rate; fx_group;}}
			BUTTON PARTICLEMESH_EMISSION_SETTINGS_RATE_SELECTOR {}
			LINK PARTICLEMESH_EMISSION_SETTINGS_ALIGNMENT { ACCEPT{fx_alignment; fx_group;}}
			BUTTON PARTICLEMESH_EMISSION_SETTINGS_ALIGNMENT_SELECTOR {}
			LINK PARTICLEMESH_EMISSION_SETTINGS_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON PARTICLEMESH_EMISSION_SETTINGS_DURATION_SELECTOR {}
		}

		LONG PARTICLEMESH_EMISSION_SETTINGS_RATEVALUE {MIN 1; }
		BOOL PARTICLEMESH_EMISSION_SETTINGS_PERFRAME {}
		
		SPLINE PARTICLEMESH_EMISSION_SETTINGS_TEMPORAL_INTENSITY { SHOWGRID_H; X_MIN 0; X_MAX 1; Y_MIN 0; Y_MAX 1; X_STEPS 0.01; Y_STEPS 0.01; }		
				
		REAL PARTICLEMESH_EMISSION_SETTINGS_SPEED {MIN -10000.0; MAX 10000.0; MAXSLIDER 100.0; MINSLIDER -100.0;CUSTOMGUI REALSLIDER;}
		REAL PARTICLEMESH_EMISSION_SETTINGS_JITTER {MIN 0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
	}
}