#ifndef FX_PARTICLEGROUP_H
#define FX_PARTICLEGROUP_H

enum
{	
	ID_FLUIDGROUP_PASSIVE = 3000,
	ID_FLUIDGROUP_LIQUID,
	ID_FLUIDGROUP_VORTICITY,
	ID_FLUIDGROUP_FOAM,

	FLUIDGROUP_PASSIVE_COLOR = 1000,	
	FLUIDGROUP_LIQUID_COLOR = 1004,		
	FLUIDGROUP_VORTICITY_COLOR = 1013,	
	FLUIDGROUP_FOAM_COLOR = 1017,
	FLUIDGROUP_PASSIVE_DRAW = 1027,
	FLUIDGROUP_VORTICITY_DRAW,
	FLUIDGROUP_LIQUID_DRAW,
	FLUIDGROUP_FOAM_DRAW,

	FLUIDGROUP_PASSIVE_SIZE,
	FLUIDGROUP_VORTICITY_SIZE,
	FLUIDGROUP_LIQUID_SIZE,
	FLUIDGROUP_FOAM_SIZE,
	
	FLUIDGROUP_LIQUID_VELTHRESHOLD = 1050,	

	FLUIDGROUP_SPRAY_SIZE = 1062,
	FLUIDGROUP_BUBBLE_SIZE,
		
	FLUIDGROUP_PASSIVE_PROPERTY,
	FLUIDGROUP_LIQUID_PROPERTY,
	FLUIDGROUP_VORTICITY_PROPERTY = 1066,

	FLUIDGROUP_PASSIVE_THRESHOLD = 1071,
	FLUIDGROUP_VORTICITY_THRESHOLD,
	FLUIDGROUP_FOAM_THRESHOLD,

	FLUIDGROUP_PASSIVE_PROPERTY_SELECTOR,
	FLUIDGROUP_LIQUID_PROPERTY_SELECTOR,
	FLUIDGROUP_VORTICITY_PROPERTY_SELECTOR,
		
	FLUIDGROUP_PASSIVE_DEFORMED,
	FLUIDGROUP_VORTICITY_DEFORMED,
	FLUIDGROUP_LIQUID_DEFORMED,
	FLUIDGROUP_FOAM_DEFORMED,
		
	FLUIDGROUP_PASSIVE_DRAWRADIUS,
	FLUIDGROUP_PASSIVE_DRAWRADIUS2D,
	FLUIDGROUP_VORTICITY_DRAWRADIUS,
	FLUIDGROUP_VORTICITY_DRAWRADIUS2D,
	FLUIDGROUP_LIQUID_DRAWRADIUS,
	FLUIDGROUP_LIQUID_DRAWRADIUS2D,
	
	FLUIDGROUP_PASSIVE_DRAWSIZE = 1087,
		FLUIDGROUP_DRAWSIZE_MINI = 0,
		FLUIDGROUP_DRAWSIZE_SMALL,
		FLUIDGROUP_DRAWSIZE_NORMAL,
	FLUIDGROUP_VORTICITY_DRAWSIZE = 1088,
	FLUIDGROUP_LIQUID_DRAWSIZE,
	FLUIDGROUP_FOAM_DRAWSIZE,
			
	//Quicktab
	FLUIDGROUP_QUICK_CREATE_ADVECTION = 1150,
	FLUIDGROUP_QUICK_CREATE_FORCES,
	FLUIDGROUP_QUICK_CREATE_MESHING,
	FLUIDGROUP_QUICK_CREATE_EMITTER,
	FLUIDGROUP_QUICK_CREATE_MESHCOLOR,
	FLUIDGROUP_QUICK_CREATE_THINSHEET,
	FLUIDGROUP_QUICK_CREATE_SURFACETENSION,
	FLUIDGROUP_QUICK_CREATE_TURBULENCE,

	FLUIDGROUP_DUMMY_

};

#endif