CONTAINER fx_particle_forces
{
	NAME fx_particle_forces;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LONG PARTICLE_FORCES_PARTICLES_MODE
			{
				CYCLE
				{
					PARTICLE_FORCES_PARTICLES_MODE_INCLUDE;
					PARTICLE_FORCES_PARTICLES_MODE_EXCLUDE;
				}
			} STATICTEXT { JOINEND;}
			IN_EXCLUDE PARTICLE_FORCES_PARTICLES
			{
				SEND_SELCHNGMSG 1;
				NUM_FLAGS 4; 
				INIT_STATE 2;
				SCALE_H;
				IMAGE_01_ON 1024284;
				IMAGE_01_OFF 1024283;
				IMAGE_02_ON 1024285;
				IMAGE_02_OFF 1024283;
				IMAGE_03_ON 1024286;
				IMAGE_03_OFF 1024283;
				IMAGE_04_ON 1024287;
				IMAGE_04_OFF 1024283;
				ACCEPT { fx_particlegroup;}; //1001381; 1027133; Obase; Oparticle;				
			}
			BUTTON PARTICLE_FORCES_PARTICLES_SELECTOR {SCALE_V; FIT_H;}
			IN_EXCLUDE PARTICLE_FORCES_FORCES
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
				ACCEPT { fx_force_curl; fx_force_plugin; fx_pforce_acceleration; fx_pforce_coffee; fx_force_vortex; fx_force_trigowave; fx_force_buoyancy; }
			}
			BUTTON PARTICLE_FORCES_FORCES_SELECTOR {SCALE_V;FIT_H;}
			LINK	PARTICLE_FORCES_PROPERTY {ACCEPT{fx_property_vector; fx_group;}}
			BUTTON	PARTICLE_FORCES_PROPERTY_SELECTOR {SCALE_V; FIT_H;}

			LINK	PARTICLE_FORCES_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON	PARTICLE_FORCES_DURATION_SELECTOR {SCALE_V; FIT_H;}		
		}		
		BOOL PARTICLE_FORCES_TIMEINTEGRATED {}
		LONG PARTICLE_FORCES_MODE
		{
			CYCLE
			{
				PARTICLE_FORCES_MODE_ADD;
				PARTICLE_FORCES_MODE_SET;
			}
		}
	}
}
			