#ifndef FX_POP_DEFORM_H
#define FX_POP_DEFORM_H

enum
{	
	POP_DEFORM_PARTICLES = 1000,
	POP_DEFORM_DURATION = 1001,
	POP_DEFORM_PROPERTY,
	POP_DEFORM_MODE = 1003,
		POP_DEFORM_MODE_ADD = 0,
		POP_DEFORM_MODE_SET,
	POP_DEFORM_TIMEINTEGRATED = 1004,
	POP_DEFORM_INPUT_FACTORY = 1005,
		POP_DEFORM_INPUT_FACTORY_PASSIVE = 0,
		POP_DEFORM_INPUT_FACTORY_VORTICITY,
		POP_DEFORM_INPUT_FACTORY_IMPLICIT,
		POP_DEFORM_INPUT_FACTORY_DIFFUSE,
	POP_DEFORM_BLEND = 1006,
	POP_DEFORM_ALLOWPOLYGONS,

	//SELECTORS
	POP_DEFORM_PARTICLES_SELECTOR = 1100,
	POP_DEFORM_DURATION_SELECTOR,
	POP_DEFORM_PROPERTY_SELECTOR,
		
	POP_DEFORM_DUMMY_

};

#endif