CONTAINER fx_particle_deform
{
	NAME fx_particle_deform;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK POP_DEFORM_PARTICLES { ACCEPT { fx_particlegroup; fx_group;} }
			BUTTON POP_DEFORM_PARTICLES_SELECTOR {SCALE_V; FIT_H;}

			LINK	POP_DEFORM_PROPERTY {ACCEPT{fx_property_vector; fx_group;}}
			BUTTON	POP_DEFORM_PROPERTY_SELECTOR {SCALE_V; FIT_H;}

			LINK	POP_DEFORM_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON	POP_DEFORM_DURATION_SELECTOR {SCALE_V; FIT_H;}		
		}		
		BOOL POP_DEFORM_TIMEINTEGRATED {}
		BOOL POP_DEFORM_ALLOWPOLYGONS {}
		
		LONG POP_DEFORM_INPUT_FACTORY
		{
			CYCLE
			{
				POP_DEFORM_INPUT_FACTORY_PASSIVE;
				POP_DEFORM_INPUT_FACTORY_VORTICITY;
				POP_DEFORM_INPUT_FACTORY_IMPLICIT;
				POP_DEFORM_INPUT_FACTORY_DIFFUSE;
			}
		}
		LONG POP_DEFORM_MODE
		{
			CYCLE
			{
				POP_DEFORM_MODE_ADD;
				POP_DEFORM_MODE_SET;
			}
		}
		REAL POP_DEFORM_BLEND { MIN 0; MAX 100; CUSTOMGUI REALSLIDER; UNIT PERCENT;}
	}
}
			