CONTAINER fx_pop_followspline
{
	NAME fx_pop_followspline;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK	POP_FOLLOWSPLINE_SPLINE {ACCEPT{Obase; }}
			BUTTON	POP_FOLLOWSPLINE_SPLINE_SELECTOR {SCALE_V; FIT_H;}
			IN_EXCLUDE POP_FOLLOWSPLINE_PARTICLES
			{
				SEND_SELCHNGMSG 1;
				NUM_FLAGS 4; 
				INIT_STATE 2;
				SCALE_H;
				IMAGE_01_ON 1024284;
				IMAGE_01_OFF 1024283;
				IMAGE_02_ON 1024285;
				IMAGE_02_OFF 1024283;
				IMAGE_03_ON 1024286;
				IMAGE_03_OFF 1024283;
				IMAGE_04_ON 1024287;
				IMAGE_04_OFF 1024283;
				ACCEPT { fx_particlegroup;}; //1001381; 1027133; Obase; Oparticle;				
			}
			BUTTON POP_FOLLOWSPLINE_PARTICLES_SELECTOR {SCALE_V; FIT_H;}

			LINK	POP_FOLLOWSPLINE_PROPERTY {ACCEPT{fx_property_vector; fx_group;}}
			BUTTON	POP_FOLLOWSPLINE_PROPERTY_SELECTOR {SCALE_V; FIT_H;}

			LINK	POP_FOLLOWSPLINE_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON	POP_FOLLOWSPLINE_DURATION_SELECTOR {SCALE_V; FIT_H;}
		}

		SEPARATOR {LINE;}

		GROUP
		{
			DEFAULT 1; COLUMNS 2;
			LONG POP_FOLLOWSPLINE_STEERMODE
			{
				CYCLE
				{
					POP_FOLLOWSPLINE_STEERMODE_NEAREST;
					POP_FOLLOWSPLINE_STEERMODE_NEARESTVERTEX;
					POP_FOLLOWSPLINE_STEERMODE_VERTEX;
					POP_FOLLOWSPLINE_STEERMODE_PERCENT;
					POP_FOLLOWSPLINE_STEERMODE_RANDOM;
				}
			}	
			LONG POP_FOLLOWSPLINE_STEERVERTEX { MIN 0; }
			REAL POP_FOLLOWSPLINE_STEERPERCENT { HIDDEN; MIN 0; MAX 100; UNIT PERCENT;}

			LONG POP_FOLLOWSPLINE_STEERMODE_SEGMENT
			{
				CYCLE
				{
					POP_FOLLOWSPLINE_STEERMODE_SEGMENT_RANDOM;
					POP_FOLLOWSPLINE_STEERMODE_SEGMENT_SEQUENTIAL;
					POP_FOLLOWSPLINE_STEERMODE_SEGMENT_INDEX;
				}
			}
			LONG POP_FOLLOWSPLINE_STEERSEGMENT { MIN 1; }	
			REAL POP_FOLLOWSPLINE_STEERDISTANCE	{ MIN 0.001; STEP 0.1; UNIT METER;}
		}
		GROUP POP_FOLLOWSPLINE_STEER
		{
			DEFAULT 1;

			BOOL POP_FOLLOWSPLINE_STEERMAXORIGVEL {}
			REAL POP_FOLLOWSPLINE_STEERMAXVELOCITY{ MIN 0; MAXSLIDER 100; UNIT METER;}

			REAL POP_FOLLOWSPLINE_STEERACUTENESS	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL POP_FOLLOWSPLINE_STEERINTENSITY	{ MIN 0; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		}
		GROUP POP_FOLLOWSPLINE_FOLLOW
		{
			DEFAULT 1; COLUMNS 2;

			REAL POP_FOLLOWSPLINE_FOLLOWPOSITION	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL POP_FOLLOWSPLINE_FOLLOWPOSITION_RND { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL POP_FOLLOWSPLINE_FOLLOWDISTANCE	{ MIN 0.01; STEP 1; UNIT METER; CUSTOMGUI REALSLIDER; MAXSLIDER 500;}
			REAL POP_FOLLOWSPLINE_FOLLOWDISTANCE_RND { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL POP_FOLLOWSPLINE_FOLLOWROTATIONHULL { MIN -360; MAX 360; UNIT DEGREE; CUSTOMGUI REALSLIDER; SCALE_H;}
			REAL POP_FOLLOWSPLINE_FOLLOWROTATIONHULL_RND { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL POP_FOLLOWSPLINE_FOLLOWROTATION	{ MIN -360; MAX 360; UNIT DEGREE; CUSTOMGUI REALSLIDER; SCALE_H;}
			REAL POP_FOLLOWSPLINE_FOLLOWROTATION_RND { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL POP_FOLLOWSPLINE_FOLLOWROTATIONANGLE { MIN 0; MAX 360; UNIT DEGREE; CUSTOMGUI REALSLIDER; SCALE_H;}
			REAL POP_FOLLOWSPLINE_FOLLOWROTATIONANGLE_RND { MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }

			LONG POP_FOLLOWSPLINE_FOLLOWLOOP
			{
				CYCLE
				{
					POP_FOLLOWSPLINE_FOLLOWLOOP_RESTART;
					POP_FOLLOWSPLINE_FOLLOWLOOP_LOOP;
					POP_FOLLOWSPLINE_FOLLOWLOOP_END;
				}
			}
			LONG POP_FOLLOWSPLINE_FOLLOWMODE
			{
				CYCLE
				{
					POP_FOLLOWSPLINE_FOLLOWMODE_FORWARD;
					POP_FOLLOWSPLINE_FOLLOWMODE_BACKWARD;
				}
			}
			LONG POP_FOLLOWSPLINE_FOLLOWSPEED
			{
				CYCLE
				{
					POP_FOLLOWSPLINE_FOLLOWSPEED_PARTICLE;
					POP_FOLLOWSPLINE_FOLLOWSPEED_SPECIFIC;
					POP_FOLLOWSPLINE_FOLLOWSPEED_LENGTH;
				}
			}
			REAL POP_FOLLOWSPLINE_FOLLOWINTENSITY	{ MIN 0; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;SCALE_H;}
			REAL POP_FOLLOWSPLINE_FOLLOWSPEEDCUSTOM	{ MIN 0; MAXSLIDER 100; UNIT METER; CUSTOMGUI REALSLIDER;SCALE_H;}
			LONG POP_FOLLOWSPLINE_FOLLOWSPEEDFRAMES	{ MIN 1; MAXSLIDER 100; CUSTOMGUI LONGSLIDER;SCALE_H;}
		}		
	}
}