#ifndef FX_PARTICLE_ADVECTION_H
#define FX_PARTICLE_ADVECTION_H

enum
{	
	FX_PARTICLEADVECTION_PARTICLES = 1000,
	FX_PARTICLEADVECTION_PARTICLES_SELECTOR,
	FX_PARTICLEADVECTION_OPERATORS,
	FX_PARTICLEADVECTION_OPERATORS_SELECTOR,
	FX_PARTICLEADVECTION_DYNAMICS,
	FX_PARTICLEADVECTION_DYNAMICS_SELECTOR,
	FX_PARTICLEADVECTION_DYNAMICS_MODE = 1007,
		FX_PARTICLEADVECTION_DYNAMICS_MODE_INCLUDE = 0,
		FX_PARTICLEADVECTION_DYNAMICS_MODE_EXCLUDE,
	FX_PARTICLEADVECTION_MODE = 1008,
		FX_PARTICLEADVECTION_MODE_OFF = 0,
		FX_PARTICLEADVECTION_MODE_DYNAMIC,
		FX_PARTICLEADVECTION_MODE_PROJECTILE,
		FX_PARTICLEADVECTION_MODE_DYNAMIC_PROJECTILE,
	FX_PARTICLEADVECTION_INTEGRATOR = 1009,
		FX_PARTICLEADVECTION_INTEGRATOR_EULER1ST = 0,
		FX_PARTICLEADVECTION_INTEGRATOR_RUNGA2ND,
		FX_PARTICLEADVECTION_INTEGRATOR_RUNGA3RD,
		FX_PARTICLEADVECTION_INTEGRATOR_RUNGA4TH,
	FX_PARTICLEADVECTION_INTEGRATOR_BALLISTIC = 1010,
		FX_PARTICLEADVECTION_INTEGRATOR_BALLISTIC_EULER = 0,
		FX_PARTICLEADVECTION_INTEGRATOR_BALLISTIC_VERLET,
		FX_PARTICLEADVECTION_INTEGRATOR_BALLISTIC_PBF,
	FX_PARTICLEADVECTION_COLLISIONS = 1011,
		FX_PARTICLEADVECTION_COLLISIONS_OFF = 0,
		FX_PARTICLEADVECTION_COLLISIONS_VOLUMES,
		FX_PARTICLEADVECTION_COLLISIONS_DYNAMICSBOUNDARY,
	FX_PARTICLEADVECTION_KILLOUTSIDE = 1012,
	FX_PARTICLEADVECTION_SUBSTEPS,
	FX_PARTICLEADVECTION_INPUT_FACTORY = 1014,
		FX_PARTICLEADVECTION_INPUT_FACTORY_PASSIVE = 0,
		FX_PARTICLEADVECTION_INPUT_FACTORY_VORTICITY,
		FX_PARTICLEADVECTION_INPUT_FACTORY_IMPLICIT,
		FX_PARTICLEADVECTION_INPUT_FACTORY_DIFFUSE,
	FX_PARTICLEADVECTION_MARGIN	= 1015,
	FX_PARTICLEADVECTION_TIMESTEP,

	FX_PARTICLEADVECTION_END
};

#endif