#ifndef FX_PROPERTY_H
#define FX_PROPERTY_H

enum
{
	ID_PROPERTY_GROUP = 2000,
	PROPERTY_TYPE = 2001,
		PROPERTY_TYPE_RADIUS = 0,
		PROPERTY_TYPE_BIRTH,
		PROPERTY_TYPE_AGE,
		PROPERTY_TYPE_DENSITY,
		PROPERTY_TYPE_VISCOSITY,
		PROPERTY_TYPE_PRESSURE,
		PROPERTY_TYPE_TEMPERATURE,
		PROPERTY_TYPE_FIRE,
		PROPERTY_TYPE_FUEL,
		PROPERTY_TYPE_MASS,
		PROPERTY_TYPE_ISODENSITY,

		PROPERTY_TYPE_SHEET_TEMPDENSITY,
		PROPERTY_TYPE_SHEET_MATRIXFACTOR,

		PROPERTY_TYPE_CURVATURE,
		PROPERTY_TYPE_SMOKE,
		PROPERTY_TYPE_HELICITY,

		PROPERTY_TYPE_COLOR = 25,
		PROPERTY_TYPE_HFFLIP,
		PROPERTY_TYPE_CORRECTOR_POS,
		PROPERTY_TYPE_CORRECTOR_VEL,
		PROPERTY_TYPE_SHEET_WEIGHTEDPOS,
		PROPERTY_TYPE_SHEET_MATRIXX,
		PROPERTY_TYPE_SHEET_MATRIXY,
		PROPERTY_TYPE_SHEET_MATRIXZ,
		PROPERTY_TYPE_SHEET_EIGENVALUE,
		PROPERTY_TYPE_NORMAL,
		PROPERTY_TYPE_TENSION,
		PROPERTY_TYPE_POSITION_OLD,
		PROPERTY_TYPE_VELOCITY,
		PROPERTY_TYPE_VORTICITY,
		PROPERTY_TYPE_EXTERNAL_FORCE,
		PROPERTY_TYPE_POSITION,
		PROPERTY_TYPE_POSITION_OLDFRAME,
		PROPERTY_TYPE_POSITION_TARGET,
		PROPERTY_TYPE_POSITION_FOLLOWPSS, //Percent,Segment,Speed
		PROPERTY_TYPE_POSITION_FOLLOWOFFSET,
		PROPERTY_TYPE_UVW,
		PROPERTY_TYPE_GEOMETRY_RANDOMSCALE,
		PROPERTY_TYPE_GEOMETRY_RANDOM,
		PROPERTY_TYPE_POSITION_DEFORMED,

		PROPERTY_TYPE_STATE = 50,
		PROPERTY_TYPE_ID,
				
		PROPERTY_TYPE_CUSTOM = 75,
		PROPERTY_TYPE_CUSTOMVECTOR,
		PROPERTY_TYPE_CUSTOMSTATE,

		PROPERTY_TYPE_ANY = 200

};

#endif