CONTAINER fx_psurfaceproperty
{
	NAME fx_psurfaceproperty;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK PSURFACEPROPERTY_PARTICLES { ACCEPT { fx_particlegroup;  fx_group;} }
			BUTTON PSURFACEPROPERTY_PARTICLES_SELECTOR {}
			LONG PSURFACEPROPERTY_INPUT_FACTORY
			{
				CYCLE
				{
					PSURFACEPROPERTY_INPUT_FACTORY_PASSIVE;
					PSURFACEPROPERTY_INPUT_FACTORY_VORTICITY;
					PSURFACEPROPERTY_INPUT_FACTORY_IMPLICIT;
					PSURFACEPROPERTY_INPUT_FACTORY_DIFFUSE;
				}
			} STATICTEXT {}
		}		

		LONG PSURFACEPROPERTY_CURVATURE 
		{
			CYCLE
			{				
				PSURFACEPROPERTY_CURVATURE_OFF;
				PSURFACEPROPERTY_CURVATURE_SIMPLE;
				PSURFACEPROPERTY_CURVATURE_DIRECT;
				PSURFACEPROPERTY_CURVATURE_NORMALISED;
			}
		}
		BOOL PSURFACEPROPERTY_NORMAL {}
		BOOL PSURFACEPROPERTY_ANISOTROPY {}

		SEPARATOR {LINE;}

		REAL PSURFACEPROPERTY_RADIUSGLOBAL	{ MIN 0.0; MAXSLIDER 5; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL PSURFACEPROPERTY_MINDENSITY	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		REAL PSURFACEPROPERTY_MAXDENSITY	{ MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

		SEPARATOR SEP_PSURFACEPROPERTY_NORMAL { }
		
		LONG PSURFACEPROPERTY_KERNEL
		{
			CYCLE
			{
				PSURFACEPROPERTY_KERNEL_SMOOTH;
				PSURFACEPROPERTY_KERNEL_SPIKEY;
				PSURFACEPROPERTY_KERNEL_POLY6;
			}
		}
		REAL PSURFACEPROPERTY_RADIUS		{ MIN 0.5; MAXSLIDER 5; STEP 0.1; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR SEP_PSURFACEPROPERTY_CURVATURE { }
		REAL PSURFACEPROPERTY_RADIUS_CURVATURE	{ MIN 0.5; MAXSLIDER 5; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL PSURFACEPROPERTY_MAXCURVATURE	{ MIN 0.5; }
		
		SEPARATOR SEP_PSURFACEPROPERTY_ANISOTROPIC { }
		REAL PSURFACEPROPERTY_RADIUS_ANISOTROPY	{ MIN 0.5; MAXSLIDER 5; STEP 0.1; CUSTOMGUI REALSLIDER;}
	}
}
			