#ifndef FX_PFORCE_ACCELERATION_H
#define FX_PFORCE_ACCELERATION_H

enum
{		
	PFORCE_ACCELERATION_ALIGNMENT = 1000,
	PFORCE_ACCELERATION_INTENSITY,
	PFORCE_ACCELERATION,
	PFORCE_ACCELERATION_MIX,
	PFORCE_ACCELERATION_ALIGNMENT_SELECTOR,
	PFORCE_ACCELERATION_DURATION,
	PFORCE_ACCELERATION_DURATION_SELECTOR,
	
	PFORCE_ACCELERATION_DUMMY_

};

#endif