CONTAINER fx_pvaluetoproperty
{
	NAME fx_pvaluetoproperty;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK PVALUETOPROPERTY_PARTICLES { ACCEPT { fx_particlegroup; fx_group; } }
			BUTTON PVALUETOPROPERTY_PARTICLES_SELECTOR {}
			LINK PVALUETOPROPERTY_KERNELNODE { ACCEPT { fx_kernel; fx_group; } }
			BUTTON PVALUETOPROPERTY_KERNELNODE_SELECTOR {}
		}

		LONG PVALUETOPROPERTY_INPUT_FACTORY
		{
			CYCLE
			{
				PVALUETOPROPERTY_INPUT_FACTORY_PASSIVE;
				PVALUETOPROPERTY_INPUT_FACTORY_VORTICITY;
				PVALUETOPROPERTY_INPUT_FACTORY_IMPLICIT;
				PVALUETOPROPERTY_INPUT_FACTORY_DIFFUSE;
			}
		}
		BOOL PVALUETOPROPERTY_DENSITY {}
		BOOL PVALUETOPROPERTY_ISODENSITY {}
		BOOL PVALUETOPROPERTY_WEIGHTEDPOS {}
		//BOOL PVALUETOPROPERTY_WEIGHTEDRAD {}

		SEPARATOR {LINE;}

		REAL PVALUETOPROPERTY_RADIUS { MIN 0.5; MAXSLIDER 5; STEP 0.1; CUSTOMGUI REALSLIDER;} //a2
		LONG PVALUETOPROPERTY_KERNEL
		{
			CYCLE
			{
				PVALUETOPROPERTY_KERNEL_GAUSS;
				PVALUETOPROPERTY_KERNEL_POLY6;
				PVALUETOPROPERTY_KERNEL_POLY6SMOOTH;
				PVALUETOPROPERTY_KERNEL_VISCOSITY;
				PVALUETOPROPERTY_KERNEL_SPIKEY;
				PVALUETOPROPERTY_KERNEL_SPIKEYSMOOTH;
				PVALUETOPROPERTY_KERNEL_SMOOTH;
				PVALUETOPROPERTY_KERNEL_SHARP;
				PVALUETOPROPERTY_KERNEL_WYVILL;
				PVALUETOPROPERTY_KERNEL_BLINN;
				PVALUETOPROPERTY_KERNEL_SPLINE;
				PVALUETOPROPERTY_KERNEL_POLYNOMIAL;
			}
		}
	}
}
			