CONTAINER fx_pforce_acceleration
{
	NAME fx_pforce_acceleration;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	INCLUDE fx_base_display_inspector;

	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;

			LINK PFORCE_ACCELERATION_ALIGNMENT { ACCEPT {fx_alignment; fx_group;}; SCALE_H; }	
			BUTTON PFORCE_ACCELERATION_ALIGNMENT_SELECTOR { ALIGN_LEFT; FIT_H; }
			LINK PFORCE_ACCELERATION_DURATION {ACCEPT{fx_duration; fx_group;}}
			BUTTON PFORCE_ACCELERATION_DURATION_SELECTOR {}		
		}

		REAL PFORCE_ACCELERATION_INTENSITY { MIN -100000; MAX 100000; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
		VECTOR PFORCE_ACCELERATION {STEP 0.01; MIN -1 -1 -1; MAX 1 1 1;}
	}
}
			