CONTAINER fx_pop_property
{	
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	INCLUDE fx_rate;

	NAME fx_pop_property;
	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2; 
			LINK POP_PROPERTY_INPUT  { SCALE_H; ACCEPT{fx_particlegroup; fx_group;}}
			BUTTON POP_PROPERTY_INPUT_SELECTOR {SCALE_V; FIT_H;}
			
			LINK POP_PROPERTY_TARGET {ACCEPT{fx_property; fx_group;}}
			BUTTON POP_PROPERTY_TARGET_SELECTOR {SCALE_V; FIT_H;}
			
			LINK POP_PROPERTY_SOURCE {ACCEPT{fx_property; fx_alignment; fx_group;}}
			BUTTON POP_PROPERTY_SOURCE_SELECTOR {SCALE_V; FIT_H;}
			
			LINK POP_PROPERTY_DURATION { ACCEPT { fx_duration;  fx_group;}}
			BUTTON POP_PROPERTY_DURATION_SELECTOR {SCALE_V; FIT_H;}
		}
		
		LONG POP_PROPERTY_INPUT_FACTORY
		{
			CYCLE
			{
				POP_PROPERTY_INPUT_FACTORY_PASSIVE;
				POP_PROPERTY_INPUT_FACTORY_VORTICITY;
				POP_PROPERTY_INPUT_FACTORY_IMPLICIT;
				POP_PROPERTY_INPUT_FACTORY_DIFFUSE;
			}
		}
		LONG POP_PROPERTY_OPERATION
		{
			CYCLE
			{
				POP_PROPERTY_OPERATION_SET;
				POP_PROPERTY_OPERATION_ADD;
				POP_PROPERTY_OPERATION_SUBSTRACT;
				POP_PROPERTY_OPERATION_MULTIPLY;
				POP_PROPERTY_OPERATION_DOT;
				POP_PROPERTY_OPERATION_MIN;
				POP_PROPERTY_OPERATION_MAX;
				POP_PROPERTY_OPERATION_BLEND;
			}
		}
		BOOL POP_PROPERTY_VALUEFY_SOURCE {}
		LONG POP_PROPERTY_COLORMODE
		{
			CYCLE
			{
				POP_PROPERTY_COLORMODE_OFF;
				POP_PROPERTY_COLORMODE_COLOR;
				POP_PROPERTY_COLORMODE_CONSTRAINTS;
				//POP_PROPERTY_COLORMODE_CONSTRAINTS_CUSTOM;
			}
		}
		COLOR POP_PROPERTY_COLOR {HIDDEN;}
		
		LONG POP_PROPERTY_BLENDMODE
		{
			CYCLE
			{
				POP_PROPERTY_BLENDMODE_NORMAL;
				POP_PROPERTY_BLENDMODE_MULTIPLY;
				POP_PROPERTY_BLENDMODE_DARKEN;
				POP_PROPERTY_BLENDMODE_LIGHTEN;
				POP_PROPERTY_BLENDMODE_SCREEN;
				POP_PROPERTY_BLENDMODE_OVERLAY;
				POP_PROPERTY_BLENDMODE_HARDLIGHT;
				POP_PROPERTY_BLENDMODE_SOFTLIGHT;
				POP_PROPERTY_BLENDMODE_COLORDODGE;
				POP_PROPERTY_BLENDMODE_COLORDODGEINV;
				POP_PROPERTY_BLENDMODE_COLORBURN;
				POP_PROPERTY_BLENDMODE_SOFTBURN;
				POP_PROPERTY_BLENDMODE_DIFFERENCE;
				POP_PROPERTY_BLENDMODE_NDIFFERENCE;
				POP_PROPERTY_BLENDMODE_EXCLUDE;
				POP_PROPERTY_BLENDMODE_REFLECT;
				POP_PROPERTY_BLENDMODE_ADD;
				POP_PROPERTY_BLENDMODE_SUB;
			}
		}
		REAL POP_PROPERTY_BLENDVALUE {MIN 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
	}
	GROUP ID_FORCE_BASE_CONSTRAINTS_SUB
	{
		BOOL POP_PROPERTY_CONSTRAINTS_ZEROSTOP {}
	}
}