#ifndef FX_PFORCE_ALIGNMENT_H
#define FX_PFORCE_ALIGNMENT_H

enum
{		
	PFORCE_ALIGNMENT_INTENSITY = 1000,
	PFORCE_ALIGNMENT_DURATION,
	PFORCE_ALIGNMENT_DURATION_SELECTOR,
	PFORCE_ALIGNMENT_RADIUS,
	
	PFORCE_ALIGNMENT_DUMMY_

};

#endif