CONTAINER fx_pop_geometry
{	
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;

	NAME fx_pop_geometry;
	GROUP ID_FORCE_BASE
	{
		GROUP ID_PORT_BASE
		{
			COLUMNS 2; 
			LINK POP_GEOMETRY_INPUT  { SCALE_H; ACCEPT{fx_particlegroup; fx_group;}}
			BUTTON POP_GEOMETRY_INPUT_SELECTOR {SCALE_V; FIT_H;}
			
			LINK POP_GEOMETRY_DURATION { ACCEPT { fx_duration;  fx_group;}}
			BUTTON POP_GEOMETRY_DURATION_SELECTOR {SCALE_V; FIT_H;}
		}
		
		BOOL POP_GEOMETRY_RENDERONLY {}
		LONG POP_GEOMETRY_INPUT_FACTORY
		{
			CYCLE
			{
				POP_GEOMETRY_INPUT_FACTORY_PASSIVE;
				POP_GEOMETRY_INPUT_FACTORY_VORTICITY;
				POP_GEOMETRY_INPUT_FACTORY_IMPLICIT;
				POP_GEOMETRY_INPUT_FACTORY_DIFFUSE;
			}
		}
		LONG POP_GEOMETRY_POSITION
		{
			CYCLE
			{
				POP_GEOMETRY_POSITION_POS;
				POP_GEOMETRY_POSITION_WEIGHTED;
				POP_GEOMETRY_POSITION_DEFORMED;
			}
		}
		LONG POP_GEOMETRY_TYPE
		{
			CYCLE
			{
				POP_GEOMETRY_TYPE_ORIG;
				POP_GEOMETRY_TYPE_INSTANCE;
				POP_GEOMETRY_TYPE_RENDERINSTANCE;
			}
		}
		LONG POP_GEOMETRY_ALIGNMENT
		{
			CYCLE
			{
				POP_GEOMETRY_ALIGNMENT_X;
				POP_GEOMETRY_ALIGNMENT_Y;
				POP_GEOMETRY_ALIGNMENT_Z;
				POP_GEOMETRY_ALIGNMENT_TRAVEL;
				POP_GEOMETRY_ALIGNMENT_BILLBOARD;
			}
		}

		GROUP POP_GEOMETRY_SCALE_SUB
		{
			DEFAULT 1;
			BOOL	 POP_GEOMETRY_SCALE_UNIFORM {}
			VECTOR	 POP_GEOMETRY_SCALE		{MIN 0 0 0; STEP 0.1 0.1 0.1;}
			REAL	 POP_GEOMETRY_SCALE_VAR		{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL	 POP_GEOMETRY_SCALE_VARY	{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
			REAL	 POP_GEOMETRY_SCALE_VARZ	{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

			SEPARATOR {LINE;}
			
			VECTOR	 POP_GEOMETRY_SCALE_VELOCITY	{MIN 0 0 0; UNIT PERCENT;}
			REAL	 POP_GEOMETRY_SCALE_VELOCITYVAR	{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		}

		GROUP POP_GEOMETRY_ROTATION_SUB
		{
			VECTOR  POP_GEOMETRY_ROTATION		{MIN -360 -360 -360; MAX 360 360 360; UNIT DEGREE;}
			REAL	POP_GEOMETRY_ROTATION_VAR	{MIN 0; MAX 100; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		}
	}
	GROUP ID_FORCE_BASE_CONSTRAINTS_SUB
	{
		IN_EXCLUDE POP_GEOMETRY_CONSTRAINTS_SCALE
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0; SCALE_H;
			ACCEPT 
			{  
				fx_constraint;
				fx_constraint_plugin;
			};
		}
		BUTTON POP_GEOMETRY_CONSTRAINTS_SCALE_SELECTOR { SCALE_V; FIT_H;}
		
		IN_EXCLUDE POP_GEOMETRY_CONSTRAINTS_ROTATION
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0; SCALE_H;
			ACCEPT 
			{  
				fx_constraint;
				fx_constraint_plugin;
			};
		}
		BUTTON POP_GEOMETRY_CONSTRAINTS_ROTATION_SELECTOR { SCALE_V; FIT_H;}
	}
}