#ifndef FX_PFORCE_SEPARATION_H
#define FX_PFORCE_SEPARATION_H

enum
{		
	PFORCE_SEPARATION_INTENSITY = 1000,
	PFORCE_SEPARATION_DURATION,
	PFORCE_SEPARATION_DURATION_SELECTOR,
	PFORCE_SEPARATION_RADIUS,
	
	PFORCE_SEPARATION_DUMMY_

};

#endif