#ifndef FX_POP_FLOCK_H
#define FX_POP_FLOCK_H

enum
{	
	POP_FLOCK_BOIDS = 1000,
	POP_FLOCK_BOIDS_SELECTOR,
	POP_FLOCK_PREDATORS,
	POP_FLOCK_PREDATORS_SELECTOR,
	POP_FLOCK_LEADER,
	POP_FLOCK_LEADER_SELECTOR,
	POP_FLOCK_DURATION,
	POP_FLOCK_DURATION_SELECTOR,

	POP_FLOCK_BOIDS_FACTORY = 1008,
		POP_FLOCK_BOIDS_FACTORY_PASSIVE = 0,
		POP_FLOCK_BOIDS_FACTORY_VORTICITY,
		POP_FLOCK_BOIDS_FACTORY_IMPLICIT,
		POP_FLOCK_BOIDS_FACTORY_DIFFUSE,
	POP_FLOCK_PREDATORS_FACTORY = 1009,
		POP_FLOCK_PREDATORS_FACTORY_PASSIVE = 0,
		POP_FLOCK_PREDATORS_FACTORY_VORTICITY,
		POP_FLOCK_PREDATORS_FACTORY_IMPLICIT,
		POP_FLOCK_PREDATORS_FACTORY_DIFFUSE,
	POP_FLOCK_LEADERS_FACTORY = 1010,
		POP_FLOCK_LEADERS_FACTORY_PASSIVE = 0,
		POP_FLOCK_LEADERS_FACTORY_VORTICITY,
		POP_FLOCK_LEADERS_FACTORY_IMPLICIT,
		POP_FLOCK_LEADERS_FACTORY_DIFFUSE,
	POP_FLOCK_COHESION = 1011,
	POP_FLOCK_SEPARATION,
	POP_FLOCK_ALIGNMENT,
	POP_FLOCK_SEPARATION_RADIUS,
	POP_FLOCK_COHESION_RADIUS,
	POP_FLOCK_ALIGNMENT_RADIUS,
	POP_FLOCK_MAXVELOCITY,

	POP_FLOCK_PREDATORS_COHESION,
	POP_FLOCK_PREDATORS_COHESION_RADIUS,
	POP_FLOCK_PREDATORS_SEPARATION,
	POP_FLOCK_PREDATORS_SEPARATION_RADIUS,
	POP_FLOCK_PREDATORS_MAXVELOCITY,
	
	POP_FLOCK_BOIDS_SUB,
	POP_FLOCK_PREDATORS_SUB,

	POP_FLOCK_FLEE,
	POP_FLOCK_FLEE_RADIUS,
	POP_FLOCK_PREDATORS_EATPREY,
	POP_FLOCK_PREDATORS_EATPREY_RADIUS,

	POP_FLOCK_DUMMY_
};

#endif