#ifndef FX_POP_FOLLOWSPLINE_H
#define FX_POP_FOLLOWSPLINE_H

enum
{	
	POP_FOLLOWSPLINE_STEER = 2000,
	POP_FOLLOWSPLINE_FOLLOW,
	
	POP_FOLLOWSPLINE_SPLINE = 1000,
	POP_FOLLOWSPLINE_SPLINE_SELECTOR,
	POP_FOLLOWSPLINE_DURATION,
	POP_FOLLOWSPLINE_DURATION_SELECTOR,
	
	POP_FOLLOWSPLINE_STEERDISTANCE,
	POP_FOLLOWSPLINE_STEERMODE = 1005,
		POP_FOLLOWSPLINE_STEERMODE_NEAREST = 0,
		POP_FOLLOWSPLINE_STEERMODE_NEARESTVERTEX,
		POP_FOLLOWSPLINE_STEERMODE_VERTEX,
		POP_FOLLOWSPLINE_STEERMODE_PERCENT,
		POP_FOLLOWSPLINE_STEERMODE_RANDOM,
	POP_FOLLOWSPLINE_STEERMAXVELOCITY = 1006,
	POP_FOLLOWSPLINE_STEERINTENSITY,
	POP_FOLLOWSPLINE_STEERMODE_SEGMENT = 1008,
		POP_FOLLOWSPLINE_STEERMODE_SEGMENT_RANDOM = 0,
		POP_FOLLOWSPLINE_STEERMODE_SEGMENT_SEQUENTIAL,
		POP_FOLLOWSPLINE_STEERMODE_SEGMENT_INDEX,
	POP_FOLLOWSPLINE_STEERSEGMENT = 1009,
	POP_FOLLOWSPLINE_STEERVERTEX,
	POP_FOLLOWSPLINE_STEERPERCENT,
	POP_FOLLOWSPLINE_STEERACUTENESS,
	
	POP_FOLLOWSPLINE_FOLLOWDISTANCE,
	POP_FOLLOWSPLINE_FOLLOWMODE = 1014,
		POP_FOLLOWSPLINE_FOLLOWMODE_FORWARD = 0,
		POP_FOLLOWSPLINE_FOLLOWMODE_BACKWARD,
		POP_FOLLOWSPLINE_FOLLOWMODE_BOTH,
	POP_FOLLOWSPLINE_FOLLOWINTENSITY = 1015,
	POP_FOLLOWSPLINE_PARTICLES,
	POP_FOLLOWSPLINE_PARTICLES_SELECTOR,
	POP_FOLLOWSPLINE_PROPERTY,
	POP_FOLLOWSPLINE_PROPERTY_SELECTOR,
	POP_FOLLOWSPLINE_FOLLOWLOOP = 1020,
		POP_FOLLOWSPLINE_FOLLOWLOOP_RESTART = 0,
		POP_FOLLOWSPLINE_FOLLOWLOOP_LOOP,
		POP_FOLLOWSPLINE_FOLLOWLOOP_END,
	POP_FOLLOWSPLINE_STEERMAXORIGVEL = 1021,
	POP_FOLLOWSPLINE_FOLLOWDISTANCE_RND,
	POP_FOLLOWSPLINE_FOLLOWROTATIONHULL,
	POP_FOLLOWSPLINE_FOLLOWROTATIONHULL_RND,
	POP_FOLLOWSPLINE_FOLLOWROTATIONANGLE,
	POP_FOLLOWSPLINE_FOLLOWROTATIONANGLE_RND,
	
	POP_FOLLOWSPLINE_FOLLOWSPEED = 1027,
		POP_FOLLOWSPLINE_FOLLOWSPEED_PARTICLE = 0,
		POP_FOLLOWSPLINE_FOLLOWSPEED_SPECIFIC,
		POP_FOLLOWSPLINE_FOLLOWSPEED_LENGTH,
	POP_FOLLOWSPLINE_FOLLOWROTATION = 1028,
	POP_FOLLOWSPLINE_FOLLOWROTATION_RND,
	POP_FOLLOWSPLINE_FOLLOWSPEEDCUSTOM,
	POP_FOLLOWSPLINE_FOLLOWSPEEDFRAMES,
	POP_FOLLOWSPLINE_FOLLOWPOSITION,
	POP_FOLLOWSPLINE_FOLLOWPOSITION_RND,

	POP_FOLLOWSPLINE_DUMMY_

};

#endif