#ifndef FX_PFORCE_TENSION_H
#define FX_PFORCE_TENSION_H

enum
{		
	PFORCE_TENSION_PARTICLES = 1000,
	PFORCE_TENSION_DYNAMICS,
	PFORCE_TENSION_K,
	PFORCE_TENSION_PARTICLES_SELECTOR,
	PFORCE_TENSION_DYNAMICS_SELECTOR,
	PFORCE_TENSION_RADIUS,
	PFORCE_TENSION_MINDENSITY = 1007,
	PFORCE_TENSION_MAXDENSITY,
	PFORCE_TENSION_MODE = 1009,
		PFORCE_TENSION_MODE_COHESION = 0,
		PFORCE_TENSION_MODE_COLOR,
	PFORCE_TENSION_INPUT_FACTORY = 1010,
		PFORCE_TENSION_INPUT_FACTORY_PASSIVE = 0,
		PFORCE_TENSION_INPUT_FACTORY_VORTICITY,
		PFORCE_TENSION_INPUT_FACTORY_IMPLICIT,
		PFORCE_TENSION_INPUT_FACTORY_DIFFUSE,

	PFORCE_TENSION_DUMMY_

};

#endif