#ifndef FX_PSURFACEOPROPERTY_H
#define FX_PSURFACEOPROPERTY_H

enum
{	
	ID_PSURFACEPROPERTY_BASE = 2000,
	SEP_PSURFACEPROPERTY_NORMAL,
	SEP_PSURFACEPROPERTY_CURVATURE,
	SEP_PSURFACEPROPERTY_ANISOTROPIC,

	PSURFACEPROPERTY_PARTICLES = 1000,
	PSURFACEPROPERTY_DYNAMICS,
	PSURFACEPROPERTY_PARTICLES_SELECTOR,
	PSURFACEPROPERTY_DYNAMICS_SELECTOR,

	PSURFACEPROPERTY_RADIUS,
	PSURFACEPROPERTY_MINDENSITY,
	PSURFACEPROPERTY_MAXDENSITY,
	
	PSURFACEPROPERTY_NORMAL,
	PSURFACEPROPERTY_CURVATURE = 1008,
		PSURFACEPROPERTY_CURVATURE_OFF = 0,
		PSURFACEPROPERTY_CURVATURE_SIMPLE,
		PSURFACEPROPERTY_CURVATURE_DIRECT,
		PSURFACEPROPERTY_CURVATURE_NORMALISED,
	PSURFACEPROPERTY_ANISOTROPY = 1009,

	PSURFACEPROPERTY_INPUT_FACTORY = 1010,
		PSURFACEPROPERTY_INPUT_FACTORY_PASSIVE = 0,
		PSURFACEPROPERTY_INPUT_FACTORY_VORTICITY,
		PSURFACEPROPERTY_INPUT_FACTORY_IMPLICIT,
		PSURFACEPROPERTY_INPUT_FACTORY_DIFFUSE,
	PSURFACEPROPERTY_KERNEL = 1011,
		PSURFACEPROPERTY_KERNEL_SMOOTH = 0,
		PSURFACEPROPERTY_KERNEL_SPIKEY,
		PSURFACEPROPERTY_KERNEL_POLY6,
	PSURFACEPROPERTY_RADIUS_CURVATURE = 1012,
	PSURFACEPROPERTY_RADIUS_ANISOTROPY,
	PSURFACEPROPERTY_RADIUSGLOBAL,
	PSURFACEPROPERTY_MAXCURVATURE,

	PSURFACEPROPERTY_DUMMY_

};

#endif