CONTAINER fx_particlegridemitter
{
	NAME fx_particlegridemitter;
	INCLUDE fx_force_base;
	INCLUDE fx_base_constraints;
	
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK PARTICLEGRIDEMITTER_VOLUME { ACCEPT {  fx_volume; fx_csg; fx_volume_multi;fx_group;}; }
			BUTTON PARTICLEGRIDEMITTER_VOLUME_SELECTOR { SCALE_V; FIT_H; }

			LINK PARTICLEGRIDEMITTER_PARTICLEFACTORY { ACCEPT {  fx_particlegroup;fx_group; } }
			BUTTON PARTICLEGRIDEMITTER_PARTICLEFACTORY_SELECTOR { SCALE_V; FIT_H;}
			
			LINK PARTICLEGRIDEMITTER_SETTINGS { ACCEPT {  fx_particlemesh_emission_setting; fx_group;} }
			BUTTON PARTICLEGRIDEMITTER_SETTINGS_SELECTOR { SCALE_V; FIT_H;}
			
			IN_EXCLUDE PARTICLEGRIDEMITTER_PROPS	
			{ 
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
				ACCEPT {  fx_property_scalar; fx_property_vector; }; 
			}
			BUTTON PARTICLEGRIDEMITTER_PROPS_SELECTOR { SCALE_V; FIT_H;}

			LINK	PARTICLEGRIDEMITTER_ALIGNMENT { HIDDEN; ACCEPT{fx_alignment; fx_group;}}
			BUTTON	PARTICLEGRIDEMITTER_ALIGNMENT_SELECTOR {HIDDEN; }

			LINK	PARTICLEGRIDEMITTER_DURATION {HIDDEN; ACCEPT{fx_duration; fx_group;}}
			BUTTON	PARTICLEGRIDEMITTER_DURATION_SELECTOR {HIDDEN; SCALE_V; FIT_H;}
		}
		LONG PARTICLEGRIDEMITTER_PARTICLETYPE
		{
			CYCLE
			{
				PARTICLEGRIDEMITTER_PARTICLETYPE_PASSIVE;
				PARTICLEGRIDEMITTER_PARTICLETYPE_VORTICITY;
				PARTICLEGRIDEMITTER_PARTICLETYPE_LIQUID;
				PARTICLEGRIDEMITTER_PARTICLETYPE_DIFFUSE;
			}
		}
		LONG PARTICLEGRIDEMITTER_COLORMODE
		{
			CYCLE
			{
				PARTICLEGRIDEMITTER_COLORMODE_COLOR;
				PARTICLEGRIDEMITTER_COLORMODE_SHADER;
				PARTICLEGRIDEMITTER_COLORMODE_CONSTRAINTS;
				//PARTICLEGRIDEMITTER_COLORMODE_CONSTRAINTS_CUSTOM;
			}
		}
		COLOR PARTICLEGRIDEMITTER_COLOR {HIDDEN;}
		SHADERLINK PARTICLEGRIDEMITTER_COLORSHADER {}

		REAL PARTICLEGRIDEMITTER_SPEED {MIN -10000.0; MAX 10000.0; MAXSLIDER 10.0; MINSLIDER -10.0; STEP 0.1; CUSTOMGUI REALSLIDER;}
		REAL PARTICLEGRIDEMITTER_SPEED_JITTER {MIN 0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

		SEPARATOR PARTICLEGRIDEMITTER_SEP_LOCATION {}

		REAL PARTICLEGRIDEMITTER_JITTER {MIN 0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		BOOL PARTICLEGRIDEMITTER_CONSTRAINTS_EXACT {}
		REAL PARTICLEGRIDEMITTER_PHI_MIN { MIN 0; MAX 100; UNIT PERCENT;}
		REAL PARTICLEGRIDEMITTER_PHI_MAX { MIN -100; UNIT PERCENT; }

		SEPARATOR PARTICLEGRIDEMITTER_SEP_SAMPLING {}

		REAL PARTICLEGRIDEMITTER_SAMPLING_MINIMUM { MIN 0.0; MAXSLIDER 100; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL PARTICLEGRIDEMITTER_GRIDSUBDIVISIONS_PHI { STEP 0.1; }
		LONG PARTICLEGRIDEMITTER_GRIDSUBDIVISIONS_MIN { MIN 0; MAX 5; }
		LONG PARTICLEGRIDEMITTER_GRIDSUBDIVISIONS_MAX { MIN 0; MAX 5; }

	}
	GROUP ID_FORCE_BASE_CONSTRAINTS
	{
		GROUP ID_FORCE_BASE_CONSTRAINTS_SUB
		{
			IN_EXCLUDE PARTICLEGRIDEMITTER_SOLVERS	
			{ 
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0; SCALE_H;
				ACCEPT {  fx_fluid; fx_liquid; }; 
			}
		}
	}
}