#ifndef FX_PROPERTIES_PARTICLES_H
#define FX_PROPERTIES_PARTICLES_H

enum
{	
	PROPERTIES_PARTICLES_GROUP = 1000,
	PROPERTIES_PARTICLES_PARTICLES = 1001,
		PROPERTIES_PARTICLES_PARTICLES_PASSIVE = 0,
		PROPERTIES_PARTICLES_PARTICLES_VORTICITY,
		PROPERTIES_PARTICLES_PARTICLES_LIQUID,
		PROPERTIES_PARTICLES_PARTICLES_DIFFUSE,
	PROPERTIES_PARTICLES_CHANNELVALUES = 1002,
	PROPERTIES_PARTICLES_RADFALLOFF = 1003,
		PROPERTIES_PARTICLES_RADFALLOFF_NONE = 0,
		PROPERTIES_PARTICLES_RADFALLOFF_LINEAR,
		PROPERTIES_PARTICLES_RADFALLOFF_CUSTOM,
	PROPERTIES_PARTICLES_RADFALLOFF_GRAD = 1004,
	PROPERTIES_PARTICLES_MASSINFLUENCE,
	PROPERTIES_PARTICLES_SIZEINFLUENCE,
	PROPERTIES_PARTICLES_EMIT_PROPERTIES,
	PROPERTIES_PARTICLES_CONSTRAINTS,
	PROPERTIES_PARTICLES_RATEMODE,
		
	PROPERTIES_PARTICLES_GROUP_SELECTOR,
	PROPERTIES_PARTICLES_DURATION_SELECTOR,
	PROPERTIES_PARTICLES_MOEFFECTORS,
	PROPERTIES_PARTICLES_CONSTRAINTMODE = 1013,
		PROPERTIES_PARTICLES_CONSTRAINTMODE_BOTH = 0,
		PROPERTIES_PARTICLES_CONSTRAINTMODE_PARTICLES,
	PROPERTIES_PARTICLES_RADIUS = 1014,
	PROPERTIES_PARTICLES_CHANNELVALUES_SELECTOR,
	PROPERTIES_PARTICLES_DURATION,

	PROPERTIES_PARTICLES_DUMMY_

};

#endif