#ifndef FX_POP_PIOP_H
#define FX_POP_PIOP_H

enum
{	
	FX_POP_PIOP_PARTICLES = 1000,
	FX_POP_PIOP_PARTICLES_SELECTOR,
	FX_POP_PIOP_OPERATORS,
	FX_POP_PIOP_OPERATORS_SELECTOR,
	FX_POP_PIOP_INPUT_FACTORY = 1004,
		FX_POP_PIOP_INPUT_FACTORY_PASSIVE = 0,
		FX_POP_PIOP_INPUT_FACTORY_VORTICITY,
		FX_POP_PIOP_INPUT_FACTORY_IMPLICIT,
		FX_POP_PIOP_INPUT_FACTORY_DIFFUSE,
	FX_POP_PIOP_DURATION = 1005,
	FX_POP_PIOP_DURATION_SELECTOR,

	FX_POP_PIOP_END
};

#endif