CONTAINER fx_rate
{
	NAME fx_rate;
	INCLUDE fx_force_base;
	
	GROUP ID_FORCE_BASE
	{
		LONG RATE_TYPE
		{
			CYCLE
			{
				RATE_TYPE_SCALAR;
				RATE_TYPE_VECTOR;
				RATE_TYPE_INTEGER;
			}
		}
		REAL	RATE_SCALAR {CUSTOMGUI DOUBLE; DSIZE 70; DDIGITS 8; }
		VECTOR	RATE_VECTOR {}
		LONG	RATE_INTEGER { MAX 100000000; }
	}
}