#ifndef FX_RIGID_FORCES_H
#define FX_RIGID_FORCES_H

enum
{	
	RIGID_FORCES_VOLUMES = 1000,
	RIGID_FORCES_FORCES,
	RIGID_FORCES_MODE = 1002,
		RIGID_FORCES_MODE_NODE = 0,
		RIGID_FORCES_MODE_VERTEX,
		RIGID_FORCES_MODE_VOLUME,
	RIGID_FORCES_VOLUMES_MODE = 1003,
		RIGID_FORCES_VOLUMES_MODE_INCLUDE = 0,
		RIGID_FORCES_VOLUMES_MODE_EXCLUDE,

	//SELECTORS
	RIGID_FORCES_VOLUMES_SELECTOR = 1100,
	RIGID_FORCES_FORCES_SELECTOR,
		
	RIGID_FORCES_DUMMY_

};

#endif