CONTAINER fx_shader_particlesampler
{
	NAME fx_shader_particlesampler;
	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		DEFAULT 1;
		GROUP
		{
			COLUMNS 2;
			LINK FX_PARTICLESAMPLER_PARTICLES 
			{
				ACCEPT
				{ 
					fx_particlegroup;
					fx_mesh;
					1001381; 
					Obase;
					Oparticle;
					1027133;
				} 
			}
			BUTTON FX_PARTICLESAMPLER_PARTICLES_SELECTOR {}
			LINK FX_PARTICLESAMPLER_PROPERTY 
			{
				ACCEPT
				{ 
					fx_property_scalar;
					fx_property_vector;
				} 
			}
			BUTTON FX_PARTICLESAMPLER_PROPERTY_SELECTOR {}
		}
		BOOL FX_PARTICLESAMPLER_USEBRUSHDATA {}

		SEPARATOR {LINE;}

		LONG FX_PARTICLESAMPLER_PARTICLETYPE
		{
			ANIM OFF;
			CYCLE
			{
				FX_PARTICLESAMPLER_PARTICLETYPE_PASSIVE;
				FX_PARTICLESAMPLER_PARTICLETYPE_VORTICITY;
				FX_PARTICLESAMPLER_PARTICLETYPE_LIQUID;
				FX_PARTICLESAMPLER_PARTICLETYPE_DIFFUSE;
			}
		}
		LONG FX_PARTICLESAMPLER_POSITION
		{
			CYCLE
			{
				FX_PARTICLESAMPLER_POSITION_POS;
				FX_PARTICLESAMPLER_POSITION_WEIGHTED;
				FX_PARTICLESAMPLER_POSITION_DEFORMED;
			}
		}
		BOOL FX_PARTICLESAMPLER_AVERAGE {}
		BOOL FX_PARTICLESAMPLER_VECTORASCOLOR {}
		REAL FX_PARTICLESAMPLER_RADIUS { MIN 0.001; STEP 0.01; }
		SHADERLINK FX_PARTICLESAMPLER_UVSHADER {}
		
		SEPARATOR {LINE;}

		GROUP
		{
			COLUMNS 2;
			LONG FX_PARTICLESAMPLER_MINPARTICLES {MIN 1;}
			LONG FX_PARTICLESAMPLER_MAXPARTICLES {MIN 2;}
			REAL FX_PARTICLESAMPLER_RANGE_MIN {MIN 0; STEP 0.1;}
			REAL FX_PARTICLESAMPLER_RANGE_MAX {MIN 0; STEP 0.1;}
		}		
		GROUP FX_PARTICLESAMPLER_SUBID_DISPLACE
		{			
			REAL FX_PARTICLESAMPLER_ADVECT {HIDDEN; MIN 0.0; STEP 0.001;}
			REAL FX_PARTICLESAMPLER_DISPLACEMENT { STEP 0.01; UNIT METER; }
			SHADERLINK FX_PARTICLESAMPLER_DISPLACEMENT_SHADER {}
		}
		GROUP FX_PARTICLESAMPLER_SUBID_COLOR
		{
			DEFAULT 1;

			LONG FX_PARTICLESAMPLER_COLOR_PRESETS
			{
				CYCLE
				{
					FX_PARTICLESAMPLER_COLOR_PRESETS_BLACKWHITE;
					FX_PARTICLESAMPLER_COLOR_PRESETS_BLACKBODY;
				}
			}
			GRADIENT FX_PARTICLESAMPLER_COLOR {COLOR;ICC_BASEDOCUMENT;}

			SEPARATOR {LINE;}

			BITMAPBUTTON FX_PARTICLESAMPLER_COLOR_HEATPLANCK {BORDER;} //Show physical gradient
			LONG FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP 
			{
				CYCLE
				{
					FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_NTSC;
					FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_PAL;
					FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_SMPTE;
					FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_HDTV;
					FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_CIE;
					FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_CIEREC709;
				}
			}
			VECTOR FX_PARTICLESAMPLER_COLOR_HEATPLANCK_BOOST {MIN 0 0 0; MAX 100 100 100; STEP 0.01;}
			REAL FX_PARTICLESAMPLER_COLOR_HEATPLANCK_INTENSITY {MIN 1; MAX 10; STEP 0.01; }
			REAL FX_PARTICLESAMPLER_COLOR_HEATPLANCK_SCALE {MIN 0; MAX 100; STEP 0.1; CUSTOMGUI REALSLIDER;}
			BOOL FX_PARTICLESAMPLER_COLOR_HEATPLANCK_GAMMA {}
			BOOL FX_PARTICLESAMPLER_COLOR_HEATPLANCK_NORMALIZE {}
		}

		SEPARATOR {LINE;}
		
		GROUP FX_PARTICLESAMPLER_SUBID_CLIPPING
		{
			COLUMNS 2;
			REAL FX_PARTICLESAMPLER_RANGEOUT_MIN {MIN 0;}
			REAL FX_PARTICLESAMPLER_RANGEOUT_MAX {MIN 0; STEP 0.1;}
		}
	}
}