#ifndef FX_SURFACERECONSTRUCTOR_H
#define FX_SURFACERECONSTRUCTOR_H

enum
{
	SURFACE_RECONSTRUCTION_ISOTROPIC = 2000,
	SURFACE_RECONSTRUCTION_ANISOTROPIC,

	SURFACE_RECONSTRUCTION_RENDERONLY = 1000,
	SURFACE_RECONSTRUCTION_GROUP,
	SURFACE_RECONSTRUCTION_PARTICLES = 1002,
		SURFACE_RECONSTRUCTION_PARTICLES_PASSIVE = 0,
		SURFACE_RECONSTRUCTION_PARTICLES_VORTICITY,
		SURFACE_RECONSTRUCTION_PARTICLES_LIQUID,
		SURFACE_RECONSTRUCTION_PARTICLES_FOAM,
		SURFACE_RECONSTRUCTION_PARTICLES_BUBBLES,
		SURFACE_RECONSTRUCTION_PARTICLES_SPRAY,
	SURFACE_RECONSTRUCTION_SURFACE_TRACKER = 1003,
	SURFACE_RECONSTRUCTION_SURFACE_TRACKER_DISTANCE,
	SURFACE_RECONSTRUCTION_SURFACETYPE = 1005,
		SURFACE_RECONSTRUCTION_SURFACETYPE_ISOTROPIC = 0,
		SURFACE_RECONSTRUCTION_SURFACETYPE_ANISOTROPIC,
		SURFACE_RECONSTRUCTION_SURFACETYPE_ANISOTROPICDIST,
	SURFACE_RECONSTRUCTION_SEARCHCOUNT_MIN = 1006,
	SURFACE_RECONSTRUCTION_SEARCHCOUNT_MAX,
	SURFACE_RECONSTRUCTION_RADIUS,
	SURFACE_RECONSTRUCTION_SMOOTHINGRADIUS,
	SURFACE_RECONSTRUCTION_ISOSURFACE,

	SURFACE_RECONSTRUCTION_ISOTROPIC_USEDENSITYPOS = 1012,

	SURFACE_RECONSTRUCTION_ANISOTROPIC_AUTORADIUS,
	SURFACE_RECONSTRUCTION_ANISOTROPIC_MAXSTRETCH,
	SURFACE_RECONSTRUCTION_ANISOTROPIC_ANISOTROPY,
		SURFACE_RECONSTRUCTION_ANISOTROPIC_NEIGHBOR_ANISOTROPY = 0,
		SURFACE_RECONSTRUCTION_ANISOTROPIC_VELOCITY_ANISOTROPY,
	SURFACE_RECONSTRUCTION_ANISOTROPIC_VELOCITY_GAIN = 1016,

	SURFACE_RECONSTRUCTION_VOXELSCALE,
	SURFACE_RECONSTRUCTION_ANISOTROPIC_CONSTRAINT_RATIO,
	
	SURFACE_RECONSTRUCTION_GROUP_SELECTOR,
	SURFACE_RECONSTRUCTION_SURFACE_TRACKER_SELECTOR,
	SURFACE_RECONSTRUCTION_ISOTROPIC_USEISODENSITY,
	SURFACE_RECONSTRUCTION_ISOTROPIC_DECAYMIN,
	SURFACE_RECONSTRUCTION_ISOTROPIC_DECAYMAX,

	SURFACE_RECONSTRUCTION_KERNEL,
	SURFACE_RECONSTRUCTION_KERNEL_SELECTOR,

	SURFACE_RECONSTRUCTION_ISOTROPIC_POSITION = 1027,
		SURFACE_RECONSTRUCTION_ISOTROPIC_POSITION_POS = 0,
		SURFACE_RECONSTRUCTION_ISOTROPIC_POSITION_WEIGHTED,
		SURFACE_RECONSTRUCTION_ISOTROPIC_POSITION_DEFORMED,

	SURFACE_RECONSTRUCTION_DUMMY_
		
};

#endif