#ifndef fx_shader_gridsampler_H_
#define fx_shader_gridsampler_H_

enum
{
	FX_GRIDSAMPLER_SUBID_CLIPPING = 4000,

	FX_GRIDSAMPLER_CHANNEL = 3000,
	FX_GRIDSAMPLER_COLOR,
	FX_GRIDSAMPLER_FLUIDCHANNEL = 3002,
		FX_GRIDSAMPLER_FLUIDCHANNEL_VELOCITY = 0,
		FX_GRIDSAMPLER_FLUIDCHANNEL_DIVERGENCE,
		FX_GRIDSAMPLER_FLUIDCHANNEL_PRESSURE,
		FX_GRIDSAMPLER_FLUIDCHANNEL_VORTICITY,
	FX_GRIDSAMPLER_RANGE_MIN = 3003,
	FX_GRIDSAMPLER_RANGE_MAX,
	FX_GRIDSAMPLER_RANGEOUT_MIN,
	FX_GRIDSAMPLER_RANGEOUT_MAX,
	FX_GRIDSAMPLER_SURFACECOORDINATE,
	FX_GRIDSAMPLER_ADVECT,
	FX_GRIDSAMPLER_COLOR_PRESETS = 3009,
		FX_GRIDSAMPLER_COLOR_PRESETS_BLACKWHITE = 0,
		FX_GRIDSAMPLER_COLOR_PRESETS_BLACKBODY,
	FX_GRIDSAMPLER_COLOR_HEATPLANCK = 3010,
	FX_GRIDSAMPLER_COLOR_HEATPLANCK_CLAMP = 3011,
		FX_GRIDSAMPLER_COLOR_HEATPLANCK_CLAMP_NTSC = 0,
		FX_GRIDSAMPLER_COLOR_HEATPLANCK_CLAMP_PAL,
		FX_GRIDSAMPLER_COLOR_HEATPLANCK_CLAMP_SMPTE,
		FX_GRIDSAMPLER_COLOR_HEATPLANCK_CLAMP_HDTV,
		FX_GRIDSAMPLER_COLOR_HEATPLANCK_CLAMP_CIE,
		FX_GRIDSAMPLER_COLOR_HEATPLANCK_CLAMP_CIEREC709,
	FX_GRIDSAMPLER_COLOR_HEATPLANCK_BOOST = 3012,
	FX_GRIDSAMPLER_COLOR_HEATPLANCK_INTENSITY,
	FX_GRIDSAMPLER_COLOR_HEATPLANCK_SCALE,
	FX_GRIDSAMPLER_COLOR_HEATPLANCK_GAMMA,
	FX_GRIDSAMPLER_COLOR_HEATPLANCK_NORMALIZE,
	FX_GRIDSAMPLER_CHANNEL_SELECTOR,

	FX_GRIDSAMPLER_DUMMY
};

#endif