#ifndef fx_shader_particlesampler_H_
#define fx_shader_particlesampler_H_

enum
{
	FX_PARTICLESAMPLER_SUBID_CLIPPING = 4000,
	FX_PARTICLESAMPLER_SUBID_DISPLACE,
	FX_PARTICLESAMPLER_SUBID_COLOR,

	FX_PARTICLESAMPLER_PARTICLES = 3000,
	FX_PARTICLESAMPLER_COLOR,
	FX_PARTICLESAMPLER_PROPERTY,
	FX_PARTICLESAMPLER_RANGE_MIN = 3003,
	FX_PARTICLESAMPLER_RANGE_MAX,
	FX_PARTICLESAMPLER_RANGEOUT_MIN,
	FX_PARTICLESAMPLER_RANGEOUT_MAX,
	FX_PARTICLESAMPLER_ADVECT,
	FX_PARTICLESAMPLER_COLOR_PRESETS = 3008,
		FX_PARTICLESAMPLER_COLOR_PRESETS_BLACKWHITE = 0,
		FX_PARTICLESAMPLER_COLOR_PRESETS_BLACKBODY,
	FX_PARTICLESAMPLER_COLOR_HEATPLANCK = 3009,
	FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP = 3010,
		FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_NTSC = 0,
		FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_PAL,
		FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_SMPTE,
		FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_HDTV,
		FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_CIE,
		FX_PARTICLESAMPLER_COLOR_HEATPLANCK_CLAMP_CIEREC709,
	FX_PARTICLESAMPLER_COLOR_HEATPLANCK_BOOST = 3011,
	FX_PARTICLESAMPLER_COLOR_HEATPLANCK_INTENSITY,
	FX_PARTICLESAMPLER_COLOR_HEATPLANCK_SCALE,
	FX_PARTICLESAMPLER_RADIUS,
	FX_PARTICLESAMPLER_AVERAGE,
	FX_PARTICLESAMPLER_PARTICLETYPE = 3016,
		FX_PARTICLESAMPLER_PARTICLETYPE_PASSIVE = 0,
		FX_PARTICLESAMPLER_PARTICLETYPE_VORTICITY,
		FX_PARTICLESAMPLER_PARTICLETYPE_LIQUID,
		FX_PARTICLESAMPLER_PARTICLETYPE_DIFFUSE,
	FX_PARTICLESAMPLER_MAXPARTICLES = 3017,
	FX_PARTICLESAMPLER_VECTORASCOLOR,
	FX_PARTICLESAMPLER_MINPARTICLES,
	FX_PARTICLESAMPLER_DISPLACEMENT,
	FX_PARTICLESAMPLER_DISPLACEMENT_SHADER,
	FX_PARTICLESAMPLER_UVSHADER,
	FX_PARTICLESAMPLER_COLOR_HEATPLANCK_GAMMA,
	FX_PARTICLESAMPLER_COLOR_HEATPLANCK_NORMALIZE,
	FX_PARTICLESAMPLER_USEBRUSHDATA,
	FX_PARTICLESAMPLER_PARTICLES_SELECTOR,
	FX_PARTICLESAMPLER_PROPERTY_SELECTOR,
	FX_PARTICLESAMPLER_POSITION = 3028,
		FX_PARTICLESAMPLER_POSITION_POS = 0,
		FX_PARTICLESAMPLER_POSITION_WEIGHTED,
		FX_PARTICLESAMPLER_POSITION_DEFORMED,

	FX_PARTICLESAMPLER_DUMMY
};

#endif