CONTAINER fx_sound
{
	NAME fx_sound;
	INCLUDE fx_force_base;
	INCLUDE fx_base_display;

	//Basic Tab
	GROUP ID_FORCE_BASE
	{			
		DEFAULT 1;
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			FILENAME FXSOUND_FILE { ANIM OFF; SCALE_H; }
		}		

		BITMAPBUTTON FXSOUND_GRAPH {FIT_H;BORDER;}
		STRING FXSOUND_INFO { CUSTOMGUI MULTISTRING; READONLY; WORDWRAP; ANIM OFF; }
		BITMAPBUTTON FXSOUND_FREQGRAPH {FIT_H;BORDER;}
		GROUP 
		{
			COLUMNS 4;
			REAL FXSOUND_FREQMIN { MIN 0; MAX 44098; STEP 10;}
			SEPARATOR {LINE;}STATICTEXT {JOINENDSCALE;}
			REAL FXSOUND_FREQMAX { MIN 1; MAX 44099; STEP 10;}
		}
		
		SEPARATOR { LINE; }
		
		BASETIME FXSOUND_START {  }
		LONG FXSOUND_FFTSAMPLES
		{
			CYCLE
			{
				FXSOUND_FFTSAMPLES_32;
				FXSOUND_FFTSAMPLES_64;
				FXSOUND_FFTSAMPLES_128;
				FXSOUND_FFTSAMPLES_256;
				FXSOUND_FFTSAMPLES_512;
				FXSOUND_FFTSAMPLES_1024;
				FXSOUND_FFTSAMPLES_2048;
				FXSOUND_FFTSAMPLES_4096;
			}
		}
		LONG FXSOUND_FILTER
		{
			CYCLE
			{
				FXSOUND_FILTER_UNIFORM;
				FXSOUND_FILTER_HANN;
				FXSOUND_FILTER_HAMMING;
				FXSOUND_FILTER_BLACKMAN;
				FXSOUND_FILTER_BLACKMANHARRIS;
				FXSOUND_FILTER_BLACKMANNUTTAL;
				FXSOUND_FILTER_FLATTOP;
				FXSOUND_FILTER_BARTLETT;
				FXSOUND_FILTER_BARTLETTHANN;
				FXSOUND_FILTER_COSINE;
				FXSOUND_FILTER_LANCZOS;
				//FXSOUND_FILTER_PLANCKTAPER;
			}
		}
		REAL FXSOUND_GAIN { MIN 0.0; MAXSLIDER 1.0; MAX 2.0; CUSTOMGUI REALSLIDER; STEP 0.01;}
		REAL FXSOUND_FALLOFF { MIN 0.0; MAX 1.0; CUSTOMGUI REALSLIDER; STEP 0.01;}
		SPLINE FXSOUND_FILTER_GRAPH { HIDDEN; SHOWGRID_H; X_MIN 0; X_MAX 1; Y_MIN 0; Y_MAX 1; X_STEPS 0.01; Y_STEPS 0.01;	}		
	}
	GROUP FX_BASE_DISPLAYTAB
	{
		LONG FXSOUND_PREVIEWSIZE { MIN 100; MAX 800; CUSTOMGUI LONGSLIDER; }
		LONG FXSOUND_PLAYMODE
		{
			CYCLE
			{
				FXSOUND_PLAYMODE_OFF;
				FXSOUND_PLAYMODE_CONTINOUS;
				FXSOUND_PLAYMODE_PERFRAME;
			}
		}
	}
}