CONTAINER fx_volume
{
	NAME fx_volume;
	INCLUDE fx_base_volume;
	INCLUDE fx_base_display;
	
	GROUP FX_BASE_QUICKTAB
	{
		COLUMNS 4;
		BUTTON FSSVOLUME_TOGGLE_OBSTACLE {}
		BUTTON FSSVOLUME_CREATE_CSVOLUME {}
		BUTTON FSSVOLUME_CREATE_CSNEARSURFACE {}
		BUTTON FSSVOLUME_CREATE_ATTRACTOR {}
	}
	GROUP ID_FORCE_BASE
	{
		DEFAULT 1;
		
		GROUP ID_PORT_BASE
		{
			COLUMNS 2;
			LINK FSSVOLUME_MESHSOURCE { ACCEPT{fx_mesh; fx_group;} }
			BUTTON FSSVOLUME_MESHSOURCE_SELECTOR {}
		}

		BOOL FSSVOLUME_CONTRIBUTE_BOUNDS {}
		BOOL FSSVOLUME_NOGRIDOBSTACLE {}

		SEPARATOR{LINE;}

		BOOL FSSVOLUME_INVERT {}
		LONG FSSVOLUME_FLUIDSAMPLEEXTENT { MIN 2; ANIM OFF;}
		LONG FSSVOLUME_SHAPE
		{
			HIDDEN;
			CYCLE
			{
				//FSSVOLUME_SHAPE_CUBE;
				FSSVOLUME_SHAPE_SPHERE;
				//FSSVOLUME_SHAPE_TORUS;
				//FSSVOLUME_SHAPE_CYLINDER;
				//FSSVOLUME_SHAPE_CONE;
				FSSVOLUME_SHAPE_MESH;
			}
			ANIM OFF;
		}		
		REAL FSSVOLUME_SPHERE_RADIUS {MIN 0.001; UNIT METER;  HIDDEN;}
		VECTOR FSSVOLUME_PRIMITIVE_SIZE {MIN 0.001 0.001 0.001; UNIT METER;HIDDEN;}
		REAL FSSVOLUME_INNER_RADIUS {MIN 0.01; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR G_FSSVOLUME_MESHIN {}

		LONG FSSVOLUME_LEVELSETQUALITY {MIN 1; MAX 3; PARENTID FSSVOLUME_MESHSOURCE; CUSTOMGUI LONGSLIDER; }
		LONG FSSVOLUME_SAFESWEEP { MIN 0; PARENTID FSSVOLUME_MESHSOURCE;}	
	}

	GROUP FX_BASE_DISPLAYTAB
	{
		SEPARATOR {LINE;}

		LINK FSSVOLUME_DISPLAY_PROPERTY { ACCEPT{fx_property_scalar; fx_property_state; fx_property_vector; fx_group;} }
	}
}