#ifndef FX_VOLUME_H
#define FX_VOLUME_H

enum
{
	G_FSSVOLUME_MESH = 3000,	
	G_FSSVOLUME_MESHIN,

	FSSVOLUME_CONTRIBUTE_BOUNDS = 1001,
	FSSVOLUME_SHAPE = 1002,
		FSSVOLUME_SHAPE_CUBE = 0,
		FSSVOLUME_SHAPE_SPHERE,
		FSSVOLUME_SHAPE_ELLIPSOID,
		FSSVOLUME_SHAPE_TORUS,
		FSSVOLUME_SHAPE_CYLINDER,
		FSSVOLUME_SHAPE_CONE,
		FSSVOLUME_SHAPE_MESH,
	FSSVOLUME_MESHSOURCE = 1003,
	FSSVOLUME_SPHERE_RADIUS,
	FSSVOLUME_PRIMITIVE_SIZE,
	FSSVOLUME_INNER_RADIUS,
	FSSVOLUME_INVERT,
	FSSVOLUME_FLUIDSAMPLEEXTENT,
	FSSVOLUME_LEVELSETQUALITY,
	FSSVOLUME_SAFESWEEP = 1010,
	FSSVOLUME_SOLID_TRANSLATION,
	FSSVOLUME_SOLID_ROTATION,

	FSSVOLUME_MESHSOURCE_SELECTOR,
	FSSVOLUME_TOGGLE_OBSTACLE,
	FSSVOLUME_CREATE_CSVOLUME,
	FSSVOLUME_CREATE_CSNEARSURFACE,
	FSSVOLUME_CREATE_ATTRACTOR,
	FSSVOLUME_NOGRIDOBSTACLE,
	FSSVOLUME_MESH_RETURN = 1019,
		FSSVOLUME_MESH_RETURN_OFF = 0,
		FSSVOLUME_MESH_RETURN_ONLYDYNAMICS,
		FSSVOLUME_MESH_RETURN_ONLYDYNAMICS_CLONER,
	FSSVOLUME_DISPLAY_PROPERTY = 1020,
	
	FSSVOLUME_DUMMY_

};

#endif