CONTAINER fx_xpresso_kinematic
{
     NAME fx_xpresso_kinematic;
     INCLUDE GVbase;
     GROUP ID_GVPROPERTIES
     {
	REAL XADVECTION_KINEMATIC_TIMESCALE	{ MIN 0.0; UNIT PERCENT; }
	VECTOR  XADVECTION_KINEMATIC_GRAVITY	{ UNIT METER; }

	LONG XADVECTION_KINEMATIC_INTEGRATOR
	{
		CYCLE
		{
			XADVECTION_KINEMATIC_INTEGRATOR_EULER;
			XADVECTION_KINEMATIC_INTEGRATOR_VERLET;
		}
	}
     }
     GROUP ID_GVPORTS
     {
        VECTOR  XADVECTION_KINEMATIC_INPOSOLD	{INPORT; STATICPORT; EDITPORT; CREATEPORT; NEEDCONNECTION; PORTONLY;}	
        VECTOR  XADVECTION_KINEMATIC_INVELOCITY	{INPORT; STATICPORT; EDITPORT; CREATEPORT; PORTONLY;}	
        VECTOR  XADVECTION_KINEMATIC_INPOS	{INPORT; STATICPORT; EDITPORT; CREATEPORT; NEEDCONNECTION; PORTONLY;}	
	VECTOR  XADVECTION_KINEMATIC_EXTERNAL	{INPORT; STATICPORT; EDITPORT; CREATEPORT; }

	VECTOR  XADVECTION_KINEMATIC_OUTPOS	{OUTPORT; STATICPORT; CREATEPORT;EDITPORT;}
	VECTOR  XADVECTION_KINEMATIC_OUTVELOCITY{OUTPORT; EDITPORT;}
     }
}
