#ifndef FX_XPRESSO_VOLUMECOLLIDER_H
#define FX_XPRESSO_VOLUMECOLLIDER_H

enum
{
	XVOLUMECOLLIDER_VOLUMES = 3000,
	XVOLUMECOLLIDER_POS,
	XVOLUMECOLLIDER_COLLIDED,
	XVOLUMECOLLIDER_COLLPOS,
	XVOLUMECOLLIDER_COLLN,
	XVOLUMECOLLIDER_COLLPOLYN,

	XVOLUMECOLLIDER_DUMMY

};

#endif