CONTAINER fx_xpresso_advection
{
     NAME fx_xpresso_advection;
     INCLUDE GVbase;
     GROUP ID_GVPROPERTIES
     {
	REAL	XADVECTION_TIMESCALE	{ MIN 0.0; UNIT PERCENT; }
	LONG	XADVECTION_INTEGRATOR
	{
		CYCLE
		{
			XADVECTION_INTEGRATOR_EULER1ST;
			XADVECTION_INTEGRATOR_RUNGA2ND;
			XADVECTION_INTEGRATOR_RUNGA4TH;
		}
	}
     }
     GROUP ID_GVPORTS
     {
        GVGENERALOBJECT	XADVECTION_DYNAMICS	{INPORT; STATICPORT; CREATEPORT; NEEDCONNECTION; ACCEPT{ fx_fluid; fx_liquid; fx_server; }}

	VECTOR  XADVECTION_INPOS	{INPORT; EDITPORT; CREATEPORT; NEEDCONNECTION;}
	MATRIX	XADVECTION_INMATRIX	{INPORT; EDITPORT; }

	VECTOR  XADVECTION_OUTPOS	{OUTPORT; STATICPORT; CREATEPORT;EDITPORT;}
	MATRIX  XADVECTION_OUTMATRIX	{OUTPORT; EDITPORT;}
     }
}
