CONTAINER fx_xpresso_cell
{
     NAME fx_xpresso_cell;
     INCLUDE GVbase;
     GROUP ID_GVPROPERTIES
     {	
	BOOL XCELL_SETCELL {}
     }
     GROUP ID_GVPORTS
     {
        GVGENERALOBJECT	XCELL_CHANNEL	
	{
		INPORT; STATICPORT; CREATEPORT; NEEDCONNECTION; 
		ACCEPT { fx_channel_velocity; fx_channel_levelset; fx_volume; fx_fluid; fx_liquid; fx_channel_scalar; fx_channel_temp; fx_channel_fuel; fx_channel_fire; fx_channel_vector; }
	}
	
	VECTOR	XCELL_C4DPOS		{INPORT; EDITPORT; }
	VECTOR	XCELL_PHYSICAL		{INPORT; EDITPORT; CREATEPORT;}
	VECTOR	XCELL_GCOORD		{MIN 0 0 0; INPORT; EDITPORT; }
	VECTOR	XCELL_VELINDEX		{MIN 0 0 0; INPORT; EDITPORT; }
	LONG	XCELL_INDEX		{MIN 0; INPORT; EDITPORT; }
	
	REAL	XCELL_VALUE		{MIN 0; STEP 0.01; INPORT; EDITPORT; CREATEPORT; }
	VECTOR	XCELL_VALUEV		{MIN 0 0 0; INPORT; EDITPORT; CREATEPORT; }
	
	REAL	XCELL_VALUE_OUT		{MIN 0; STEP 0.01; OUTPORT; EDITPORT; CREATEPORT; }
	VECTOR	XCELL_VALUEV_OUT		{MIN 0 0 0; OUTPORT; EDITPORT; CREATEPORT; }
     }
}
