CONTAINER fx_xpresso_volumecollider
{
     NAME fx_xpresso_volumecollider;
     INCLUDE GVbase;
     GROUP ID_GVPROPERTIES
     {
	
	IN_EXCLUDE XVOLUMECOLLIDER_VOLUMES
	{ 
		NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
		ACCEPT {  fx_volume; }; 
	}
     }
     GROUP ID_GVPORTS
     {
	VECTOR  XVOLUMECOLLIDER_POS	{INPORT; STATICPORT; EDITPORT; CREATEPORT; NEEDCONNECTION;}

	BOOL	XVOLUMECOLLIDER_COLLIDED{OUTPORT;}
	VECTOR  XVOLUMECOLLIDER_COLLPOS	{OUTPORT; STATICPORT; CREATEPORT;EDITPORT;}
	VECTOR  XVOLUMECOLLIDER_COLLN	{OUTPORT; CREATEPORT;EDITPORT;}
	VECTOR  XVOLUMECOLLIDER_COLLPOLYN{OUTPORT; EDITPORT;}
     }
}
