CONTAINER fx_xpresso_particleinfo
{
     NAME fx_xpresso_particleinfo;
     INCLUDE GVbase;

     GROUP ID_GVPROPERTIES
     {
	LINK	XPARTICLE_INFO_PARTICLEGROUP {ACCEPT{ fx_particlegroup; }}
	LONG	XPARTICLE_INFO_TYPE
	{
		CYCLE
		{
			XPARTICLE_INFO_TYPE_PASSIVE;
			XPARTICLE_INFO_TYPE_VORTICITY;
			XPARTICLE_INFO_TYPE_LIQUID;
			XPARTICLE_INFO_TYPE_DIFFUSE;
		}
	}
	IN_EXCLUDE XPARTICLE_INFO_PROPERTIES
	{ 
		NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 0;
		ACCEPT {  fx_property_scalar; fx_property_vector; }; 
	}
     }
     GROUP ID_GVPORTS
     {
	LONG		XPARTICLE_INFO_INDEX	{INPORT; STATICPORT; CREATEPORT; }

	VECTOR  XPARTICLE_INFO_POS		{OUTPORT; EDITPORT; CREATEPORT;}
	BOOL	XPARTICLE_INFO_ALIVE		{OUTPORT; EDITPORT; }
	BOOL	XPARTICLE_INFO_COLLISION	{OUTPORT; EDITPORT; }
	BOOL	XPARTICLE_INFO_SPRAY		{OUTPORT; EDITPORT; }
	BOOL	XPARTICLE_INFO_BUBBLE		{OUTPORT; EDITPORT; }
	BOOL	XPARTICLE_INFO_TEMP		{OUTPORT; EDITPORT; }
	
	REAL	XPARTICLE_INFO_PROP_SCALAR	{OUTPORT; MULTIPLE; }
	VECTOR	XPARTICLE_INFO_PROP_VECTOR	{OUTPORT; MULTIPLE; }
	BOOL	XPARTICLE_INFO_PROP_STATE	{OUTPORT; MULTIPLE; }
	LONG	XPARTICLE_INFO_COUNT		{OUTPORT; EDITPORT; }
	LONG	XPARTICLE_INFO_COUNTITER	{OUTPORT; EDITPORT; }
     }
}
