#ifndef FX_XPRESSO_PARTICLEINFO_H
#define FX_XPRESSO_PARTICLEINFO_H

enum
{
	XPARTICLE_INFO_PARTICLEGROUP = 3000,
	XPARTICLE_INFO_TYPE,
		XPARTICLE_INFO_TYPE_PASSIVE = 0,
		XPARTICLE_INFO_TYPE_VORTICITY,
		XPARTICLE_INFO_TYPE_LIQUID,
		XPARTICLE_INFO_TYPE_DIFFUSE,
	XPARTICLE_INFO_PROPERTIES,

	XPARTICLE_INFO_INDEX = 3050,
	XPARTICLE_INFO_POS,
	XPARTICLE_INFO_ALIVE,
	XPARTICLE_INFO_COLLISION,
	XPARTICLE_INFO_SPRAY,
	XPARTICLE_INFO_BUBBLE,
	XPARTICLE_INFO_TEMP,

	XPARTICLE_INFO_PROP_SCALAR,
	XPARTICLE_INFO_PROP_VECTOR,
	XPARTICLE_INFO_PROP_STATE,
	
	XPARTICLE_INFO_COUNT,
	XPARTICLE_INFO_COUNTITER,

	XPARTICLE_INFO_DUMMY

};

#endif