CONTAINER fx_xpresso_voxeliterator
{
     NAME fx_xpresso_voxeliterator;
     INCLUDE GVbase;
     GROUP ID_GVPROPERTIES
     {	
     }
     GROUP ID_GVPORTS
     {
	VECTOR  XVOXELITER_FROM	{MIN 0 0 0; INPORT; STATICPORT; CREATEPORT; }
	VECTOR  XVOXELITER_TO	{MIN 1 1 1; INPORT; STATICPORT; CREATEPORT;}
	VECTOR	XVOXELITER_OUT	{OUTPORT; STATICPORT; CREATEPORT;ITERATOR;}
     }
}
