#ifndef FX_XPRESSO_KINEMATIC_H
#define FX_XPRESSO_KINEMATIC_H

enum
{
	XADVECTION_KINEMATIC_TIMESCALE = 3000,
	XADVECTION_KINEMATIC_INTEGRATOR = 3001,
		XADVECTION_KINEMATIC_INTEGRATOR_EULER = 0,
		XADVECTION_KINEMATIC_INTEGRATOR_VERLET,
	XADVECTION_KINEMATIC_INPOS = 3002,
	XADVECTION_KINEMATIC_INPOSOLD,	
	XADVECTION_KINEMATIC_OUTPOS,
	XADVECTION_KINEMATIC_EXTERNAL,
	XADVECTION_KINEMATIC_GRAVITY,
	XADVECTION_KINEMATIC_INVELOCITY,
	XADVECTION_KINEMATIC_OUTVELOCITY,

	XADVECTION_KINEMATIC_DUMMY

};

#endif