#ifndef FX_XPRESSO_ADVECTION_H
#define FX_XPRESSO_ADVECTION_H

enum
{
	XADVECTION_TIMESCALE = 3000,
	XADVECTION_INTEGRATOR = 3001,
		XADVECTION_INTEGRATOR_EULER1ST = 0,
		XADVECTION_INTEGRATOR_RUNGA2ND,
		XADVECTION_INTEGRATOR_RUNGA4TH,
	XADVECTION_DYNAMICS = 3002,
	XADVECTION_INPOS,
	XADVECTION_INMATRIX,
	XADVECTION_OUTPOS,
	XADVECTION_OUTMATRIX,

	XADVECTION_DUMMY

};

#endif