CONTAINER fx_xpresso_spacetranslator
{
     NAME fx_xpresso_spacetranslator;

     INCLUDE GVbase;
     GROUP ID_GVPROPERTIES
     {	
	LINK	XSPACE_TRANSLATOR_SCENE	{ACCEPT{ fx_server; }}
	BOOL	XSPACE_TRANSLATOR_SUBGRIDSPACE	{HIDDEN;}

	LONG	XSPACE_TRANSLATOR_POSITIONTYPE
	{
		CYCLE
		{
			XSPACE_TRANSLATOR_POSITIONTYPE_WORLD;
			XSPACE_TRANSLATOR_POSITIONTYPE_PHYSICAL;
			XSPACE_TRANSLATOR_POSITIONTYPE_GRID;
		}
	}
	BOOL	XSPACE_GLOBAL_OUTPUT {}
     }
     GROUP ID_GVPORTS
     {
        GVGENERALOBJECT	XSPACE_TRANSLATOR_CHANNEL	
	{
		INPORT; STATICPORT; CREATEPORT; PORTONLY;
		ACCEPT { fx_volume; fx_fluid; fx_liquid; fx_channel_scalar; fx_channel_temp; fx_channel_fuel; fx_channel_fire; fx_channel_vector; }
	}
	VECTOR  XSPACE_TRANSLATOR_POS			{INPORT; STATICPORT; CREATEPORT; NEEDCONNECTION;}

	LONG	XSPACE_TRANSLATOR_OUT_INDEX		{OUTPORT; EDITPORT; CREATEPORT;}
	VECTOR  XSPACE_TRANSLATOR_OUT_GCOORD		{OUTPORT; EDITPORT;}
	VECTOR  XSPACE_TRANSLATOR_OUT_PHYSICAL		{OUTPORT; EDITPORT;}
	VECTOR  XSPACE_TRANSLATOR_OUT_PHYSICAL_GLB	{OUTPORT; EDITPORT;}
	VECTOR  XSPACE_TRANSLATOR_OUT_C4DWORLD		{OUTPORT; EDITPORT;}
	VECTOR  XSPACE_TRANSLATOR_OUT_C4DWORLD_GLB	{OUTPORT; EDITPORT;}
     }
}
